// Code generated by machine generator; DO NOT EDIT.
// Clippy: `#[must_use]` on functions returning `Option`/`Result` is intentional even though
// those types are already `#[must_use]`; the attribute surfaces better IDE messages.
#![allow(clippy::double_must_use)]

//! Utility for juniper packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2019 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! #
//! #  dictionary.juniper
//! #
//! #    As posted to the list by Eric Kilfoil <ekilfoil@uslec.net>
//! #
//! # Version:    $Id$
//! #
//!
//! VENDOR        Juniper                2636
//!
//! BEGIN-VENDOR    Juniper
//!
//! ATTRIBUTE    Juniper-Local-User-Name            1    string
//! ATTRIBUTE    Juniper-Allow-Commands            2    string
//! ATTRIBUTE    Juniper-Deny-Commands            3    string
//! ATTRIBUTE    Juniper-Allow-Configuration        4    string
//! ATTRIBUTE    Juniper-Deny-Configuration        5    string
//!
//! ATTRIBUTE    Juniper-Interactive-Command        8    string
//! ATTRIBUTE    Juniper-Configuration-Change        9    string
//! ATTRIBUTE    Juniper-User-Permissions        10    string
//! ATTRIBUTE    Juniper-Junosspace-Profile        11    string
//! ATTRIBUTE    Juniper-Junosspace-Profiles        11    string
//!
//! ATTRIBUTE    Juniper-CTP-Group            21    integer
//! ATTRIBUTE    Juniper-CTPView-APP-Group        22    integer
//! ATTRIBUTE    Juniper-CTPView-OS-Group        23    integer
//!
//! ATTRIBUTE    Juniper-Primary-Dns            31    ipaddr
//! ATTRIBUTE    Juniper-Primary-Wins            32    ipaddr
//! ATTRIBUTE    Juniper-Secondary-Dns            33    ipaddr
//! ATTRIBUTE    Juniper-Secondary-Wins            34    ipaddr
//! ATTRIBUTE    Juniper-Interface-id            35    string
//! ATTRIBUTE    Juniper-Ip-Pool-Name            36    string
//! ATTRIBUTE    Juniper-Keep-Alive            37    integer
//! ATTRIBUTE    Juniper-CoS-Traffic-Control-Profile    38    string
//! ATTRIBUTE    Juniper-CoS-Parameter            39    string
//! ATTRIBUTE    Juniper-encapsulation-overhead        40    integer
//! ATTRIBUTE    Juniper-cell-overhead            41    integer
//! ATTRIBUTE    Juniper-tx-connect-speed        42    integer
//! ATTRIBUTE    Juniper-rx-connect-speed        43    integer
//! ATTRIBUTE    Juniper-Firewall-filter-name        44    string
//! ATTRIBUTE    Juniper-Policer-Parameter        45    string
//! ATTRIBUTE    Juniper-Local-Group-Name        46    string
//! ATTRIBUTE    Juniper-Local-Interface            47    string
//! ATTRIBUTE    Juniper-Switching-Filter        48    string
//! ATTRIBUTE    Juniper-VoIP-Vlan            49    string
//! ATTRIBUTE    Juniper-CWA-Redirect            50    string
//!
//! ATTRIBUTE    Juniper-AV-Pair                52    string
//!
//! ATTRIBUTE    Juniper-DHCPv4-Options            55    octets
//! ATTRIBUTE    Juniper-DHCPv6-Options            207    octets
//! ATTRIBUTE    Juniper-DHCPv4-Packet-Header        208    octets
//! ATTRIBUTE    Juniper-DHCPv6-Packet-Header        209    octets
//! ATTRIBUTE    Juniper-Acct-Request-Reason        210    uint32
//!
//!
//! VALUE    Juniper-CTPView-APP-Group    Net_View        1
//! VALUE    Juniper-CTPView-APP-Group    Net_Admin        2
//! VALUE    Juniper-CTPView-APP-Group    Global_Admin        3
//!
//! VALUE    Juniper-CTP-Group        Read_Only        1
//! VALUE    Juniper-CTP-Group        Admin            2
//! VALUE    Juniper-CTP-Group        Privileged_Admin    3
//! VALUE    Juniper-CTP-Group        Auditor            4
//!
//! VALUE    Juniper-CTPView-OS-Group    Web_Manager        1
//! VALUE    Juniper-CTPView-OS-Group    System_Admin        2
//! VALUE    Juniper-CTPView-OS-Group    Auditor            3
//!
//! VALUE    Juniper-Acct-Request-Reason    IPv4-Active        0x0004
//! VALUE    Juniper-Acct-Request-Reason    IPv6-Active        0x0010
//! VALUE    Juniper-Acct-Request-Reason    Session-Active        0x0040
//!
//! END-VENDOR    Juniper
//! ```

use std::net::Ipv4Addr;

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;

pub const JUNIPER_LOCAL_USER_NAME_TYPE: AVPType = 1;
/// Delete all of `juniper_local_user_name` values from a packet.
pub fn delete_juniper_local_user_name(packet: &mut Packet) {
    packet.delete(JUNIPER_LOCAL_USER_NAME_TYPE);
}
/// Add `juniper_local_user_name` string value to a packet.
pub fn add_juniper_local_user_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_LOCAL_USER_NAME_TYPE, value));
}
/// Lookup a `juniper_local_user_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_local_user_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_local_user_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_LOCAL_USER_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_local_user_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_local_user_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_LOCAL_USER_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_ALLOW_COMMANDS_TYPE: AVPType = 2;
/// Delete all of `juniper_allow_commands` values from a packet.
pub fn delete_juniper_allow_commands(packet: &mut Packet) {
    packet.delete(JUNIPER_ALLOW_COMMANDS_TYPE);
}
/// Add `juniper_allow_commands` string value to a packet.
pub fn add_juniper_allow_commands(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_ALLOW_COMMANDS_TYPE, value));
}
/// Lookup a `juniper_allow_commands` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_allow_commands`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_allow_commands(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_ALLOW_COMMANDS_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_allow_commands` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_allow_commands(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_ALLOW_COMMANDS_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_DENY_COMMANDS_TYPE: AVPType = 3;
/// Delete all of `juniper_deny_commands` values from a packet.
pub fn delete_juniper_deny_commands(packet: &mut Packet) {
    packet.delete(JUNIPER_DENY_COMMANDS_TYPE);
}
/// Add `juniper_deny_commands` string value to a packet.
pub fn add_juniper_deny_commands(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_DENY_COMMANDS_TYPE, value));
}
/// Lookup a `juniper_deny_commands` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_deny_commands`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_deny_commands(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_DENY_COMMANDS_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_deny_commands` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_deny_commands(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_DENY_COMMANDS_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_ALLOW_CONFIGURATION_TYPE: AVPType = 4;
/// Delete all of `juniper_allow_configuration` values from a packet.
pub fn delete_juniper_allow_configuration(packet: &mut Packet) {
    packet.delete(JUNIPER_ALLOW_CONFIGURATION_TYPE);
}
/// Add `juniper_allow_configuration` string value to a packet.
pub fn add_juniper_allow_configuration(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_ALLOW_CONFIGURATION_TYPE, value));
}
/// Lookup a `juniper_allow_configuration` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_allow_configuration`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_allow_configuration(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_ALLOW_CONFIGURATION_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_allow_configuration` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_allow_configuration(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_ALLOW_CONFIGURATION_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_DENY_CONFIGURATION_TYPE: AVPType = 5;
/// Delete all of `juniper_deny_configuration` values from a packet.
pub fn delete_juniper_deny_configuration(packet: &mut Packet) {
    packet.delete(JUNIPER_DENY_CONFIGURATION_TYPE);
}
/// Add `juniper_deny_configuration` string value to a packet.
pub fn add_juniper_deny_configuration(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_DENY_CONFIGURATION_TYPE, value));
}
/// Lookup a `juniper_deny_configuration` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_deny_configuration`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_deny_configuration(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_DENY_CONFIGURATION_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_deny_configuration` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_deny_configuration(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_DENY_CONFIGURATION_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_INTERACTIVE_COMMAND_TYPE: AVPType = 8;
/// Delete all of `juniper_interactive_command` values from a packet.
pub fn delete_juniper_interactive_command(packet: &mut Packet) {
    packet.delete(JUNIPER_INTERACTIVE_COMMAND_TYPE);
}
/// Add `juniper_interactive_command` string value to a packet.
pub fn add_juniper_interactive_command(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_INTERACTIVE_COMMAND_TYPE, value));
}
/// Lookup a `juniper_interactive_command` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_interactive_command`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_interactive_command(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_INTERACTIVE_COMMAND_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_interactive_command` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_interactive_command(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_INTERACTIVE_COMMAND_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_CONFIGURATION_CHANGE_TYPE: AVPType = 9;
/// Delete all of `juniper_configuration_change` values from a packet.
pub fn delete_juniper_configuration_change(packet: &mut Packet) {
    packet.delete(JUNIPER_CONFIGURATION_CHANGE_TYPE);
}
/// Add `juniper_configuration_change` string value to a packet.
pub fn add_juniper_configuration_change(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_CONFIGURATION_CHANGE_TYPE, value));
}
/// Lookup a `juniper_configuration_change` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_configuration_change`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_configuration_change(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_CONFIGURATION_CHANGE_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_configuration_change` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_configuration_change(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CONFIGURATION_CHANGE_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_USER_PERMISSIONS_TYPE: AVPType = 10;
/// Delete all of `juniper_user_permissions` values from a packet.
pub fn delete_juniper_user_permissions(packet: &mut Packet) {
    packet.delete(JUNIPER_USER_PERMISSIONS_TYPE);
}
/// Add `juniper_user_permissions` string value to a packet.
pub fn add_juniper_user_permissions(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_USER_PERMISSIONS_TYPE, value));
}
/// Lookup a `juniper_user_permissions` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_user_permissions`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_user_permissions(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_USER_PERMISSIONS_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_user_permissions` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_user_permissions(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_USER_PERMISSIONS_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_JUNOSSPACE_PROFILE_TYPE: AVPType = 11;
/// Delete all of `juniper_junosspace_profile` values from a packet.
pub fn delete_juniper_junosspace_profile(packet: &mut Packet) {
    packet.delete(JUNIPER_JUNOSSPACE_PROFILE_TYPE);
}
/// Add `juniper_junosspace_profile` string value to a packet.
pub fn add_juniper_junosspace_profile(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_JUNOSSPACE_PROFILE_TYPE, value));
}
/// Lookup a `juniper_junosspace_profile` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_junosspace_profile`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_junosspace_profile(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_JUNOSSPACE_PROFILE_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_junosspace_profile` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_junosspace_profile(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_JUNOSSPACE_PROFILE_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_CTP_GROUP_TYPE: AVPType = 21;
/// Delete all of `juniper_ctp_group` values from a packet.
pub fn delete_juniper_ctp_group(packet: &mut Packet) {
    packet.delete(JUNIPER_CTP_GROUP_TYPE);
}
/// Add `juniper_ctp_group` value-defined integer value to a packet.
pub fn add_juniper_ctp_group(packet: &mut Packet, value: JuniperCTPGroup) {
    packet.add(AVP::from_u32(JUNIPER_CTP_GROUP_TYPE, value));
}
/// Lookup a `juniper_ctp_group` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_ctp_group`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_ctp_group(packet: &Packet) -> Option<Result<JuniperCTPGroup, AVPError>> {
    packet
        .lookup(JUNIPER_CTP_GROUP_TYPE)
        .map(|v| Ok(v.encode_u32()? as JuniperCTPGroup))
}
/// Lookup all of the `juniper_ctp_group` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_ctp_group(packet: &Packet) -> Result<Vec<JuniperCTPGroup>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CTP_GROUP_TYPE) {
        vec.push(avp.encode_u32()? as JuniperCTPGroup);
    }
    Ok(vec)
}

pub const JUNIPER_CTP_VIEW_APP_GROUP_TYPE: AVPType = 22;
/// Delete all of `juniper_ctp_view_app_group` values from a packet.
pub fn delete_juniper_ctp_view_app_group(packet: &mut Packet) {
    packet.delete(JUNIPER_CTP_VIEW_APP_GROUP_TYPE);
}
/// Add `juniper_ctp_view_app_group` value-defined integer value to a packet.
pub fn add_juniper_ctp_view_app_group(packet: &mut Packet, value: JuniperCTPViewAPPGroup) {
    packet.add(AVP::from_u32(JUNIPER_CTP_VIEW_APP_GROUP_TYPE, value));
}
/// Lookup a `juniper_ctp_view_app_group` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_ctp_view_app_group`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_ctp_view_app_group(
    packet: &Packet,
) -> Option<Result<JuniperCTPViewAPPGroup, AVPError>> {
    packet
        .lookup(JUNIPER_CTP_VIEW_APP_GROUP_TYPE)
        .map(|v| Ok(v.encode_u32()? as JuniperCTPViewAPPGroup))
}
/// Lookup all of the `juniper_ctp_view_app_group` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_ctp_view_app_group(
    packet: &Packet,
) -> Result<Vec<JuniperCTPViewAPPGroup>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CTP_VIEW_APP_GROUP_TYPE) {
        vec.push(avp.encode_u32()? as JuniperCTPViewAPPGroup);
    }
    Ok(vec)
}

pub const JUNIPER_CTP_VIEW_OS_GROUP_TYPE: AVPType = 23;
/// Delete all of `juniper_ctp_view_os_group` values from a packet.
pub fn delete_juniper_ctp_view_os_group(packet: &mut Packet) {
    packet.delete(JUNIPER_CTP_VIEW_OS_GROUP_TYPE);
}
/// Add `juniper_ctp_view_os_group` value-defined integer value to a packet.
pub fn add_juniper_ctp_view_os_group(packet: &mut Packet, value: JuniperCTPViewOSGroup) {
    packet.add(AVP::from_u32(JUNIPER_CTP_VIEW_OS_GROUP_TYPE, value));
}
/// Lookup a `juniper_ctp_view_os_group` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_ctp_view_os_group`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_ctp_view_os_group(
    packet: &Packet,
) -> Option<Result<JuniperCTPViewOSGroup, AVPError>> {
    packet
        .lookup(JUNIPER_CTP_VIEW_OS_GROUP_TYPE)
        .map(|v| Ok(v.encode_u32()? as JuniperCTPViewOSGroup))
}
/// Lookup all of the `juniper_ctp_view_os_group` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_ctp_view_os_group(
    packet: &Packet,
) -> Result<Vec<JuniperCTPViewOSGroup>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CTP_VIEW_OS_GROUP_TYPE) {
        vec.push(avp.encode_u32()? as JuniperCTPViewOSGroup);
    }
    Ok(vec)
}

pub const JUNIPER_PRIMARY_DNS_TYPE: AVPType = 31;
/// Delete all of `juniper_primary_dns` values from a packet.
pub fn delete_juniper_primary_dns(packet: &mut Packet) {
    packet.delete(JUNIPER_PRIMARY_DNS_TYPE);
}
/// Add `juniper_primary_dns` ipaddr value to a packet.
pub fn add_juniper_primary_dns(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(JUNIPER_PRIMARY_DNS_TYPE, value));
}
/// Lookup a `juniper_primary_dns` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_primary_dns`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_primary_dns(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(JUNIPER_PRIMARY_DNS_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `juniper_primary_dns` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_primary_dns(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_PRIMARY_DNS_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const JUNIPER_PRIMARY_WINS_TYPE: AVPType = 32;
/// Delete all of `juniper_primary_wins` values from a packet.
pub fn delete_juniper_primary_wins(packet: &mut Packet) {
    packet.delete(JUNIPER_PRIMARY_WINS_TYPE);
}
/// Add `juniper_primary_wins` ipaddr value to a packet.
pub fn add_juniper_primary_wins(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(JUNIPER_PRIMARY_WINS_TYPE, value));
}
/// Lookup a `juniper_primary_wins` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_primary_wins`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_primary_wins(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(JUNIPER_PRIMARY_WINS_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `juniper_primary_wins` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_primary_wins(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_PRIMARY_WINS_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const JUNIPER_SECONDARY_DNS_TYPE: AVPType = 33;
/// Delete all of `juniper_secondary_dns` values from a packet.
pub fn delete_juniper_secondary_dns(packet: &mut Packet) {
    packet.delete(JUNIPER_SECONDARY_DNS_TYPE);
}
/// Add `juniper_secondary_dns` ipaddr value to a packet.
pub fn add_juniper_secondary_dns(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(JUNIPER_SECONDARY_DNS_TYPE, value));
}
/// Lookup a `juniper_secondary_dns` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_secondary_dns`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_secondary_dns(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(JUNIPER_SECONDARY_DNS_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `juniper_secondary_dns` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_secondary_dns(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_SECONDARY_DNS_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const JUNIPER_SECONDARY_WINS_TYPE: AVPType = 34;
/// Delete all of `juniper_secondary_wins` values from a packet.
pub fn delete_juniper_secondary_wins(packet: &mut Packet) {
    packet.delete(JUNIPER_SECONDARY_WINS_TYPE);
}
/// Add `juniper_secondary_wins` ipaddr value to a packet.
pub fn add_juniper_secondary_wins(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(JUNIPER_SECONDARY_WINS_TYPE, value));
}
/// Lookup a `juniper_secondary_wins` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_secondary_wins`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_secondary_wins(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(JUNIPER_SECONDARY_WINS_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `juniper_secondary_wins` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_secondary_wins(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_SECONDARY_WINS_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const JUNIPER_INTERFACE_ID_TYPE: AVPType = 35;
/// Delete all of `juniper_interface_id` values from a packet.
pub fn delete_juniper_interface_id(packet: &mut Packet) {
    packet.delete(JUNIPER_INTERFACE_ID_TYPE);
}
/// Add `juniper_interface_id` string value to a packet.
pub fn add_juniper_interface_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_INTERFACE_ID_TYPE, value));
}
/// Lookup a `juniper_interface_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_interface_id`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_interface_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_INTERFACE_ID_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_interface_id` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_interface_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_INTERFACE_ID_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_IP_POOL_NAME_TYPE: AVPType = 36;
/// Delete all of `juniper_ip_pool_name` values from a packet.
pub fn delete_juniper_ip_pool_name(packet: &mut Packet) {
    packet.delete(JUNIPER_IP_POOL_NAME_TYPE);
}
/// Add `juniper_ip_pool_name` string value to a packet.
pub fn add_juniper_ip_pool_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_IP_POOL_NAME_TYPE, value));
}
/// Lookup a `juniper_ip_pool_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_ip_pool_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_ip_pool_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_IP_POOL_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_ip_pool_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_ip_pool_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_IP_POOL_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_KEEP_ALIVE_TYPE: AVPType = 37;
/// Delete all of `juniper_keep_alive` values from a packet.
pub fn delete_juniper_keep_alive(packet: &mut Packet) {
    packet.delete(JUNIPER_KEEP_ALIVE_TYPE);
}
/// Add `juniper_keep_alive` integer value to a packet.
pub fn add_juniper_keep_alive(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(JUNIPER_KEEP_ALIVE_TYPE, value));
}
/// Lookup a `juniper_keep_alive` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_keep_alive`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_keep_alive(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet.lookup(JUNIPER_KEEP_ALIVE_TYPE).map(AVP::encode_u32)
}
/// Lookup all of the `juniper_keep_alive` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_keep_alive(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_KEEP_ALIVE_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const JUNIPER_CO_S_TRAFFIC_CONTROL_PROFILE_TYPE: AVPType = 38;
/// Delete all of `juniper_co_s_traffic_control_profile` values from a packet.
pub fn delete_juniper_co_s_traffic_control_profile(packet: &mut Packet) {
    packet.delete(JUNIPER_CO_S_TRAFFIC_CONTROL_PROFILE_TYPE);
}
/// Add `juniper_co_s_traffic_control_profile` string value to a packet.
pub fn add_juniper_co_s_traffic_control_profile(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(
        JUNIPER_CO_S_TRAFFIC_CONTROL_PROFILE_TYPE,
        value,
    ));
}
/// Lookup a `juniper_co_s_traffic_control_profile` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_co_s_traffic_control_profile`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_co_s_traffic_control_profile(
    packet: &Packet,
) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_CO_S_TRAFFIC_CONTROL_PROFILE_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_co_s_traffic_control_profile` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_co_s_traffic_control_profile(
    packet: &Packet,
) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CO_S_TRAFFIC_CONTROL_PROFILE_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_CO_S_PARAMETER_TYPE: AVPType = 39;
/// Delete all of `juniper_co_s_parameter` values from a packet.
pub fn delete_juniper_co_s_parameter(packet: &mut Packet) {
    packet.delete(JUNIPER_CO_S_PARAMETER_TYPE);
}
/// Add `juniper_co_s_parameter` string value to a packet.
pub fn add_juniper_co_s_parameter(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_CO_S_PARAMETER_TYPE, value));
}
/// Lookup a `juniper_co_s_parameter` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_co_s_parameter`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_co_s_parameter(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_CO_S_PARAMETER_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_co_s_parameter` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_co_s_parameter(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CO_S_PARAMETER_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_ENCAPSULATION_OVERHEAD_TYPE: AVPType = 40;
/// Delete all of `juniper_encapsulation_overhead` values from a packet.
pub fn delete_juniper_encapsulation_overhead(packet: &mut Packet) {
    packet.delete(JUNIPER_ENCAPSULATION_OVERHEAD_TYPE);
}
/// Add `juniper_encapsulation_overhead` integer value to a packet.
pub fn add_juniper_encapsulation_overhead(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(JUNIPER_ENCAPSULATION_OVERHEAD_TYPE, value));
}
/// Lookup a `juniper_encapsulation_overhead` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_encapsulation_overhead`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_encapsulation_overhead(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(JUNIPER_ENCAPSULATION_OVERHEAD_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `juniper_encapsulation_overhead` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_encapsulation_overhead(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_ENCAPSULATION_OVERHEAD_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const JUNIPER_CELL_OVERHEAD_TYPE: AVPType = 41;
/// Delete all of `juniper_cell_overhead` values from a packet.
pub fn delete_juniper_cell_overhead(packet: &mut Packet) {
    packet.delete(JUNIPER_CELL_OVERHEAD_TYPE);
}
/// Add `juniper_cell_overhead` integer value to a packet.
pub fn add_juniper_cell_overhead(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(JUNIPER_CELL_OVERHEAD_TYPE, value));
}
/// Lookup a `juniper_cell_overhead` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_cell_overhead`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_cell_overhead(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(JUNIPER_CELL_OVERHEAD_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `juniper_cell_overhead` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_cell_overhead(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CELL_OVERHEAD_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const JUNIPER_TX_CONNECT_SPEED_TYPE: AVPType = 42;
/// Delete all of `juniper_tx_connect_speed` values from a packet.
pub fn delete_juniper_tx_connect_speed(packet: &mut Packet) {
    packet.delete(JUNIPER_TX_CONNECT_SPEED_TYPE);
}
/// Add `juniper_tx_connect_speed` integer value to a packet.
pub fn add_juniper_tx_connect_speed(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(JUNIPER_TX_CONNECT_SPEED_TYPE, value));
}
/// Lookup a `juniper_tx_connect_speed` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_tx_connect_speed`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_tx_connect_speed(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(JUNIPER_TX_CONNECT_SPEED_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `juniper_tx_connect_speed` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_tx_connect_speed(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_TX_CONNECT_SPEED_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const JUNIPER_RX_CONNECT_SPEED_TYPE: AVPType = 43;
/// Delete all of `juniper_rx_connect_speed` values from a packet.
pub fn delete_juniper_rx_connect_speed(packet: &mut Packet) {
    packet.delete(JUNIPER_RX_CONNECT_SPEED_TYPE);
}
/// Add `juniper_rx_connect_speed` integer value to a packet.
pub fn add_juniper_rx_connect_speed(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(JUNIPER_RX_CONNECT_SPEED_TYPE, value));
}
/// Lookup a `juniper_rx_connect_speed` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_rx_connect_speed`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_rx_connect_speed(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(JUNIPER_RX_CONNECT_SPEED_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `juniper_rx_connect_speed` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_rx_connect_speed(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_RX_CONNECT_SPEED_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const JUNIPER_FIREWALL_FILTER_NAME_TYPE: AVPType = 44;
/// Delete all of `juniper_firewall_filter_name` values from a packet.
pub fn delete_juniper_firewall_filter_name(packet: &mut Packet) {
    packet.delete(JUNIPER_FIREWALL_FILTER_NAME_TYPE);
}
/// Add `juniper_firewall_filter_name` string value to a packet.
pub fn add_juniper_firewall_filter_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_FIREWALL_FILTER_NAME_TYPE, value));
}
/// Lookup a `juniper_firewall_filter_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_firewall_filter_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_firewall_filter_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_FIREWALL_FILTER_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_firewall_filter_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_firewall_filter_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_FIREWALL_FILTER_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_POLICER_PARAMETER_TYPE: AVPType = 45;
/// Delete all of `juniper_policer_parameter` values from a packet.
pub fn delete_juniper_policer_parameter(packet: &mut Packet) {
    packet.delete(JUNIPER_POLICER_PARAMETER_TYPE);
}
/// Add `juniper_policer_parameter` string value to a packet.
pub fn add_juniper_policer_parameter(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_POLICER_PARAMETER_TYPE, value));
}
/// Lookup a `juniper_policer_parameter` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_policer_parameter`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_policer_parameter(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_POLICER_PARAMETER_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_policer_parameter` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_policer_parameter(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_POLICER_PARAMETER_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_LOCAL_GROUP_NAME_TYPE: AVPType = 46;
/// Delete all of `juniper_local_group_name` values from a packet.
pub fn delete_juniper_local_group_name(packet: &mut Packet) {
    packet.delete(JUNIPER_LOCAL_GROUP_NAME_TYPE);
}
/// Add `juniper_local_group_name` string value to a packet.
pub fn add_juniper_local_group_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_LOCAL_GROUP_NAME_TYPE, value));
}
/// Lookup a `juniper_local_group_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_local_group_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_local_group_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_LOCAL_GROUP_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_local_group_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_local_group_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_LOCAL_GROUP_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_LOCAL_INTERFACE_TYPE: AVPType = 47;
/// Delete all of `juniper_local_interface` values from a packet.
pub fn delete_juniper_local_interface(packet: &mut Packet) {
    packet.delete(JUNIPER_LOCAL_INTERFACE_TYPE);
}
/// Add `juniper_local_interface` string value to a packet.
pub fn add_juniper_local_interface(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_LOCAL_INTERFACE_TYPE, value));
}
/// Lookup a `juniper_local_interface` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_local_interface`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_local_interface(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_LOCAL_INTERFACE_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_local_interface` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_local_interface(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_LOCAL_INTERFACE_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_SWITCHING_FILTER_TYPE: AVPType = 48;
/// Delete all of `juniper_switching_filter` values from a packet.
pub fn delete_juniper_switching_filter(packet: &mut Packet) {
    packet.delete(JUNIPER_SWITCHING_FILTER_TYPE);
}
/// Add `juniper_switching_filter` string value to a packet.
pub fn add_juniper_switching_filter(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_SWITCHING_FILTER_TYPE, value));
}
/// Lookup a `juniper_switching_filter` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_switching_filter`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_switching_filter(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_SWITCHING_FILTER_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_switching_filter` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_switching_filter(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_SWITCHING_FILTER_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_VO_IP_VLAN_TYPE: AVPType = 49;
/// Delete all of `juniper_vo_ip_vlan` values from a packet.
pub fn delete_juniper_vo_ip_vlan(packet: &mut Packet) {
    packet.delete(JUNIPER_VO_IP_VLAN_TYPE);
}
/// Add `juniper_vo_ip_vlan` string value to a packet.
pub fn add_juniper_vo_ip_vlan(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_VO_IP_VLAN_TYPE, value));
}
/// Lookup a `juniper_vo_ip_vlan` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_vo_ip_vlan`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_vo_ip_vlan(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_VO_IP_VLAN_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_vo_ip_vlan` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_vo_ip_vlan(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_VO_IP_VLAN_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_CWA_REDIRECT_TYPE: AVPType = 50;
/// Delete all of `juniper_cwa_redirect` values from a packet.
pub fn delete_juniper_cwa_redirect(packet: &mut Packet) {
    packet.delete(JUNIPER_CWA_REDIRECT_TYPE);
}
/// Add `juniper_cwa_redirect` string value to a packet.
pub fn add_juniper_cwa_redirect(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_CWA_REDIRECT_TYPE, value));
}
/// Lookup a `juniper_cwa_redirect` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_cwa_redirect`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_cwa_redirect(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(JUNIPER_CWA_REDIRECT_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `juniper_cwa_redirect` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_cwa_redirect(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_CWA_REDIRECT_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_AV_PAIR_TYPE: AVPType = 52;
/// Delete all of `juniper_av_pair` values from a packet.
pub fn delete_juniper_av_pair(packet: &mut Packet) {
    packet.delete(JUNIPER_AV_PAIR_TYPE);
}
/// Add `juniper_av_pair` string value to a packet.
pub fn add_juniper_av_pair(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(JUNIPER_AV_PAIR_TYPE, value));
}
/// Lookup a `juniper_av_pair` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_av_pair`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_av_pair(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(JUNIPER_AV_PAIR_TYPE).map(AVP::encode_string)
}
/// Lookup all of the `juniper_av_pair` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_av_pair(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_AV_PAIR_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const JUNIPER_DHC_PV_4_OPTIONS_TYPE: AVPType = 55;
/// Delete all of `juniper_dhc_pv_4_options` values from a packet.
pub fn delete_juniper_dhc_pv_4_options(packet: &mut Packet) {
    packet.delete(JUNIPER_DHC_PV_4_OPTIONS_TYPE);
}
/// Add `juniper_dhc_pv_4_options` octets value to a packet.
pub fn add_juniper_dhc_pv_4_options(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(JUNIPER_DHC_PV_4_OPTIONS_TYPE, value));
}
/// Lookup a `juniper_dhc_pv_4_options` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_dhc_pv_4_options`, it returns `None`.
#[must_use]
pub fn lookup_juniper_dhc_pv_4_options(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(JUNIPER_DHC_PV_4_OPTIONS_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `juniper_dhc_pv_4_options` octets value from a packet.
#[must_use]
pub fn lookup_all_juniper_dhc_pv_4_options(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_DHC_PV_4_OPTIONS_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const JUNIPER_DHC_PV_6_OPTIONS_TYPE: AVPType = 207;
/// Delete all of `juniper_dhc_pv_6_options` values from a packet.
pub fn delete_juniper_dhc_pv_6_options(packet: &mut Packet) {
    packet.delete(JUNIPER_DHC_PV_6_OPTIONS_TYPE);
}
/// Add `juniper_dhc_pv_6_options` octets value to a packet.
pub fn add_juniper_dhc_pv_6_options(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(JUNIPER_DHC_PV_6_OPTIONS_TYPE, value));
}
/// Lookup a `juniper_dhc_pv_6_options` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_dhc_pv_6_options`, it returns `None`.
#[must_use]
pub fn lookup_juniper_dhc_pv_6_options(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(JUNIPER_DHC_PV_6_OPTIONS_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `juniper_dhc_pv_6_options` octets value from a packet.
#[must_use]
pub fn lookup_all_juniper_dhc_pv_6_options(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_DHC_PV_6_OPTIONS_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const JUNIPER_DHC_PV_4_PACKET_HEADER_TYPE: AVPType = 208;
/// Delete all of `juniper_dhc_pv_4_packet_header` values from a packet.
pub fn delete_juniper_dhc_pv_4_packet_header(packet: &mut Packet) {
    packet.delete(JUNIPER_DHC_PV_4_PACKET_HEADER_TYPE);
}
/// Add `juniper_dhc_pv_4_packet_header` octets value to a packet.
pub fn add_juniper_dhc_pv_4_packet_header(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(JUNIPER_DHC_PV_4_PACKET_HEADER_TYPE, value));
}
/// Lookup a `juniper_dhc_pv_4_packet_header` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_dhc_pv_4_packet_header`, it returns `None`.
#[must_use]
pub fn lookup_juniper_dhc_pv_4_packet_header(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(JUNIPER_DHC_PV_4_PACKET_HEADER_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `juniper_dhc_pv_4_packet_header` octets value from a packet.
#[must_use]
pub fn lookup_all_juniper_dhc_pv_4_packet_header(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_DHC_PV_4_PACKET_HEADER_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const JUNIPER_DHC_PV_6_PACKET_HEADER_TYPE: AVPType = 209;
/// Delete all of `juniper_dhc_pv_6_packet_header` values from a packet.
pub fn delete_juniper_dhc_pv_6_packet_header(packet: &mut Packet) {
    packet.delete(JUNIPER_DHC_PV_6_PACKET_HEADER_TYPE);
}
/// Add `juniper_dhc_pv_6_packet_header` octets value to a packet.
pub fn add_juniper_dhc_pv_6_packet_header(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(JUNIPER_DHC_PV_6_PACKET_HEADER_TYPE, value));
}
/// Lookup a `juniper_dhc_pv_6_packet_header` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_dhc_pv_6_packet_header`, it returns `None`.
#[must_use]
pub fn lookup_juniper_dhc_pv_6_packet_header(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(JUNIPER_DHC_PV_6_PACKET_HEADER_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `juniper_dhc_pv_6_packet_header` octets value from a packet.
#[must_use]
pub fn lookup_all_juniper_dhc_pv_6_packet_header(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_DHC_PV_6_PACKET_HEADER_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const JUNIPER_ACCT_REQUEST_REASON_TYPE: AVPType = 210;
/// Delete all of `juniper_acct_request_reason` values from a packet.
pub fn delete_juniper_acct_request_reason(packet: &mut Packet) {
    packet.delete(JUNIPER_ACCT_REQUEST_REASON_TYPE);
}
/// Add `juniper_acct_request_reason` value-defined integer value to a packet.
pub fn add_juniper_acct_request_reason(packet: &mut Packet, value: JuniperAcctRequestReason) {
    packet.add(AVP::from_u32(JUNIPER_ACCT_REQUEST_REASON_TYPE, value));
}
/// Lookup a `juniper_acct_request_reason` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `juniper_acct_request_reason`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_juniper_acct_request_reason(
    packet: &Packet,
) -> Option<Result<JuniperAcctRequestReason, AVPError>> {
    packet
        .lookup(JUNIPER_ACCT_REQUEST_REASON_TYPE)
        .map(|v| Ok(v.encode_u32()? as JuniperAcctRequestReason))
}
/// Lookup all of the `juniper_acct_request_reason` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_juniper_acct_request_reason(
    packet: &Packet,
) -> Result<Vec<JuniperAcctRequestReason>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(JUNIPER_ACCT_REQUEST_REASON_TYPE) {
        vec.push(avp.encode_u32()? as JuniperAcctRequestReason);
    }
    Ok(vec)
}

pub type JuniperAcctRequestReason = u32;
pub const JUNIPER_ACCT_REQUEST_REASON_I_PV_4_ACTIVE: JuniperAcctRequestReason = 4;
pub const JUNIPER_ACCT_REQUEST_REASON_I_PV_6_ACTIVE: JuniperAcctRequestReason = 16;
pub const JUNIPER_ACCT_REQUEST_REASON_SESSION_ACTIVE: JuniperAcctRequestReason = 64;

pub type JuniperCTPGroup = u32;
pub const JUNIPER_CTP_GROUP_READ_ONLY: JuniperCTPGroup = 1;
pub const JUNIPER_CTP_GROUP_ADMIN: JuniperCTPGroup = 2;
pub const JUNIPER_CTP_GROUP_PRIVILEGED_ADMIN: JuniperCTPGroup = 3;
pub const JUNIPER_CTP_GROUP_AUDITOR: JuniperCTPGroup = 4;

pub type JuniperCTPViewAPPGroup = u32;
pub const JUNIPER_CTP_VIEW_APP_GROUP_NET_VIEW: JuniperCTPViewAPPGroup = 1;
pub const JUNIPER_CTP_VIEW_APP_GROUP_NET_ADMIN: JuniperCTPViewAPPGroup = 2;
pub const JUNIPER_CTP_VIEW_APP_GROUP_GLOBAL_ADMIN: JuniperCTPViewAPPGroup = 3;

pub type JuniperCTPViewOSGroup = u32;
pub const JUNIPER_CTP_VIEW_OS_GROUP_WEB_MANAGER: JuniperCTPViewOSGroup = 1;
pub const JUNIPER_CTP_VIEW_OS_GROUP_SYSTEM_ADMIN: JuniperCTPViewOSGroup = 2;
pub const JUNIPER_CTP_VIEW_OS_GROUP_AUDITOR: JuniperCTPViewOSGroup = 3;
