// Code generated by machine generator; DO NOT EDIT.
// Clippy: `#[must_use]` on functions returning `Option`/`Result` is intentional even though
// those types are already `#[must_use]`; the attribute surfaces better IDE messages.
#![allow(clippy::double_must_use)]

//! Utility for microsoft packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2019 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! #
//! #    Microsoft's VSA's, from RFC 2548
//! #
//! #    $Id$
//! #
//!
//! VENDOR        Microsoft            311
//!
//! BEGIN-VENDOR    Microsoft
//! ATTRIBUTE    MS-CHAP-Response            1    octets[50]
//! ATTRIBUTE    MS-CHAP-Error                2    string
//! ATTRIBUTE    MS-CHAP-CPW-1                3    octets[70]
//! ATTRIBUTE    MS-CHAP-CPW-2                4    octets[84]
//! ATTRIBUTE    MS-CHAP-LM-Enc-PW            5    octets
//! ATTRIBUTE    MS-CHAP-NT-Enc-PW            6    octets    secret
//! ATTRIBUTE    MS-MPPE-Encryption-Policy        7    integer
//!
//! VALUE    MS-MPPE-Encryption-Policy    Encryption-Allowed    1
//! VALUE    MS-MPPE-Encryption-Policy    Encryption-Required    2
//!
//! # This is referred to as both singular and plural in the RFC.
//! # Plural seems to make more sense.
//! ATTRIBUTE    MS-MPPE-Encryption-Type            8    integer
//! ATTRIBUTE    MS-MPPE-Encryption-Types        8    integer
//!
//! VALUE    MS-MPPE-Encryption-Types    RC4-40bit-Allowed    1
//! VALUE    MS-MPPE-Encryption-Types    RC4-128bit-Allowed    2
//! VALUE    MS-MPPE-Encryption-Types    RC4-40or128-bit-Allowed    6
//!
//! ATTRIBUTE    MS-RAS-Vendor                9    integer    # content is Vendor-ID
//! ATTRIBUTE    MS-CHAP-Domain                10    string
//! ATTRIBUTE    MS-CHAP-Challenge            11    octets    secret
//! ATTRIBUTE    MS-CHAP-MPPE-Keys            12    octets[24]  encrypt=1
//! ATTRIBUTE    MS-BAP-Usage                13    integer
//! ATTRIBUTE    MS-Link-Utilization-Threshold        14    integer # values are 1-100
//! ATTRIBUTE    MS-Link-Drop-Time-Limit            15    integer
//! ATTRIBUTE    MS-MPPE-Send-Key            16    octets    encrypt=2
//! ATTRIBUTE    MS-MPPE-Recv-Key            17    octets    encrypt=2
//! ATTRIBUTE    MS-RAS-Version                18    string
//! ATTRIBUTE    MS-Old-ARAP-Password            19    octets
//! ATTRIBUTE    MS-New-ARAP-Password            20    octets
//! ATTRIBUTE    MS-ARAP-PW-Change-Reason        21    integer
//!
//! ATTRIBUTE    MS-Filter                22    octets
//! ATTRIBUTE    MS-Acct-Auth-Type            23    integer
//! ATTRIBUTE    MS-Acct-EAP-Type            24    integer
//!
//! ATTRIBUTE    MS-CHAP2-Response            25    octets[50]
//! ATTRIBUTE    MS-CHAP2-Success            26    octets
//! ATTRIBUTE    MS-CHAP2-CPW                27    octets[68]
//!
//! ATTRIBUTE    MS-Primary-DNS-Server            28    ipaddr
//! ATTRIBUTE    MS-Secondary-DNS-Server            29    ipaddr
//! ATTRIBUTE    MS-Primary-NBNS-Server            30    ipaddr
//! ATTRIBUTE    MS-Secondary-NBNS-Server        31    ipaddr
//!
//! #ATTRIBUTE    MS-ARAP-Challenge            33    octets[8]
//!
//! ## MS-RNAP
//! #
//! # http://download.microsoft.com/download/9/5/E/95EF66AF-9026-4BB0-A41D-A4F81802D92C/%5BMS-RNAP%5D.pdf
//!
//! ATTRIBUTE    MS-RAS-Client-Name            34    string
//! ATTRIBUTE    MS-RAS-Client-Version            35    string
//! ATTRIBUTE    MS-Quarantine-IPFilter            36    octets
//! ATTRIBUTE    MS-Quarantine-Session-Timeout        37    integer
//! ATTRIBUTE    MS-User-Security-Identity        40    string
//! ATTRIBUTE    MS-Identity-Type            41    integer
//! ATTRIBUTE    MS-Service-Class            42    string
//! ATTRIBUTE    MS-Quarantine-User-Class        44    string
//! ATTRIBUTE    MS-Quarantine-State            45    integer
//! ATTRIBUTE    MS-Quarantine-Grace-Time        46    integer
//! ATTRIBUTE    MS-Network-Access-Server-Type        47    integer
//! ATTRIBUTE    MS-AFW-Zone                48    integer
//!
//! VALUE    MS-AFW-Zone            MS-AFW-Zone-Boundary-Policy 1
//! VALUE    MS-AFW-Zone            MS-AFW-Zone-Unprotected-Policy 2
//! VALUE    MS-AFW-Zone            MS-AFW-Zone-Protected-Policy 3
//!
//! ATTRIBUTE    MS-AFW-Protection-Level            49    integer
//!
//! VALUE    MS-AFW-Protection-Level        HECP-Response-Sign-Only    1
//! VALUE    MS-AFW-Protection-Level        HECP-Response-Sign-And-Encrypt 2
//!
//! ATTRIBUTE    MS-Machine-Name                50    string
//! ATTRIBUTE    MS-IPv6-Filter                51    octets
//! ATTRIBUTE    MS-IPv4-Remediation-Servers        52    octets
//! ATTRIBUTE    MS-IPv6-Remediation-Servers        53    octets
//! ATTRIBUTE    MS-RNAP-Not-Quarantine-Capable        54    integer
//!
//! VALUE    MS-RNAP-Not-Quarantine-Capable    SoH-Sent        0
//! VALUE    MS-RNAP-Not-Quarantine-Capable    SoH-Not-Sent        1
//!
//! ATTRIBUTE    MS-Quarantine-SOH            55    octets
//! ATTRIBUTE    MS-RAS-Correlation            56    octets
//!
//! #  Or this might be 56?
//! ATTRIBUTE    MS-Extended-Quarantine-State        57    integer
//!
//! ATTRIBUTE    MS-HCAP-User-Groups            58    string
//! ATTRIBUTE    MS-HCAP-Location-Group-Name        59    string
//! ATTRIBUTE    MS-HCAP-User-Name            60    string
//! ATTRIBUTE    MS-User-IPv4-Address            61    ipaddr
//! ATTRIBUTE    MS-User-IPv6-Address            62    ipv6addr
//! ATTRIBUTE    MS-TSG-Device-Redirection        63    integer
//!
//! #
//! #    Integer Translations
//! #
//!
//! #    MS-BAP-Usage Values
//!
//! VALUE    MS-BAP-Usage            Not-Allowed        0
//! VALUE    MS-BAP-Usage            Allowed            1
//! VALUE    MS-BAP-Usage            Required        2
//!
//! #    MS-ARAP-Password-Change-Reason Values
//!
//! VALUE    MS-ARAP-PW-Change-Reason    Just-Change-Password    1
//! VALUE    MS-ARAP-PW-Change-Reason    Expired-Password    2
//! VALUE    MS-ARAP-PW-Change-Reason    Admin-Requires-Password-Change 3
//! VALUE    MS-ARAP-PW-Change-Reason    Password-Too-Short    4
//!
//! #    MS-Acct-Auth-Type Values
//!
//! VALUE    MS-Acct-Auth-Type        PAP            1
//! VALUE    MS-Acct-Auth-Type        CHAP            2
//! VALUE    MS-Acct-Auth-Type        MS-CHAP-1        3
//! VALUE    MS-Acct-Auth-Type        MS-CHAP-2        4
//! VALUE    MS-Acct-Auth-Type        EAP            5
//!
//! #    MS-Acct-EAP-Type Values
//!
//! VALUE    MS-Acct-EAP-Type        MD5            4
//! VALUE    MS-Acct-EAP-Type        OTP            5
//! VALUE    MS-Acct-EAP-Type        Generic-Token-Card    6
//! VALUE    MS-Acct-EAP-Type        TLS            13
//!
//! #  MS-Identity-Type Values
//!
//! VALUE    MS-Identity-Type        Machine-Health-Check    1
//! VALUE    MS-Identity-Type        Ignore-User-Lookup-Failure 2
//!
//! #  MS-Quarantine-State Values
//!
//! VALUE    MS-Quarantine-State        Full-Access        0
//! VALUE    MS-Quarantine-State        Quarantine        1
//! VALUE    MS-Quarantine-State        Probation        2
//!
//! #  MS-Network-Access-Server-Type Values
//!
//! VALUE    MS-Network-Access-Server-Type    Unspecified        0
//! VALUE    MS-Network-Access-Server-Type    Terminal-Server-Gateway    1
//! VALUE    MS-Network-Access-Server-Type    Remote-Access-Server    2
//! VALUE    MS-Network-Access-Server-Type    DHCP-Server        3
//! VALUE    MS-Network-Access-Server-Type    Wireless-Access-Point    4
//! VALUE    MS-Network-Access-Server-Type    HRA            5
//! VALUE    MS-Network-Access-Server-Type    HCAP-Server        6
//!
//! #  MS-Extended-Quarantine-State Values
//!
//! VALUE    MS-Extended-Quarantine-State    Transition        1
//! VALUE    MS-Extended-Quarantine-State    Infected        2
//! VALUE    MS-Extended-Quarantine-State    Unknown            3
//! VALUE    MS-Extended-Quarantine-State    No-Data            4
//!
//! END-VENDOR Microsoft
//! ```

use std::net::{Ipv4Addr, Ipv6Addr};

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;

pub const MS_CHAP_RESPONSE_TYPE: AVPType = 1;
/// Delete all of `ms_chap_response` values from a packet.
pub fn delete_ms_chap_response(packet: &mut Packet) {
    packet.delete(MS_CHAP_RESPONSE_TYPE);
}
/// Add `ms_chap_response` fixed-length octets value to a packet.
///
/// # Errors
///
/// Returns an `AVPError` if `value` is not exactly `50` bytes.
pub fn add_ms_chap_response(packet: &mut Packet, value: &[u8]) -> Result<(), AVPError> {
    if value.len() != 50 {
        return Err(AVPError::InvalidAttributeLengthError(
            "50 bytes".to_owned(),
            value.len(),
        ));
    }
    packet.add(AVP::from_bytes(MS_CHAP_RESPONSE_TYPE, value));
    Ok(())
}
/// Lookup a `ms_chap_response` fixed-length octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_response`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap_response(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP_RESPONSE_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap_response` fixed-length octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap_response(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_RESPONSE_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_CHAP_ERROR_TYPE: AVPType = 2;
/// Delete all of `ms_chap_error` values from a packet.
pub fn delete_ms_chap_error(packet: &mut Packet) {
    packet.delete(MS_CHAP_ERROR_TYPE);
}
/// Add `ms_chap_error` string value to a packet.
pub fn add_ms_chap_error(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_CHAP_ERROR_TYPE, value));
}
/// Lookup a `ms_chap_error` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_error`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_chap_error(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(MS_CHAP_ERROR_TYPE).map(AVP::encode_string)
}
/// Lookup all of the `ms_chap_error` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_chap_error(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_ERROR_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_CHAP_CPW_1_TYPE: AVPType = 3;
/// Delete all of `ms_chap_cpw_1` values from a packet.
pub fn delete_ms_chap_cpw_1(packet: &mut Packet) {
    packet.delete(MS_CHAP_CPW_1_TYPE);
}
/// Add `ms_chap_cpw_1` fixed-length octets value to a packet.
///
/// # Errors
///
/// Returns an `AVPError` if `value` is not exactly `70` bytes.
pub fn add_ms_chap_cpw_1(packet: &mut Packet, value: &[u8]) -> Result<(), AVPError> {
    if value.len() != 70 {
        return Err(AVPError::InvalidAttributeLengthError(
            "70 bytes".to_owned(),
            value.len(),
        ));
    }
    packet.add(AVP::from_bytes(MS_CHAP_CPW_1_TYPE, value));
    Ok(())
}
/// Lookup a `ms_chap_cpw_1` fixed-length octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_cpw_1`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap_cpw_1(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP_CPW_1_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap_cpw_1` fixed-length octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap_cpw_1(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_CPW_1_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_CHAP_CPW_2_TYPE: AVPType = 4;
/// Delete all of `ms_chap_cpw_2` values from a packet.
pub fn delete_ms_chap_cpw_2(packet: &mut Packet) {
    packet.delete(MS_CHAP_CPW_2_TYPE);
}
/// Add `ms_chap_cpw_2` fixed-length octets value to a packet.
///
/// # Errors
///
/// Returns an `AVPError` if `value` is not exactly `84` bytes.
pub fn add_ms_chap_cpw_2(packet: &mut Packet, value: &[u8]) -> Result<(), AVPError> {
    if value.len() != 84 {
        return Err(AVPError::InvalidAttributeLengthError(
            "84 bytes".to_owned(),
            value.len(),
        ));
    }
    packet.add(AVP::from_bytes(MS_CHAP_CPW_2_TYPE, value));
    Ok(())
}
/// Lookup a `ms_chap_cpw_2` fixed-length octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_cpw_2`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap_cpw_2(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP_CPW_2_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap_cpw_2` fixed-length octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap_cpw_2(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_CPW_2_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_CHAP_LM_ENC_PW_TYPE: AVPType = 5;
/// Delete all of `ms_chap_lm_enc_pw` values from a packet.
pub fn delete_ms_chap_lm_enc_pw(packet: &mut Packet) {
    packet.delete(MS_CHAP_LM_ENC_PW_TYPE);
}
/// Add `ms_chap_lm_enc_pw` octets value to a packet.
pub fn add_ms_chap_lm_enc_pw(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_CHAP_LM_ENC_PW_TYPE, value));
}
/// Lookup a `ms_chap_lm_enc_pw` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_lm_enc_pw`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap_lm_enc_pw(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP_LM_ENC_PW_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap_lm_enc_pw` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap_lm_enc_pw(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_LM_ENC_PW_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_CHAP_NT_ENC_PW_TYPE: AVPType = 6;
/// Delete all of `ms_chap_nt_enc_pw` values from a packet.
pub fn delete_ms_chap_nt_enc_pw(packet: &mut Packet) {
    packet.delete(MS_CHAP_NT_ENC_PW_TYPE);
}
/// Add `ms_chap_nt_enc_pw` octets value to a packet.
pub fn add_ms_chap_nt_enc_pw(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_CHAP_NT_ENC_PW_TYPE, value));
}
/// Lookup a `ms_chap_nt_enc_pw` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_nt_enc_pw`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap_nt_enc_pw(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP_NT_ENC_PW_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap_nt_enc_pw` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap_nt_enc_pw(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_NT_ENC_PW_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_MPPE_ENCRYPTION_POLICY_TYPE: AVPType = 7;
/// Delete all of `ms_mppe_encryption_policy` values from a packet.
pub fn delete_ms_mppe_encryption_policy(packet: &mut Packet) {
    packet.delete(MS_MPPE_ENCRYPTION_POLICY_TYPE);
}
/// Add `ms_mppe_encryption_policy` value-defined integer value to a packet.
pub fn add_ms_mppe_encryption_policy(packet: &mut Packet, value: MsMppeEncryptionPolicy) {
    packet.add(AVP::from_u32(MS_MPPE_ENCRYPTION_POLICY_TYPE, value));
}
/// Lookup a `ms_mppe_encryption_policy` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_mppe_encryption_policy`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_mppe_encryption_policy(
    packet: &Packet,
) -> Option<Result<MsMppeEncryptionPolicy, AVPError>> {
    packet
        .lookup(MS_MPPE_ENCRYPTION_POLICY_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsMppeEncryptionPolicy))
}
/// Lookup all of the `ms_mppe_encryption_policy` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_mppe_encryption_policy(
    packet: &Packet,
) -> Result<Vec<MsMppeEncryptionPolicy>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_MPPE_ENCRYPTION_POLICY_TYPE) {
        vec.push(avp.encode_u32()? as MsMppeEncryptionPolicy);
    }
    Ok(vec)
}

pub const MS_MPPE_ENCRYPTION_TYPE_TYPE: AVPType = 8;
/// Delete all of `ms_mppe_encryption_type` values from a packet.
pub fn delete_ms_mppe_encryption_type(packet: &mut Packet) {
    packet.delete(MS_MPPE_ENCRYPTION_TYPE_TYPE);
}
/// Add `ms_mppe_encryption_type` integer value to a packet.
pub fn add_ms_mppe_encryption_type(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MS_MPPE_ENCRYPTION_TYPE_TYPE, value));
}
/// Lookup a `ms_mppe_encryption_type` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_mppe_encryption_type`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_mppe_encryption_type(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MS_MPPE_ENCRYPTION_TYPE_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `ms_mppe_encryption_type` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_mppe_encryption_type(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_MPPE_ENCRYPTION_TYPE_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const MS_RAS_VENDOR_TYPE: AVPType = 9;
/// Delete all of `ms_ras_vendor` values from a packet.
pub fn delete_ms_ras_vendor(packet: &mut Packet) {
    packet.delete(MS_RAS_VENDOR_TYPE);
}
/// Add `ms_ras_vendor` integer value to a packet.
pub fn add_ms_ras_vendor(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MS_RAS_VENDOR_TYPE, value));
}
/// Lookup a `ms_ras_vendor` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_ras_vendor`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_ras_vendor(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet.lookup(MS_RAS_VENDOR_TYPE).map(AVP::encode_u32)
}
/// Lookup all of the `ms_ras_vendor` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_ras_vendor(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_RAS_VENDOR_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const MS_CHAP_DOMAIN_TYPE: AVPType = 10;
/// Delete all of `ms_chap_domain` values from a packet.
pub fn delete_ms_chap_domain(packet: &mut Packet) {
    packet.delete(MS_CHAP_DOMAIN_TYPE);
}
/// Add `ms_chap_domain` string value to a packet.
pub fn add_ms_chap_domain(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_CHAP_DOMAIN_TYPE, value));
}
/// Lookup a `ms_chap_domain` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_domain`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_chap_domain(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(MS_CHAP_DOMAIN_TYPE).map(AVP::encode_string)
}
/// Lookup all of the `ms_chap_domain` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_chap_domain(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_DOMAIN_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_CHAP_CHALLENGE_TYPE: AVPType = 11;
/// Delete all of `ms_chap_challenge` values from a packet.
pub fn delete_ms_chap_challenge(packet: &mut Packet) {
    packet.delete(MS_CHAP_CHALLENGE_TYPE);
}
/// Add `ms_chap_challenge` octets value to a packet.
pub fn add_ms_chap_challenge(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_CHAP_CHALLENGE_TYPE, value));
}
/// Lookup a `ms_chap_challenge` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_challenge`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap_challenge(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP_CHALLENGE_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap_challenge` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap_challenge(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_CHALLENGE_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_CHAP_MPPE_KEYS_TYPE: AVPType = 12;
/// Delete all of `ms_chap_mppe_keys` values from a packet.
pub fn delete_ms_chap_mppe_keys(packet: &mut Packet) {
    packet.delete(MS_CHAP_MPPE_KEYS_TYPE);
}
/// Add `ms_chap_mppe_keys` fixed-length octets value to a packet.
///
/// # Errors
///
/// Returns an `AVPError` if `value` is not exactly `24` bytes.
pub fn add_ms_chap_mppe_keys(packet: &mut Packet, value: &[u8]) -> Result<(), AVPError> {
    if value.len() != 24 {
        return Err(AVPError::InvalidAttributeLengthError(
            "24 bytes".to_owned(),
            value.len(),
        ));
    }
    packet.add(AVP::from_bytes(MS_CHAP_MPPE_KEYS_TYPE, value));
    Ok(())
}
/// Lookup a `ms_chap_mppe_keys` fixed-length octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap_mppe_keys`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap_mppe_keys(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP_MPPE_KEYS_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap_mppe_keys` fixed-length octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap_mppe_keys(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP_MPPE_KEYS_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_BAP_USAGE_TYPE: AVPType = 13;
/// Delete all of `ms_bap_usage` values from a packet.
pub fn delete_ms_bap_usage(packet: &mut Packet) {
    packet.delete(MS_BAP_USAGE_TYPE);
}
/// Add `ms_bap_usage` value-defined integer value to a packet.
pub fn add_ms_bap_usage(packet: &mut Packet, value: MsBapUsage) {
    packet.add(AVP::from_u32(MS_BAP_USAGE_TYPE, value));
}
/// Lookup a `ms_bap_usage` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_bap_usage`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_bap_usage(packet: &Packet) -> Option<Result<MsBapUsage, AVPError>> {
    packet
        .lookup(MS_BAP_USAGE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsBapUsage))
}
/// Lookup all of the `ms_bap_usage` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_bap_usage(packet: &Packet) -> Result<Vec<MsBapUsage>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_BAP_USAGE_TYPE) {
        vec.push(avp.encode_u32()? as MsBapUsage);
    }
    Ok(vec)
}

pub const MS_LINK_UTILIZATION_THRESHOLD_TYPE: AVPType = 14;
/// Delete all of `ms_link_utilization_threshold` values from a packet.
pub fn delete_ms_link_utilization_threshold(packet: &mut Packet) {
    packet.delete(MS_LINK_UTILIZATION_THRESHOLD_TYPE);
}
/// Add `ms_link_utilization_threshold` integer value to a packet.
pub fn add_ms_link_utilization_threshold(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MS_LINK_UTILIZATION_THRESHOLD_TYPE, value));
}
/// Lookup a `ms_link_utilization_threshold` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_link_utilization_threshold`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_link_utilization_threshold(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MS_LINK_UTILIZATION_THRESHOLD_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `ms_link_utilization_threshold` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_link_utilization_threshold(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_LINK_UTILIZATION_THRESHOLD_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const MS_LINK_DROP_TIME_LIMIT_TYPE: AVPType = 15;
/// Delete all of `ms_link_drop_time_limit` values from a packet.
pub fn delete_ms_link_drop_time_limit(packet: &mut Packet) {
    packet.delete(MS_LINK_DROP_TIME_LIMIT_TYPE);
}
/// Add `ms_link_drop_time_limit` integer value to a packet.
pub fn add_ms_link_drop_time_limit(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MS_LINK_DROP_TIME_LIMIT_TYPE, value));
}
/// Lookup a `ms_link_drop_time_limit` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_link_drop_time_limit`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_link_drop_time_limit(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MS_LINK_DROP_TIME_LIMIT_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `ms_link_drop_time_limit` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_link_drop_time_limit(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_LINK_DROP_TIME_LIMIT_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const MS_MPPE_SEND_KEY_TYPE: AVPType = 16;
/// Delete all of `ms_mppe_send_key` values from a packet.
pub fn delete_ms_mppe_send_key(packet: &mut Packet) {
    packet.delete(MS_MPPE_SEND_KEY_TYPE);
}
/// Add `ms_mppe_send_key` octets value to a packet.
pub fn add_ms_mppe_send_key(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_MPPE_SEND_KEY_TYPE, value));
}
/// Lookup a `ms_mppe_send_key` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_mppe_send_key`, it returns `None`.
#[must_use]
pub fn lookup_ms_mppe_send_key(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_MPPE_SEND_KEY_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_mppe_send_key` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_mppe_send_key(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_MPPE_SEND_KEY_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_MPPE_RECV_KEY_TYPE: AVPType = 17;
/// Delete all of `ms_mppe_recv_key` values from a packet.
pub fn delete_ms_mppe_recv_key(packet: &mut Packet) {
    packet.delete(MS_MPPE_RECV_KEY_TYPE);
}
/// Add `ms_mppe_recv_key` octets value to a packet.
pub fn add_ms_mppe_recv_key(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_MPPE_RECV_KEY_TYPE, value));
}
/// Lookup a `ms_mppe_recv_key` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_mppe_recv_key`, it returns `None`.
#[must_use]
pub fn lookup_ms_mppe_recv_key(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_MPPE_RECV_KEY_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_mppe_recv_key` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_mppe_recv_key(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_MPPE_RECV_KEY_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_RAS_VERSION_TYPE: AVPType = 18;
/// Delete all of `ms_ras_version` values from a packet.
pub fn delete_ms_ras_version(packet: &mut Packet) {
    packet.delete(MS_RAS_VERSION_TYPE);
}
/// Add `ms_ras_version` string value to a packet.
pub fn add_ms_ras_version(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_RAS_VERSION_TYPE, value));
}
/// Lookup a `ms_ras_version` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_ras_version`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_ras_version(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(MS_RAS_VERSION_TYPE).map(AVP::encode_string)
}
/// Lookup all of the `ms_ras_version` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_ras_version(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_RAS_VERSION_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_OLD_ARAP_PASSWORD_TYPE: AVPType = 19;
/// Delete all of `ms_old_arap_password` values from a packet.
pub fn delete_ms_old_arap_password(packet: &mut Packet) {
    packet.delete(MS_OLD_ARAP_PASSWORD_TYPE);
}
/// Add `ms_old_arap_password` octets value to a packet.
pub fn add_ms_old_arap_password(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_OLD_ARAP_PASSWORD_TYPE, value));
}
/// Lookup a `ms_old_arap_password` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_old_arap_password`, it returns `None`.
#[must_use]
pub fn lookup_ms_old_arap_password(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(MS_OLD_ARAP_PASSWORD_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `ms_old_arap_password` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_old_arap_password(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_OLD_ARAP_PASSWORD_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_NEW_ARAP_PASSWORD_TYPE: AVPType = 20;
/// Delete all of `ms_new_arap_password` values from a packet.
pub fn delete_ms_new_arap_password(packet: &mut Packet) {
    packet.delete(MS_NEW_ARAP_PASSWORD_TYPE);
}
/// Add `ms_new_arap_password` octets value to a packet.
pub fn add_ms_new_arap_password(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_NEW_ARAP_PASSWORD_TYPE, value));
}
/// Lookup a `ms_new_arap_password` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_new_arap_password`, it returns `None`.
#[must_use]
pub fn lookup_ms_new_arap_password(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(MS_NEW_ARAP_PASSWORD_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `ms_new_arap_password` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_new_arap_password(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_NEW_ARAP_PASSWORD_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_ARAP_PW_CHANGE_REASON_TYPE: AVPType = 21;
/// Delete all of `ms_arap_pw_change_reason` values from a packet.
pub fn delete_ms_arap_pw_change_reason(packet: &mut Packet) {
    packet.delete(MS_ARAP_PW_CHANGE_REASON_TYPE);
}
/// Add `ms_arap_pw_change_reason` value-defined integer value to a packet.
pub fn add_ms_arap_pw_change_reason(packet: &mut Packet, value: MsArapPwChangeReason) {
    packet.add(AVP::from_u32(MS_ARAP_PW_CHANGE_REASON_TYPE, value));
}
/// Lookup a `ms_arap_pw_change_reason` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_arap_pw_change_reason`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_arap_pw_change_reason(
    packet: &Packet,
) -> Option<Result<MsArapPwChangeReason, AVPError>> {
    packet
        .lookup(MS_ARAP_PW_CHANGE_REASON_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsArapPwChangeReason))
}
/// Lookup all of the `ms_arap_pw_change_reason` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_arap_pw_change_reason(
    packet: &Packet,
) -> Result<Vec<MsArapPwChangeReason>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_ARAP_PW_CHANGE_REASON_TYPE) {
        vec.push(avp.encode_u32()? as MsArapPwChangeReason);
    }
    Ok(vec)
}

pub const MS_FILTER_TYPE: AVPType = 22;
/// Delete all of `ms_filter` values from a packet.
pub fn delete_ms_filter(packet: &mut Packet) {
    packet.delete(MS_FILTER_TYPE);
}
/// Add `ms_filter` octets value to a packet.
pub fn add_ms_filter(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_FILTER_TYPE, value));
}
/// Lookup a `ms_filter` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_filter`, it returns `None`.
#[must_use]
pub fn lookup_ms_filter(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_FILTER_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_filter` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_filter(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_FILTER_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_ACCT_AUTH_TYPE_TYPE: AVPType = 23;
/// Delete all of `ms_acct_auth_type` values from a packet.
pub fn delete_ms_acct_auth_type(packet: &mut Packet) {
    packet.delete(MS_ACCT_AUTH_TYPE_TYPE);
}
/// Add `ms_acct_auth_type` value-defined integer value to a packet.
pub fn add_ms_acct_auth_type(packet: &mut Packet, value: MsAcctAuthType) {
    packet.add(AVP::from_u32(MS_ACCT_AUTH_TYPE_TYPE, value));
}
/// Lookup a `ms_acct_auth_type` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_acct_auth_type`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_acct_auth_type(packet: &Packet) -> Option<Result<MsAcctAuthType, AVPError>> {
    packet
        .lookup(MS_ACCT_AUTH_TYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsAcctAuthType))
}
/// Lookup all of the `ms_acct_auth_type` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_acct_auth_type(packet: &Packet) -> Result<Vec<MsAcctAuthType>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_ACCT_AUTH_TYPE_TYPE) {
        vec.push(avp.encode_u32()? as MsAcctAuthType);
    }
    Ok(vec)
}

pub const MS_ACCT_EAP_TYPE_TYPE: AVPType = 24;
/// Delete all of `ms_acct_eap_type` values from a packet.
pub fn delete_ms_acct_eap_type(packet: &mut Packet) {
    packet.delete(MS_ACCT_EAP_TYPE_TYPE);
}
/// Add `ms_acct_eap_type` value-defined integer value to a packet.
pub fn add_ms_acct_eap_type(packet: &mut Packet, value: MsAcctEAPType) {
    packet.add(AVP::from_u32(MS_ACCT_EAP_TYPE_TYPE, value));
}
/// Lookup a `ms_acct_eap_type` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_acct_eap_type`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_acct_eap_type(packet: &Packet) -> Option<Result<MsAcctEAPType, AVPError>> {
    packet
        .lookup(MS_ACCT_EAP_TYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsAcctEAPType))
}
/// Lookup all of the `ms_acct_eap_type` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_acct_eap_type(packet: &Packet) -> Result<Vec<MsAcctEAPType>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_ACCT_EAP_TYPE_TYPE) {
        vec.push(avp.encode_u32()? as MsAcctEAPType);
    }
    Ok(vec)
}

pub const MS_CHAP2_RESPONSE_TYPE: AVPType = 25;
/// Delete all of `ms_chap2_response` values from a packet.
pub fn delete_ms_chap2_response(packet: &mut Packet) {
    packet.delete(MS_CHAP2_RESPONSE_TYPE);
}
/// Add `ms_chap2_response` fixed-length octets value to a packet.
///
/// # Errors
///
/// Returns an `AVPError` if `value` is not exactly `50` bytes.
pub fn add_ms_chap2_response(packet: &mut Packet, value: &[u8]) -> Result<(), AVPError> {
    if value.len() != 50 {
        return Err(AVPError::InvalidAttributeLengthError(
            "50 bytes".to_owned(),
            value.len(),
        ));
    }
    packet.add(AVP::from_bytes(MS_CHAP2_RESPONSE_TYPE, value));
    Ok(())
}
/// Lookup a `ms_chap2_response` fixed-length octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap2_response`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap2_response(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP2_RESPONSE_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap2_response` fixed-length octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap2_response(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP2_RESPONSE_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_CHAP2_SUCCESS_TYPE: AVPType = 26;
/// Delete all of `ms_chap2_success` values from a packet.
pub fn delete_ms_chap2_success(packet: &mut Packet) {
    packet.delete(MS_CHAP2_SUCCESS_TYPE);
}
/// Add `ms_chap2_success` octets value to a packet.
pub fn add_ms_chap2_success(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_CHAP2_SUCCESS_TYPE, value));
}
/// Lookup a `ms_chap2_success` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap2_success`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap2_success(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP2_SUCCESS_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap2_success` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap2_success(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP2_SUCCESS_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_CHAP2_CPW_TYPE: AVPType = 27;
/// Delete all of `ms_chap2_cpw` values from a packet.
pub fn delete_ms_chap2_cpw(packet: &mut Packet) {
    packet.delete(MS_CHAP2_CPW_TYPE);
}
/// Add `ms_chap2_cpw` fixed-length octets value to a packet.
///
/// # Errors
///
/// Returns an `AVPError` if `value` is not exactly `68` bytes.
pub fn add_ms_chap2_cpw(packet: &mut Packet, value: &[u8]) -> Result<(), AVPError> {
    if value.len() != 68 {
        return Err(AVPError::InvalidAttributeLengthError(
            "68 bytes".to_owned(),
            value.len(),
        ));
    }
    packet.add(AVP::from_bytes(MS_CHAP2_CPW_TYPE, value));
    Ok(())
}
/// Lookup a `ms_chap2_cpw` fixed-length octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_chap2_cpw`, it returns `None`.
#[must_use]
pub fn lookup_ms_chap2_cpw(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_CHAP2_CPW_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_chap2_cpw` fixed-length octets value from a packet.
#[must_use]
pub fn lookup_all_ms_chap2_cpw(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_CHAP2_CPW_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_PRIMARY_DNS_SERVER_TYPE: AVPType = 28;
/// Delete all of `ms_primary_dns_server` values from a packet.
pub fn delete_ms_primary_dns_server(packet: &mut Packet) {
    packet.delete(MS_PRIMARY_DNS_SERVER_TYPE);
}
/// Add `ms_primary_dns_server` ipaddr value to a packet.
pub fn add_ms_primary_dns_server(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(MS_PRIMARY_DNS_SERVER_TYPE, value));
}
/// Lookup a `ms_primary_dns_server` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_primary_dns_server`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_primary_dns_server(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(MS_PRIMARY_DNS_SERVER_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `ms_primary_dns_server` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_primary_dns_server(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_PRIMARY_DNS_SERVER_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const MS_SECONDARY_DNS_SERVER_TYPE: AVPType = 29;
/// Delete all of `ms_secondary_dns_server` values from a packet.
pub fn delete_ms_secondary_dns_server(packet: &mut Packet) {
    packet.delete(MS_SECONDARY_DNS_SERVER_TYPE);
}
/// Add `ms_secondary_dns_server` ipaddr value to a packet.
pub fn add_ms_secondary_dns_server(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(MS_SECONDARY_DNS_SERVER_TYPE, value));
}
/// Lookup a `ms_secondary_dns_server` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_secondary_dns_server`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_secondary_dns_server(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(MS_SECONDARY_DNS_SERVER_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `ms_secondary_dns_server` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_secondary_dns_server(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_SECONDARY_DNS_SERVER_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const MS_PRIMARY_NBNS_SERVER_TYPE: AVPType = 30;
/// Delete all of `ms_primary_nbns_server` values from a packet.
pub fn delete_ms_primary_nbns_server(packet: &mut Packet) {
    packet.delete(MS_PRIMARY_NBNS_SERVER_TYPE);
}
/// Add `ms_primary_nbns_server` ipaddr value to a packet.
pub fn add_ms_primary_nbns_server(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(MS_PRIMARY_NBNS_SERVER_TYPE, value));
}
/// Lookup a `ms_primary_nbns_server` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_primary_nbns_server`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_primary_nbns_server(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(MS_PRIMARY_NBNS_SERVER_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `ms_primary_nbns_server` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_primary_nbns_server(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_PRIMARY_NBNS_SERVER_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const MS_SECONDARY_NBNS_SERVER_TYPE: AVPType = 31;
/// Delete all of `ms_secondary_nbns_server` values from a packet.
pub fn delete_ms_secondary_nbns_server(packet: &mut Packet) {
    packet.delete(MS_SECONDARY_NBNS_SERVER_TYPE);
}
/// Add `ms_secondary_nbns_server` ipaddr value to a packet.
pub fn add_ms_secondary_nbns_server(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(MS_SECONDARY_NBNS_SERVER_TYPE, value));
}
/// Lookup a `ms_secondary_nbns_server` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_secondary_nbns_server`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_secondary_nbns_server(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(MS_SECONDARY_NBNS_SERVER_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `ms_secondary_nbns_server` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_secondary_nbns_server(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_SECONDARY_NBNS_SERVER_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const MS_RAS_CLIENT_NAME_TYPE: AVPType = 34;
/// Delete all of `ms_ras_client_name` values from a packet.
pub fn delete_ms_ras_client_name(packet: &mut Packet) {
    packet.delete(MS_RAS_CLIENT_NAME_TYPE);
}
/// Add `ms_ras_client_name` string value to a packet.
pub fn add_ms_ras_client_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_RAS_CLIENT_NAME_TYPE, value));
}
/// Lookup a `ms_ras_client_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_ras_client_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_ras_client_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MS_RAS_CLIENT_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `ms_ras_client_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_ras_client_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_RAS_CLIENT_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_RAS_CLIENT_VERSION_TYPE: AVPType = 35;
/// Delete all of `ms_ras_client_version` values from a packet.
pub fn delete_ms_ras_client_version(packet: &mut Packet) {
    packet.delete(MS_RAS_CLIENT_VERSION_TYPE);
}
/// Add `ms_ras_client_version` string value to a packet.
pub fn add_ms_ras_client_version(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_RAS_CLIENT_VERSION_TYPE, value));
}
/// Lookup a `ms_ras_client_version` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_ras_client_version`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_ras_client_version(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MS_RAS_CLIENT_VERSION_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `ms_ras_client_version` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_ras_client_version(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_RAS_CLIENT_VERSION_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_QUARANTINE_IP_FILTER_TYPE: AVPType = 36;
/// Delete all of `ms_quarantine_ip_filter` values from a packet.
pub fn delete_ms_quarantine_ip_filter(packet: &mut Packet) {
    packet.delete(MS_QUARANTINE_IP_FILTER_TYPE);
}
/// Add `ms_quarantine_ip_filter` octets value to a packet.
pub fn add_ms_quarantine_ip_filter(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_QUARANTINE_IP_FILTER_TYPE, value));
}
/// Lookup a `ms_quarantine_ip_filter` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_quarantine_ip_filter`, it returns `None`.
#[must_use]
pub fn lookup_ms_quarantine_ip_filter(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(MS_QUARANTINE_IP_FILTER_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `ms_quarantine_ip_filter` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_quarantine_ip_filter(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_QUARANTINE_IP_FILTER_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_QUARANTINE_SESSION_TIMEOUT_TYPE: AVPType = 37;
/// Delete all of `ms_quarantine_session_timeout` values from a packet.
pub fn delete_ms_quarantine_session_timeout(packet: &mut Packet) {
    packet.delete(MS_QUARANTINE_SESSION_TIMEOUT_TYPE);
}
/// Add `ms_quarantine_session_timeout` integer value to a packet.
pub fn add_ms_quarantine_session_timeout(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MS_QUARANTINE_SESSION_TIMEOUT_TYPE, value));
}
/// Lookup a `ms_quarantine_session_timeout` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_quarantine_session_timeout`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_quarantine_session_timeout(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MS_QUARANTINE_SESSION_TIMEOUT_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `ms_quarantine_session_timeout` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_quarantine_session_timeout(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_QUARANTINE_SESSION_TIMEOUT_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const MS_USER_SECURITY_IDENTITY_TYPE: AVPType = 40;
/// Delete all of `ms_user_security_identity` values from a packet.
pub fn delete_ms_user_security_identity(packet: &mut Packet) {
    packet.delete(MS_USER_SECURITY_IDENTITY_TYPE);
}
/// Add `ms_user_security_identity` string value to a packet.
pub fn add_ms_user_security_identity(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_USER_SECURITY_IDENTITY_TYPE, value));
}
/// Lookup a `ms_user_security_identity` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_user_security_identity`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_user_security_identity(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MS_USER_SECURITY_IDENTITY_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `ms_user_security_identity` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_user_security_identity(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_USER_SECURITY_IDENTITY_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_IDENTITY_TYPE_TYPE: AVPType = 41;
/// Delete all of `ms_identity_type` values from a packet.
pub fn delete_ms_identity_type(packet: &mut Packet) {
    packet.delete(MS_IDENTITY_TYPE_TYPE);
}
/// Add `ms_identity_type` value-defined integer value to a packet.
pub fn add_ms_identity_type(packet: &mut Packet, value: MsIdentityType) {
    packet.add(AVP::from_u32(MS_IDENTITY_TYPE_TYPE, value));
}
/// Lookup a `ms_identity_type` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_identity_type`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_identity_type(packet: &Packet) -> Option<Result<MsIdentityType, AVPError>> {
    packet
        .lookup(MS_IDENTITY_TYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsIdentityType))
}
/// Lookup all of the `ms_identity_type` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_identity_type(packet: &Packet) -> Result<Vec<MsIdentityType>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_IDENTITY_TYPE_TYPE) {
        vec.push(avp.encode_u32()? as MsIdentityType);
    }
    Ok(vec)
}

pub const MS_SERVICE_CLASS_TYPE: AVPType = 42;
/// Delete all of `ms_service_class` values from a packet.
pub fn delete_ms_service_class(packet: &mut Packet) {
    packet.delete(MS_SERVICE_CLASS_TYPE);
}
/// Add `ms_service_class` string value to a packet.
pub fn add_ms_service_class(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_SERVICE_CLASS_TYPE, value));
}
/// Lookup a `ms_service_class` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_service_class`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_service_class(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(MS_SERVICE_CLASS_TYPE).map(AVP::encode_string)
}
/// Lookup all of the `ms_service_class` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_service_class(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_SERVICE_CLASS_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_QUARANTINE_USER_CLASS_TYPE: AVPType = 44;
/// Delete all of `ms_quarantine_user_class` values from a packet.
pub fn delete_ms_quarantine_user_class(packet: &mut Packet) {
    packet.delete(MS_QUARANTINE_USER_CLASS_TYPE);
}
/// Add `ms_quarantine_user_class` string value to a packet.
pub fn add_ms_quarantine_user_class(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_QUARANTINE_USER_CLASS_TYPE, value));
}
/// Lookup a `ms_quarantine_user_class` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_quarantine_user_class`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_quarantine_user_class(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MS_QUARANTINE_USER_CLASS_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `ms_quarantine_user_class` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_quarantine_user_class(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_QUARANTINE_USER_CLASS_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_QUARANTINE_STATE_TYPE: AVPType = 45;
/// Delete all of `ms_quarantine_state` values from a packet.
pub fn delete_ms_quarantine_state(packet: &mut Packet) {
    packet.delete(MS_QUARANTINE_STATE_TYPE);
}
/// Add `ms_quarantine_state` value-defined integer value to a packet.
pub fn add_ms_quarantine_state(packet: &mut Packet, value: MsQuarantineState) {
    packet.add(AVP::from_u32(MS_QUARANTINE_STATE_TYPE, value));
}
/// Lookup a `ms_quarantine_state` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_quarantine_state`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_quarantine_state(packet: &Packet) -> Option<Result<MsQuarantineState, AVPError>> {
    packet
        .lookup(MS_QUARANTINE_STATE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsQuarantineState))
}
/// Lookup all of the `ms_quarantine_state` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_quarantine_state(packet: &Packet) -> Result<Vec<MsQuarantineState>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_QUARANTINE_STATE_TYPE) {
        vec.push(avp.encode_u32()? as MsQuarantineState);
    }
    Ok(vec)
}

pub const MS_QUARANTINE_GRACE_TIME_TYPE: AVPType = 46;
/// Delete all of `ms_quarantine_grace_time` values from a packet.
pub fn delete_ms_quarantine_grace_time(packet: &mut Packet) {
    packet.delete(MS_QUARANTINE_GRACE_TIME_TYPE);
}
/// Add `ms_quarantine_grace_time` integer value to a packet.
pub fn add_ms_quarantine_grace_time(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MS_QUARANTINE_GRACE_TIME_TYPE, value));
}
/// Lookup a `ms_quarantine_grace_time` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_quarantine_grace_time`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_quarantine_grace_time(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MS_QUARANTINE_GRACE_TIME_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `ms_quarantine_grace_time` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_quarantine_grace_time(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_QUARANTINE_GRACE_TIME_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const MS_NETWORK_ACCESS_SERVER_TYPE_TYPE: AVPType = 47;
/// Delete all of `ms_network_access_server_type` values from a packet.
pub fn delete_ms_network_access_server_type(packet: &mut Packet) {
    packet.delete(MS_NETWORK_ACCESS_SERVER_TYPE_TYPE);
}
/// Add `ms_network_access_server_type` value-defined integer value to a packet.
pub fn add_ms_network_access_server_type(packet: &mut Packet, value: MsNetworkAccessServerType) {
    packet.add(AVP::from_u32(MS_NETWORK_ACCESS_SERVER_TYPE_TYPE, value));
}
/// Lookup a `ms_network_access_server_type` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_network_access_server_type`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_network_access_server_type(
    packet: &Packet,
) -> Option<Result<MsNetworkAccessServerType, AVPError>> {
    packet
        .lookup(MS_NETWORK_ACCESS_SERVER_TYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsNetworkAccessServerType))
}
/// Lookup all of the `ms_network_access_server_type` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_network_access_server_type(
    packet: &Packet,
) -> Result<Vec<MsNetworkAccessServerType>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_NETWORK_ACCESS_SERVER_TYPE_TYPE) {
        vec.push(avp.encode_u32()? as MsNetworkAccessServerType);
    }
    Ok(vec)
}

pub const MS_AFW_ZONE_TYPE: AVPType = 48;
/// Delete all of `ms_afw_zone` values from a packet.
pub fn delete_ms_afw_zone(packet: &mut Packet) {
    packet.delete(MS_AFW_ZONE_TYPE);
}
/// Add `ms_afw_zone` value-defined integer value to a packet.
pub fn add_ms_afw_zone(packet: &mut Packet, value: MsAfwZone) {
    packet.add(AVP::from_u32(MS_AFW_ZONE_TYPE, value));
}
/// Lookup a `ms_afw_zone` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_afw_zone`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_afw_zone(packet: &Packet) -> Option<Result<MsAfwZone, AVPError>> {
    packet
        .lookup(MS_AFW_ZONE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsAfwZone))
}
/// Lookup all of the `ms_afw_zone` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_afw_zone(packet: &Packet) -> Result<Vec<MsAfwZone>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_AFW_ZONE_TYPE) {
        vec.push(avp.encode_u32()? as MsAfwZone);
    }
    Ok(vec)
}

pub const MS_AFW_PROTECTION_LEVEL_TYPE: AVPType = 49;
/// Delete all of `ms_afw_protection_level` values from a packet.
pub fn delete_ms_afw_protection_level(packet: &mut Packet) {
    packet.delete(MS_AFW_PROTECTION_LEVEL_TYPE);
}
/// Add `ms_afw_protection_level` value-defined integer value to a packet.
pub fn add_ms_afw_protection_level(packet: &mut Packet, value: MsAfwProtectionLevel) {
    packet.add(AVP::from_u32(MS_AFW_PROTECTION_LEVEL_TYPE, value));
}
/// Lookup a `ms_afw_protection_level` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_afw_protection_level`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_afw_protection_level(
    packet: &Packet,
) -> Option<Result<MsAfwProtectionLevel, AVPError>> {
    packet
        .lookup(MS_AFW_PROTECTION_LEVEL_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsAfwProtectionLevel))
}
/// Lookup all of the `ms_afw_protection_level` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_afw_protection_level(
    packet: &Packet,
) -> Result<Vec<MsAfwProtectionLevel>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_AFW_PROTECTION_LEVEL_TYPE) {
        vec.push(avp.encode_u32()? as MsAfwProtectionLevel);
    }
    Ok(vec)
}

pub const MS_MACHINE_NAME_TYPE: AVPType = 50;
/// Delete all of `ms_machine_name` values from a packet.
pub fn delete_ms_machine_name(packet: &mut Packet) {
    packet.delete(MS_MACHINE_NAME_TYPE);
}
/// Add `ms_machine_name` string value to a packet.
pub fn add_ms_machine_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_MACHINE_NAME_TYPE, value));
}
/// Lookup a `ms_machine_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_machine_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_machine_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(MS_MACHINE_NAME_TYPE).map(AVP::encode_string)
}
/// Lookup all of the `ms_machine_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_machine_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_MACHINE_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_I_PV_6_FILTER_TYPE: AVPType = 51;
/// Delete all of `ms_i_pv_6_filter` values from a packet.
pub fn delete_ms_i_pv_6_filter(packet: &mut Packet) {
    packet.delete(MS_I_PV_6_FILTER_TYPE);
}
/// Add `ms_i_pv_6_filter` octets value to a packet.
pub fn add_ms_i_pv_6_filter(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_I_PV_6_FILTER_TYPE, value));
}
/// Lookup a `ms_i_pv_6_filter` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_i_pv_6_filter`, it returns `None`.
#[must_use]
pub fn lookup_ms_i_pv_6_filter(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_I_PV_6_FILTER_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_i_pv_6_filter` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_i_pv_6_filter(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_I_PV_6_FILTER_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_I_PV_4_REMEDIATION_SERVERS_TYPE: AVPType = 52;
/// Delete all of `ms_i_pv_4_remediation_servers` values from a packet.
pub fn delete_ms_i_pv_4_remediation_servers(packet: &mut Packet) {
    packet.delete(MS_I_PV_4_REMEDIATION_SERVERS_TYPE);
}
/// Add `ms_i_pv_4_remediation_servers` octets value to a packet.
pub fn add_ms_i_pv_4_remediation_servers(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_I_PV_4_REMEDIATION_SERVERS_TYPE, value));
}
/// Lookup a `ms_i_pv_4_remediation_servers` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_i_pv_4_remediation_servers`, it returns `None`.
#[must_use]
pub fn lookup_ms_i_pv_4_remediation_servers(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(MS_I_PV_4_REMEDIATION_SERVERS_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `ms_i_pv_4_remediation_servers` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_i_pv_4_remediation_servers(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_I_PV_4_REMEDIATION_SERVERS_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_I_PV_6_REMEDIATION_SERVERS_TYPE: AVPType = 53;
/// Delete all of `ms_i_pv_6_remediation_servers` values from a packet.
pub fn delete_ms_i_pv_6_remediation_servers(packet: &mut Packet) {
    packet.delete(MS_I_PV_6_REMEDIATION_SERVERS_TYPE);
}
/// Add `ms_i_pv_6_remediation_servers` octets value to a packet.
pub fn add_ms_i_pv_6_remediation_servers(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_I_PV_6_REMEDIATION_SERVERS_TYPE, value));
}
/// Lookup a `ms_i_pv_6_remediation_servers` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_i_pv_6_remediation_servers`, it returns `None`.
#[must_use]
pub fn lookup_ms_i_pv_6_remediation_servers(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(MS_I_PV_6_REMEDIATION_SERVERS_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `ms_i_pv_6_remediation_servers` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_i_pv_6_remediation_servers(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_I_PV_6_REMEDIATION_SERVERS_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_RNAP_NOT_QUARANTINE_CAPABLE_TYPE: AVPType = 54;
/// Delete all of `ms_rnap_not_quarantine_capable` values from a packet.
pub fn delete_ms_rnap_not_quarantine_capable(packet: &mut Packet) {
    packet.delete(MS_RNAP_NOT_QUARANTINE_CAPABLE_TYPE);
}
/// Add `ms_rnap_not_quarantine_capable` value-defined integer value to a packet.
pub fn add_ms_rnap_not_quarantine_capable(packet: &mut Packet, value: MsRnapNotQuarantineCapable) {
    packet.add(AVP::from_u32(MS_RNAP_NOT_QUARANTINE_CAPABLE_TYPE, value));
}
/// Lookup a `ms_rnap_not_quarantine_capable` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_rnap_not_quarantine_capable`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_rnap_not_quarantine_capable(
    packet: &Packet,
) -> Option<Result<MsRnapNotQuarantineCapable, AVPError>> {
    packet
        .lookup(MS_RNAP_NOT_QUARANTINE_CAPABLE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsRnapNotQuarantineCapable))
}
/// Lookup all of the `ms_rnap_not_quarantine_capable` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_rnap_not_quarantine_capable(
    packet: &Packet,
) -> Result<Vec<MsRnapNotQuarantineCapable>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_RNAP_NOT_QUARANTINE_CAPABLE_TYPE) {
        vec.push(avp.encode_u32()? as MsRnapNotQuarantineCapable);
    }
    Ok(vec)
}

pub const MS_QUARANTINE_SOH_TYPE: AVPType = 55;
/// Delete all of `ms_quarantine_soh` values from a packet.
pub fn delete_ms_quarantine_soh(packet: &mut Packet) {
    packet.delete(MS_QUARANTINE_SOH_TYPE);
}
/// Add `ms_quarantine_soh` octets value to a packet.
pub fn add_ms_quarantine_soh(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_QUARANTINE_SOH_TYPE, value));
}
/// Lookup a `ms_quarantine_soh` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_quarantine_soh`, it returns `None`.
#[must_use]
pub fn lookup_ms_quarantine_soh(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(MS_QUARANTINE_SOH_TYPE).map(AVP::encode_bytes)
}
/// Lookup all of the `ms_quarantine_soh` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_quarantine_soh(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_QUARANTINE_SOH_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_RAS_CORRELATION_TYPE: AVPType = 56;
/// Delete all of `ms_ras_correlation` values from a packet.
pub fn delete_ms_ras_correlation(packet: &mut Packet) {
    packet.delete(MS_RAS_CORRELATION_TYPE);
}
/// Add `ms_ras_correlation` octets value to a packet.
pub fn add_ms_ras_correlation(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(MS_RAS_CORRELATION_TYPE, value));
}
/// Lookup a `ms_ras_correlation` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_ras_correlation`, it returns `None`.
#[must_use]
pub fn lookup_ms_ras_correlation(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(MS_RAS_CORRELATION_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `ms_ras_correlation` octets value from a packet.
#[must_use]
pub fn lookup_all_ms_ras_correlation(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_RAS_CORRELATION_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const MS_EXTENDED_QUARANTINE_STATE_TYPE: AVPType = 57;
/// Delete all of `ms_extended_quarantine_state` values from a packet.
pub fn delete_ms_extended_quarantine_state(packet: &mut Packet) {
    packet.delete(MS_EXTENDED_QUARANTINE_STATE_TYPE);
}
/// Add `ms_extended_quarantine_state` value-defined integer value to a packet.
pub fn add_ms_extended_quarantine_state(packet: &mut Packet, value: MsExtendedQuarantineState) {
    packet.add(AVP::from_u32(MS_EXTENDED_QUARANTINE_STATE_TYPE, value));
}
/// Lookup a `ms_extended_quarantine_state` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_extended_quarantine_state`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_extended_quarantine_state(
    packet: &Packet,
) -> Option<Result<MsExtendedQuarantineState, AVPError>> {
    packet
        .lookup(MS_EXTENDED_QUARANTINE_STATE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MsExtendedQuarantineState))
}
/// Lookup all of the `ms_extended_quarantine_state` value-defined integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_extended_quarantine_state(
    packet: &Packet,
) -> Result<Vec<MsExtendedQuarantineState>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_EXTENDED_QUARANTINE_STATE_TYPE) {
        vec.push(avp.encode_u32()? as MsExtendedQuarantineState);
    }
    Ok(vec)
}

pub const MS_HCAP_USER_GROUPS_TYPE: AVPType = 58;
/// Delete all of `ms_hcap_user_groups` values from a packet.
pub fn delete_ms_hcap_user_groups(packet: &mut Packet) {
    packet.delete(MS_HCAP_USER_GROUPS_TYPE);
}
/// Add `ms_hcap_user_groups` string value to a packet.
pub fn add_ms_hcap_user_groups(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_HCAP_USER_GROUPS_TYPE, value));
}
/// Lookup a `ms_hcap_user_groups` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_hcap_user_groups`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_hcap_user_groups(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MS_HCAP_USER_GROUPS_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `ms_hcap_user_groups` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_hcap_user_groups(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_HCAP_USER_GROUPS_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_HCAP_LOCATION_GROUP_NAME_TYPE: AVPType = 59;
/// Delete all of `ms_hcap_location_group_name` values from a packet.
pub fn delete_ms_hcap_location_group_name(packet: &mut Packet) {
    packet.delete(MS_HCAP_LOCATION_GROUP_NAME_TYPE);
}
/// Add `ms_hcap_location_group_name` string value to a packet.
pub fn add_ms_hcap_location_group_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_HCAP_LOCATION_GROUP_NAME_TYPE, value));
}
/// Lookup a `ms_hcap_location_group_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_hcap_location_group_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_hcap_location_group_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MS_HCAP_LOCATION_GROUP_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `ms_hcap_location_group_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_hcap_location_group_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_HCAP_LOCATION_GROUP_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_HCAP_USER_NAME_TYPE: AVPType = 60;
/// Delete all of `ms_hcap_user_name` values from a packet.
pub fn delete_ms_hcap_user_name(packet: &mut Packet) {
    packet.delete(MS_HCAP_USER_NAME_TYPE);
}
/// Add `ms_hcap_user_name` string value to a packet.
pub fn add_ms_hcap_user_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MS_HCAP_USER_NAME_TYPE, value));
}
/// Lookup a `ms_hcap_user_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_hcap_user_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_hcap_user_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MS_HCAP_USER_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `ms_hcap_user_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_hcap_user_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_HCAP_USER_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const MS_USER_I_PV_4_ADDRESS_TYPE: AVPType = 61;
/// Delete all of `ms_user_i_pv_4_address` values from a packet.
pub fn delete_ms_user_i_pv_4_address(packet: &mut Packet) {
    packet.delete(MS_USER_I_PV_4_ADDRESS_TYPE);
}
/// Add `ms_user_i_pv_4_address` ipaddr value to a packet.
pub fn add_ms_user_i_pv_4_address(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(MS_USER_I_PV_4_ADDRESS_TYPE, value));
}
/// Lookup a `ms_user_i_pv_4_address` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_user_i_pv_4_address`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_user_i_pv_4_address(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(MS_USER_I_PV_4_ADDRESS_TYPE)
        .map(AVP::encode_ipv4)
}
/// Lookup all of the `ms_user_i_pv_4_address` ipaddr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_user_i_pv_4_address(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_USER_I_PV_4_ADDRESS_TYPE) {
        vec.push(avp.encode_ipv4()?);
    }
    Ok(vec)
}

pub const MS_USER_I_PV_6_ADDRESS_TYPE: AVPType = 62;
/// Delete all of `ms_user_i_pv_6_address` values from a packet.
pub fn delete_ms_user_i_pv_6_address(packet: &mut Packet) {
    packet.delete(MS_USER_I_PV_6_ADDRESS_TYPE);
}
/// Add `ms_user_i_pv_6_address` ipv6addr value to a packet.
pub fn add_ms_user_i_pv_6_address(packet: &mut Packet, value: &Ipv6Addr) {
    packet.add(AVP::from_ipv6(MS_USER_I_PV_6_ADDRESS_TYPE, value));
}
/// Lookup a `ms_user_i_pv_6_address` ipv6addr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_user_i_pv_6_address`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_user_i_pv_6_address(packet: &Packet) -> Option<Result<Ipv6Addr, AVPError>> {
    packet
        .lookup(MS_USER_I_PV_6_ADDRESS_TYPE)
        .map(AVP::encode_ipv6)
}
/// Lookup all of the `ms_user_i_pv_6_address` ipv6addr value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_user_i_pv_6_address(packet: &Packet) -> Result<Vec<Ipv6Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_USER_I_PV_6_ADDRESS_TYPE) {
        vec.push(avp.encode_ipv6()?);
    }
    Ok(vec)
}

pub const MS_TSG_DEVICE_REDIRECTION_TYPE: AVPType = 63;
/// Delete all of `ms_tsg_device_redirection` values from a packet.
pub fn delete_ms_tsg_device_redirection(packet: &mut Packet) {
    packet.delete(MS_TSG_DEVICE_REDIRECTION_TYPE);
}
/// Add `ms_tsg_device_redirection` integer value to a packet.
pub fn add_ms_tsg_device_redirection(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MS_TSG_DEVICE_REDIRECTION_TYPE, value));
}
/// Lookup a `ms_tsg_device_redirection` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ms_tsg_device_redirection`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_ms_tsg_device_redirection(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MS_TSG_DEVICE_REDIRECTION_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `ms_tsg_device_redirection` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_ms_tsg_device_redirection(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MS_TSG_DEVICE_REDIRECTION_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub type MsAfwProtectionLevel = u32;
pub const MS_AFW_PROTECTION_LEVEL_HECP_RESPONSE_SIGN_ONLY: MsAfwProtectionLevel = 1;
pub const MS_AFW_PROTECTION_LEVEL_HECP_RESPONSE_SIGN_AND_ENCRYPT: MsAfwProtectionLevel = 2;

pub type MsAfwZone = u32;
pub const MS_AFW_ZONE_MS_AFW_ZONE_BOUNDARY_POLICY: MsAfwZone = 1;
pub const MS_AFW_ZONE_MS_AFW_ZONE_UNPROTECTED_POLICY: MsAfwZone = 2;
pub const MS_AFW_ZONE_MS_AFW_ZONE_PROTECTED_POLICY: MsAfwZone = 3;

pub type MsArapPwChangeReason = u32;
pub const MS_ARAP_PW_CHANGE_REASON_JUST_CHANGE_PASSWORD: MsArapPwChangeReason = 1;
pub const MS_ARAP_PW_CHANGE_REASON_EXPIRED_PASSWORD: MsArapPwChangeReason = 2;
pub const MS_ARAP_PW_CHANGE_REASON_ADMIN_REQUIRES_PASSWORD_CHANGE: MsArapPwChangeReason = 3;
pub const MS_ARAP_PW_CHANGE_REASON_PASSWORD_TOO_SHORT: MsArapPwChangeReason = 4;

pub type MsAcctAuthType = u32;
pub const MS_ACCT_AUTH_TYPE_PAP: MsAcctAuthType = 1;
pub const MS_ACCT_AUTH_TYPE_CHAP: MsAcctAuthType = 2;
pub const MS_ACCT_AUTH_TYPE_MS_CHAP_1: MsAcctAuthType = 3;
pub const MS_ACCT_AUTH_TYPE_MS_CHAP_2: MsAcctAuthType = 4;
pub const MS_ACCT_AUTH_TYPE_EAP: MsAcctAuthType = 5;

pub type MsAcctEAPType = u32;
pub const MS_ACCT_EAP_TYPE_MD5: MsAcctEAPType = 4;
pub const MS_ACCT_EAP_TYPE_OTP: MsAcctEAPType = 5;
pub const MS_ACCT_EAP_TYPE_GENERIC_TOKEN_CARD: MsAcctEAPType = 6;
pub const MS_ACCT_EAP_TYPE_TLS: MsAcctEAPType = 13;

pub type MsBapUsage = u32;
pub const MS_BAP_USAGE_NOT_ALLOWED: MsBapUsage = 0;
pub const MS_BAP_USAGE_ALLOWED: MsBapUsage = 1;
pub const MS_BAP_USAGE_REQUIRED: MsBapUsage = 2;

pub type MsExtendedQuarantineState = u32;
pub const MS_EXTENDED_QUARANTINE_STATE_TRANSITION: MsExtendedQuarantineState = 1;
pub const MS_EXTENDED_QUARANTINE_STATE_INFECTED: MsExtendedQuarantineState = 2;
pub const MS_EXTENDED_QUARANTINE_STATE_UNKNOWN: MsExtendedQuarantineState = 3;
pub const MS_EXTENDED_QUARANTINE_STATE_NO_DATA: MsExtendedQuarantineState = 4;

pub type MsIdentityType = u32;
pub const MS_IDENTITY_TYPE_MACHINE_HEALTH_CHECK: MsIdentityType = 1;
pub const MS_IDENTITY_TYPE_IGNORE_USER_LOOKUP_FAILURE: MsIdentityType = 2;

pub type MsMppeEncryptionPolicy = u32;
pub const MS_MPPE_ENCRYPTION_POLICY_ENCRYPTION_ALLOWED: MsMppeEncryptionPolicy = 1;
pub const MS_MPPE_ENCRYPTION_POLICY_ENCRYPTION_REQUIRED: MsMppeEncryptionPolicy = 2;

pub type MsMppeEncryptionTypes = u32;
pub const MS_MPPE_ENCRYPTION_TYPES_RC4_4_0BIT_ALLOWED: MsMppeEncryptionTypes = 1;
pub const MS_MPPE_ENCRYPTION_TYPES_RC4_12_8BIT_ALLOWED: MsMppeEncryptionTypes = 2;
pub const MS_MPPE_ENCRYPTION_TYPES_RC4_4_0OR_128_BIT_ALLOWED: MsMppeEncryptionTypes = 6;

pub type MsNetworkAccessServerType = u32;
pub const MS_NETWORK_ACCESS_SERVER_TYPE_UNSPECIFIED: MsNetworkAccessServerType = 0;
pub const MS_NETWORK_ACCESS_SERVER_TYPE_TERMINAL_SERVER_GATEWAY: MsNetworkAccessServerType = 1;
pub const MS_NETWORK_ACCESS_SERVER_TYPE_REMOTE_ACCESS_SERVER: MsNetworkAccessServerType = 2;
pub const MS_NETWORK_ACCESS_SERVER_TYPE_DHCP_SERVER: MsNetworkAccessServerType = 3;
pub const MS_NETWORK_ACCESS_SERVER_TYPE_WIRELESS_ACCESS_POINT: MsNetworkAccessServerType = 4;
pub const MS_NETWORK_ACCESS_SERVER_TYPE_HRA: MsNetworkAccessServerType = 5;
pub const MS_NETWORK_ACCESS_SERVER_TYPE_HCAP_SERVER: MsNetworkAccessServerType = 6;

pub type MsQuarantineState = u32;
pub const MS_QUARANTINE_STATE_FULL_ACCESS: MsQuarantineState = 0;
pub const MS_QUARANTINE_STATE_QUARANTINE: MsQuarantineState = 1;
pub const MS_QUARANTINE_STATE_PROBATION: MsQuarantineState = 2;

pub type MsRnapNotQuarantineCapable = u32;
pub const MS_RNAP_NOT_QUARANTINE_CAPABLE_SO_H_SENT: MsRnapNotQuarantineCapable = 0;
pub const MS_RNAP_NOT_QUARANTINE_CAPABLE_SO_H_NOT_SENT: MsRnapNotQuarantineCapable = 1;
