// Code generated by machine generator; DO NOT EDIT.

//! Utility for mikrotik packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2019 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! #
//! #    http://www.mikrotik.com
//! #
//! #    http://www.mikrotik.com/documentation//manual_2.9/dictionary
//! #
//! #    Do NOT follow their instructions and replace the dictionary
//! #    in /etc/raddb with the one that they supply.  It is NOT necessary.
//! #
//! #    On top of that, the sample dictionary file they provide
//! #    DOES NOT WORK.  Do NOT use it.
//! #
//! #    $Id$
//! #
//! VENDOR        Mikrotik            14988
//!
//! BEGIN-VENDOR    Mikrotik
//!
//! ATTRIBUTE    Mikrotik-Recv-Limit            1    integer
//! ATTRIBUTE    Mikrotik-Xmit-Limit            2    integer
//!
//! # this attribute is unused
//! ATTRIBUTE    Mikrotik-Group                3    string
//!
//! ATTRIBUTE    Mikrotik-Wireless-Forward        4    integer
//! ATTRIBUTE    Mikrotik-Wireless-Skip-Dot1x        5    integer
//! ATTRIBUTE    Mikrotik-Wireless-Enc-Algo        6    integer
//! ATTRIBUTE    Mikrotik-Wireless-Enc-Key        7    string
//! ATTRIBUTE    Mikrotik-Rate-Limit            8    string
//! ATTRIBUTE    Mikrotik-Realm                9    string
//! ATTRIBUTE    Mikrotik-Host-IP            10    ipaddr
//! ATTRIBUTE    Mikrotik-Mark-Id            11    string
//! ATTRIBUTE    Mikrotik-Advertise-URL            12    string
//! ATTRIBUTE    Mikrotik-Advertise-Interval        13    integer
//! ATTRIBUTE    Mikrotik-Recv-Limit-Gigawords        14    integer
//! ATTRIBUTE    Mikrotik-Xmit-Limit-Gigawords        15    integer
//! ATTRIBUTE    Mikrotik-Wireless-PSK            16    string
//! ATTRIBUTE    Mikrotik-Total-Limit            17    integer
//! ATTRIBUTE    Mikrotik-Total-Limit-Gigawords        18    integer
//! ATTRIBUTE    Mikrotik-Address-List            19    string
//! ATTRIBUTE    Mikrotik-Wireless-MPKey            20    string
//! ATTRIBUTE    Mikrotik-Wireless-Comment        21    string
//! ATTRIBUTE    Mikrotik-Delegated-IPv6-Pool        22    string
//! ATTRIBUTE    Mikrotik-DHCP-Option-Set        23    string
//! ATTRIBUTE    Mikrotik-DHCP-Option-Param-STR1        24    string
//! ATTRIBUTE    Mikrotik-DHCP-Option-Param-STR2        25    string
//! ATTRIBUTE    Mikrotik-DHCP-Option-ParamSTR2         25    string
//! ATTRIBUTE    Mikrotik-Wireless-VLANID        26    integer
//! ATTRIBUTE    Mikrotik-Wireless-VLANIDtype        27    integer
//! ATTRIBUTE    Mikrotik-Wireless-VLANID-Type         27    integer
//! ATTRIBUTE    Mikrotik-Wireless-Minsignal        28    string
//! ATTRIBUTE    Mikrotik-Wireless-Maxsignal        29    string
//! ATTRIBUTE    Mikrotik-Switching-Filter        30    string
//!
//! # MikroTik Values
//!
//! VALUE    Mikrotik-Wireless-Enc-Algo    No-encryption        0
//! VALUE    Mikrotik-Wireless-Enc-Algo    40-bit-WEP        1
//! VALUE    Mikrotik-Wireless-Enc-Algo    104-bit-WEP        2
//! VALUE    Mikrotik-Wireless-Enc-Algo    AES-CCM            3
//! VALUE    Mikrotik-Wireless-Enc-Algo    TKIP            4
//!
//! VALUE    Mikrotik-Wireless-VLANIDtype    802.1q            0
//! VALUE    Mikrotik-Wireless-VLANIDtype    802.1ad            1
//!
//! END-VENDOR    Mikrotik
//! ```

use std::net::Ipv4Addr;

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;

pub const MIKROTIK_RECV_LIMIT_TYPE: AVPType = 1;
/// Delete all of `mikrotik_recv_limit` values from a packet.
pub fn delete_mikrotik_recv_limit(packet: &mut Packet) {
    packet.delete(MIKROTIK_RECV_LIMIT_TYPE);
}
/// Add `mikrotik_recv_limit` integer value to a packet.
pub fn add_mikrotik_recv_limit(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_RECV_LIMIT_TYPE, value));
}
/// Lookup a `mikrotik_recv_limit` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_recv_limit`, it returns `None`.
pub fn lookup_mikrotik_recv_limit(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_RECV_LIMIT_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_recv_limit` integer value from a packet.
pub fn lookup_all_mikrotik_recv_limit(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_RECV_LIMIT_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_XMIT_LIMIT_TYPE: AVPType = 2;
/// Delete all of `mikrotik_xmit_limit` values from a packet.
pub fn delete_mikrotik_xmit_limit(packet: &mut Packet) {
    packet.delete(MIKROTIK_XMIT_LIMIT_TYPE);
}
/// Add `mikrotik_xmit_limit` integer value to a packet.
pub fn add_mikrotik_xmit_limit(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_XMIT_LIMIT_TYPE, value));
}
/// Lookup a `mikrotik_xmit_limit` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_xmit_limit`, it returns `None`.
pub fn lookup_mikrotik_xmit_limit(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_XMIT_LIMIT_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_xmit_limit` integer value from a packet.
pub fn lookup_all_mikrotik_xmit_limit(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_XMIT_LIMIT_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_GROUP_TYPE: AVPType = 3;
/// Delete all of `mikrotik_group` values from a packet.
pub fn delete_mikrotik_group(packet: &mut Packet) {
    packet.delete(MIKROTIK_GROUP_TYPE);
}
/// Add `mikrotik_group` string value to a packet.
pub fn add_mikrotik_group(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_GROUP_TYPE, value));
}
/// Lookup a `mikrotik_group` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_group`, it returns `None`.
pub fn lookup_mikrotik_group(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_GROUP_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_group` string value from a packet.
pub fn lookup_all_mikrotik_group(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_GROUP_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_FORWARD_TYPE: AVPType = 4;
/// Delete all of `mikrotik_wireless_forward` values from a packet.
pub fn delete_mikrotik_wireless_forward(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_FORWARD_TYPE);
}
/// Add `mikrotik_wireless_forward` integer value to a packet.
pub fn add_mikrotik_wireless_forward(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_WIRELESS_FORWARD_TYPE, value));
}
/// Lookup a `mikrotik_wireless_forward` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_forward`, it returns `None`.
pub fn lookup_mikrotik_wireless_forward(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_FORWARD_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_wireless_forward` integer value from a packet.
pub fn lookup_all_mikrotik_wireless_forward(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_FORWARD_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_SKIP_DOT_1X_TYPE: AVPType = 5;
/// Delete all of `mikrotik_wireless_skip_dot_1x` values from a packet.
pub fn delete_mikrotik_wireless_skip_dot_1x(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_SKIP_DOT_1X_TYPE);
}
/// Add `mikrotik_wireless_skip_dot_1x` integer value to a packet.
pub fn add_mikrotik_wireless_skip_dot_1x(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_WIRELESS_SKIP_DOT_1X_TYPE, value));
}
/// Lookup a `mikrotik_wireless_skip_dot_1x` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_skip_dot_1x`, it returns `None`.
pub fn lookup_mikrotik_wireless_skip_dot_1x(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_SKIP_DOT_1X_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_wireless_skip_dot_1x` integer value from a packet.
pub fn lookup_all_mikrotik_wireless_skip_dot_1x(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_SKIP_DOT_1X_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_ENC_ALGO_TYPE: AVPType = 6;
/// Delete all of `mikrotik_wireless_enc_algo` values from a packet.
pub fn delete_mikrotik_wireless_enc_algo(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_ENC_ALGO_TYPE);
}
/// Add `mikrotik_wireless_enc_algo` value-defined integer value to a packet.
pub fn add_mikrotik_wireless_enc_algo(packet: &mut Packet, value: MikrotikWirelessEncAlgo) {
    packet.add(AVP::from_u32(MIKROTIK_WIRELESS_ENC_ALGO_TYPE, value));
}
/// Lookup a `mikrotik_wireless_enc_algo` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_enc_algo`, it returns `None`.
pub fn lookup_mikrotik_wireless_enc_algo(
    packet: &Packet,
) -> Option<Result<MikrotikWirelessEncAlgo, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_ENC_ALGO_TYPE)
        .map(|v| Ok(v.encode_u32()? as MikrotikWirelessEncAlgo))
}
/// Lookup all of the `mikrotik_wireless_enc_algo` value-defined integer value from a packet.
pub fn lookup_all_mikrotik_wireless_enc_algo(
    packet: &Packet,
) -> Result<Vec<MikrotikWirelessEncAlgo>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_ENC_ALGO_TYPE) {
        vec.push(avp.encode_u32()? as MikrotikWirelessEncAlgo)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_ENC_KEY_TYPE: AVPType = 7;
/// Delete all of `mikrotik_wireless_enc_key` values from a packet.
pub fn delete_mikrotik_wireless_enc_key(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_ENC_KEY_TYPE);
}
/// Add `mikrotik_wireless_enc_key` string value to a packet.
pub fn add_mikrotik_wireless_enc_key(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_WIRELESS_ENC_KEY_TYPE, value));
}
/// Lookup a `mikrotik_wireless_enc_key` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_enc_key`, it returns `None`.
pub fn lookup_mikrotik_wireless_enc_key(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_ENC_KEY_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_wireless_enc_key` string value from a packet.
pub fn lookup_all_mikrotik_wireless_enc_key(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_ENC_KEY_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_RATE_LIMIT_TYPE: AVPType = 8;
/// Delete all of `mikrotik_rate_limit` values from a packet.
pub fn delete_mikrotik_rate_limit(packet: &mut Packet) {
    packet.delete(MIKROTIK_RATE_LIMIT_TYPE);
}
/// Add `mikrotik_rate_limit` string value to a packet.
pub fn add_mikrotik_rate_limit(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_RATE_LIMIT_TYPE, value));
}
/// Lookup a `mikrotik_rate_limit` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_rate_limit`, it returns `None`.
pub fn lookup_mikrotik_rate_limit(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_RATE_LIMIT_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_rate_limit` string value from a packet.
pub fn lookup_all_mikrotik_rate_limit(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_RATE_LIMIT_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_REALM_TYPE: AVPType = 9;
/// Delete all of `mikrotik_realm` values from a packet.
pub fn delete_mikrotik_realm(packet: &mut Packet) {
    packet.delete(MIKROTIK_REALM_TYPE);
}
/// Add `mikrotik_realm` string value to a packet.
pub fn add_mikrotik_realm(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_REALM_TYPE, value));
}
/// Lookup a `mikrotik_realm` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_realm`, it returns `None`.
pub fn lookup_mikrotik_realm(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_REALM_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_realm` string value from a packet.
pub fn lookup_all_mikrotik_realm(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_REALM_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_HOST_IP_TYPE: AVPType = 10;
/// Delete all of `mikrotik_host_ip` values from a packet.
pub fn delete_mikrotik_host_ip(packet: &mut Packet) {
    packet.delete(MIKROTIK_HOST_IP_TYPE);
}
/// Add `mikrotik_host_ip` ipaddr value to a packet.
pub fn add_mikrotik_host_ip(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(MIKROTIK_HOST_IP_TYPE, value));
}
/// Lookup a `mikrotik_host_ip` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_host_ip`, it returns `None`.
pub fn lookup_mikrotik_host_ip(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(MIKROTIK_HOST_IP_TYPE)
        .map(|v| v.encode_ipv4())
}
/// Lookup all of the `mikrotik_host_ip` ipaddr value from a packet.
pub fn lookup_all_mikrotik_host_ip(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_HOST_IP_TYPE) {
        vec.push(avp.encode_ipv4()?)
    }
    Ok(vec)
}

pub const MIKROTIK_MARK_ID_TYPE: AVPType = 11;
/// Delete all of `mikrotik_mark_id` values from a packet.
pub fn delete_mikrotik_mark_id(packet: &mut Packet) {
    packet.delete(MIKROTIK_MARK_ID_TYPE);
}
/// Add `mikrotik_mark_id` string value to a packet.
pub fn add_mikrotik_mark_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_MARK_ID_TYPE, value));
}
/// Lookup a `mikrotik_mark_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_mark_id`, it returns `None`.
pub fn lookup_mikrotik_mark_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_MARK_ID_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_mark_id` string value from a packet.
pub fn lookup_all_mikrotik_mark_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_MARK_ID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_ADVERTISE_URL_TYPE: AVPType = 12;
/// Delete all of `mikrotik_advertise_url` values from a packet.
pub fn delete_mikrotik_advertise_url(packet: &mut Packet) {
    packet.delete(MIKROTIK_ADVERTISE_URL_TYPE);
}
/// Add `mikrotik_advertise_url` string value to a packet.
pub fn add_mikrotik_advertise_url(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_ADVERTISE_URL_TYPE, value));
}
/// Lookup a `mikrotik_advertise_url` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_advertise_url`, it returns `None`.
pub fn lookup_mikrotik_advertise_url(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_ADVERTISE_URL_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_advertise_url` string value from a packet.
pub fn lookup_all_mikrotik_advertise_url(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_ADVERTISE_URL_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_ADVERTISE_INTERVAL_TYPE: AVPType = 13;
/// Delete all of `mikrotik_advertise_interval` values from a packet.
pub fn delete_mikrotik_advertise_interval(packet: &mut Packet) {
    packet.delete(MIKROTIK_ADVERTISE_INTERVAL_TYPE);
}
/// Add `mikrotik_advertise_interval` integer value to a packet.
pub fn add_mikrotik_advertise_interval(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_ADVERTISE_INTERVAL_TYPE, value));
}
/// Lookup a `mikrotik_advertise_interval` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_advertise_interval`, it returns `None`.
pub fn lookup_mikrotik_advertise_interval(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_ADVERTISE_INTERVAL_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_advertise_interval` integer value from a packet.
pub fn lookup_all_mikrotik_advertise_interval(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_ADVERTISE_INTERVAL_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_RECV_LIMIT_GIGAWORDS_TYPE: AVPType = 14;
/// Delete all of `mikrotik_recv_limit_gigawords` values from a packet.
pub fn delete_mikrotik_recv_limit_gigawords(packet: &mut Packet) {
    packet.delete(MIKROTIK_RECV_LIMIT_GIGAWORDS_TYPE);
}
/// Add `mikrotik_recv_limit_gigawords` integer value to a packet.
pub fn add_mikrotik_recv_limit_gigawords(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_RECV_LIMIT_GIGAWORDS_TYPE, value));
}
/// Lookup a `mikrotik_recv_limit_gigawords` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_recv_limit_gigawords`, it returns `None`.
pub fn lookup_mikrotik_recv_limit_gigawords(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_RECV_LIMIT_GIGAWORDS_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_recv_limit_gigawords` integer value from a packet.
pub fn lookup_all_mikrotik_recv_limit_gigawords(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_RECV_LIMIT_GIGAWORDS_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_XMIT_LIMIT_GIGAWORDS_TYPE: AVPType = 15;
/// Delete all of `mikrotik_xmit_limit_gigawords` values from a packet.
pub fn delete_mikrotik_xmit_limit_gigawords(packet: &mut Packet) {
    packet.delete(MIKROTIK_XMIT_LIMIT_GIGAWORDS_TYPE);
}
/// Add `mikrotik_xmit_limit_gigawords` integer value to a packet.
pub fn add_mikrotik_xmit_limit_gigawords(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_XMIT_LIMIT_GIGAWORDS_TYPE, value));
}
/// Lookup a `mikrotik_xmit_limit_gigawords` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_xmit_limit_gigawords`, it returns `None`.
pub fn lookup_mikrotik_xmit_limit_gigawords(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_XMIT_LIMIT_GIGAWORDS_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_xmit_limit_gigawords` integer value from a packet.
pub fn lookup_all_mikrotik_xmit_limit_gigawords(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_XMIT_LIMIT_GIGAWORDS_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_PSK_TYPE: AVPType = 16;
/// Delete all of `mikrotik_wireless_psk` values from a packet.
pub fn delete_mikrotik_wireless_psk(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_PSK_TYPE);
}
/// Add `mikrotik_wireless_psk` string value to a packet.
pub fn add_mikrotik_wireless_psk(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_WIRELESS_PSK_TYPE, value));
}
/// Lookup a `mikrotik_wireless_psk` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_psk`, it returns `None`.
pub fn lookup_mikrotik_wireless_psk(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_PSK_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_wireless_psk` string value from a packet.
pub fn lookup_all_mikrotik_wireless_psk(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_PSK_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_TOTAL_LIMIT_TYPE: AVPType = 17;
/// Delete all of `mikrotik_total_limit` values from a packet.
pub fn delete_mikrotik_total_limit(packet: &mut Packet) {
    packet.delete(MIKROTIK_TOTAL_LIMIT_TYPE);
}
/// Add `mikrotik_total_limit` integer value to a packet.
pub fn add_mikrotik_total_limit(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_TOTAL_LIMIT_TYPE, value));
}
/// Lookup a `mikrotik_total_limit` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_total_limit`, it returns `None`.
pub fn lookup_mikrotik_total_limit(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_TOTAL_LIMIT_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_total_limit` integer value from a packet.
pub fn lookup_all_mikrotik_total_limit(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_TOTAL_LIMIT_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_TOTAL_LIMIT_GIGAWORDS_TYPE: AVPType = 18;
/// Delete all of `mikrotik_total_limit_gigawords` values from a packet.
pub fn delete_mikrotik_total_limit_gigawords(packet: &mut Packet) {
    packet.delete(MIKROTIK_TOTAL_LIMIT_GIGAWORDS_TYPE);
}
/// Add `mikrotik_total_limit_gigawords` integer value to a packet.
pub fn add_mikrotik_total_limit_gigawords(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_TOTAL_LIMIT_GIGAWORDS_TYPE, value));
}
/// Lookup a `mikrotik_total_limit_gigawords` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_total_limit_gigawords`, it returns `None`.
pub fn lookup_mikrotik_total_limit_gigawords(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_TOTAL_LIMIT_GIGAWORDS_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_total_limit_gigawords` integer value from a packet.
pub fn lookup_all_mikrotik_total_limit_gigawords(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_TOTAL_LIMIT_GIGAWORDS_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_ADDRESS_LIST_TYPE: AVPType = 19;
/// Delete all of `mikrotik_address_list` values from a packet.
pub fn delete_mikrotik_address_list(packet: &mut Packet) {
    packet.delete(MIKROTIK_ADDRESS_LIST_TYPE);
}
/// Add `mikrotik_address_list` string value to a packet.
pub fn add_mikrotik_address_list(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_ADDRESS_LIST_TYPE, value));
}
/// Lookup a `mikrotik_address_list` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_address_list`, it returns `None`.
pub fn lookup_mikrotik_address_list(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_ADDRESS_LIST_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_address_list` string value from a packet.
pub fn lookup_all_mikrotik_address_list(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_ADDRESS_LIST_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_MP_KEY_TYPE: AVPType = 20;
/// Delete all of `mikrotik_wireless_mp_key` values from a packet.
pub fn delete_mikrotik_wireless_mp_key(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_MP_KEY_TYPE);
}
/// Add `mikrotik_wireless_mp_key` string value to a packet.
pub fn add_mikrotik_wireless_mp_key(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_WIRELESS_MP_KEY_TYPE, value));
}
/// Lookup a `mikrotik_wireless_mp_key` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_mp_key`, it returns `None`.
pub fn lookup_mikrotik_wireless_mp_key(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_MP_KEY_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_wireless_mp_key` string value from a packet.
pub fn lookup_all_mikrotik_wireless_mp_key(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_MP_KEY_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_COMMENT_TYPE: AVPType = 21;
/// Delete all of `mikrotik_wireless_comment` values from a packet.
pub fn delete_mikrotik_wireless_comment(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_COMMENT_TYPE);
}
/// Add `mikrotik_wireless_comment` string value to a packet.
pub fn add_mikrotik_wireless_comment(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_WIRELESS_COMMENT_TYPE, value));
}
/// Lookup a `mikrotik_wireless_comment` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_comment`, it returns `None`.
pub fn lookup_mikrotik_wireless_comment(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_COMMENT_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_wireless_comment` string value from a packet.
pub fn lookup_all_mikrotik_wireless_comment(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_COMMENT_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_DELEGATED_I_PV_6_POOL_TYPE: AVPType = 22;
/// Delete all of `mikrotik_delegated_i_pv_6_pool` values from a packet.
pub fn delete_mikrotik_delegated_i_pv_6_pool(packet: &mut Packet) {
    packet.delete(MIKROTIK_DELEGATED_I_PV_6_POOL_TYPE);
}
/// Add `mikrotik_delegated_i_pv_6_pool` string value to a packet.
pub fn add_mikrotik_delegated_i_pv_6_pool(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_DELEGATED_I_PV_6_POOL_TYPE, value));
}
/// Lookup a `mikrotik_delegated_i_pv_6_pool` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_delegated_i_pv_6_pool`, it returns `None`.
pub fn lookup_mikrotik_delegated_i_pv_6_pool(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_DELEGATED_I_PV_6_POOL_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_delegated_i_pv_6_pool` string value from a packet.
pub fn lookup_all_mikrotik_delegated_i_pv_6_pool(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_DELEGATED_I_PV_6_POOL_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_DHCP_OPTION_SET_TYPE: AVPType = 23;
/// Delete all of `mikrotik_dhcp_option_set` values from a packet.
pub fn delete_mikrotik_dhcp_option_set(packet: &mut Packet) {
    packet.delete(MIKROTIK_DHCP_OPTION_SET_TYPE);
}
/// Add `mikrotik_dhcp_option_set` string value to a packet.
pub fn add_mikrotik_dhcp_option_set(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_DHCP_OPTION_SET_TYPE, value));
}
/// Lookup a `mikrotik_dhcp_option_set` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_dhcp_option_set`, it returns `None`.
pub fn lookup_mikrotik_dhcp_option_set(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_DHCP_OPTION_SET_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_dhcp_option_set` string value from a packet.
pub fn lookup_all_mikrotik_dhcp_option_set(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_DHCP_OPTION_SET_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_DHCP_OPTION_PARAM_STR1_TYPE: AVPType = 24;
/// Delete all of `mikrotik_dhcp_option_param_str1` values from a packet.
pub fn delete_mikrotik_dhcp_option_param_str1(packet: &mut Packet) {
    packet.delete(MIKROTIK_DHCP_OPTION_PARAM_STR1_TYPE);
}
/// Add `mikrotik_dhcp_option_param_str1` string value to a packet.
pub fn add_mikrotik_dhcp_option_param_str1(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(
        MIKROTIK_DHCP_OPTION_PARAM_STR1_TYPE,
        value,
    ));
}
/// Lookup a `mikrotik_dhcp_option_param_str1` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_dhcp_option_param_str1`, it returns `None`.
pub fn lookup_mikrotik_dhcp_option_param_str1(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_DHCP_OPTION_PARAM_STR1_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_dhcp_option_param_str1` string value from a packet.
pub fn lookup_all_mikrotik_dhcp_option_param_str1(
    packet: &Packet,
) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_DHCP_OPTION_PARAM_STR1_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_DHCP_OPTION_PARAM_STR2_TYPE: AVPType = 25;
/// Delete all of `mikrotik_dhcp_option_param_str2` values from a packet.
pub fn delete_mikrotik_dhcp_option_param_str2(packet: &mut Packet) {
    packet.delete(MIKROTIK_DHCP_OPTION_PARAM_STR2_TYPE);
}
/// Add `mikrotik_dhcp_option_param_str2` string value to a packet.
pub fn add_mikrotik_dhcp_option_param_str2(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(
        MIKROTIK_DHCP_OPTION_PARAM_STR2_TYPE,
        value,
    ));
}
/// Lookup a `mikrotik_dhcp_option_param_str2` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_dhcp_option_param_str2`, it returns `None`.
pub fn lookup_mikrotik_dhcp_option_param_str2(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_DHCP_OPTION_PARAM_STR2_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_dhcp_option_param_str2` string value from a packet.
pub fn lookup_all_mikrotik_dhcp_option_param_str2(
    packet: &Packet,
) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_DHCP_OPTION_PARAM_STR2_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_VLANID_TYPE: AVPType = 26;
/// Delete all of `mikrotik_wireless_vlanid` values from a packet.
pub fn delete_mikrotik_wireless_vlanid(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_VLANID_TYPE);
}
/// Add `mikrotik_wireless_vlanid` integer value to a packet.
pub fn add_mikrotik_wireless_vlanid(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(MIKROTIK_WIRELESS_VLANID_TYPE, value));
}
/// Lookup a `mikrotik_wireless_vlanid` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_vlanid`, it returns `None`.
pub fn lookup_mikrotik_wireless_vlanid(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_VLANID_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `mikrotik_wireless_vlanid` integer value from a packet.
pub fn lookup_all_mikrotik_wireless_vlanid(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_VLANID_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_VLANI_DTYPE_TYPE: AVPType = 27;
/// Delete all of `mikrotik_wireless_vlani_dtype` values from a packet.
pub fn delete_mikrotik_wireless_vlani_dtype(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_VLANI_DTYPE_TYPE);
}
/// Add `mikrotik_wireless_vlani_dtype` value-defined integer value to a packet.
pub fn add_mikrotik_wireless_vlani_dtype(packet: &mut Packet, value: MikrotikWirelessVLANIDtype) {
    packet.add(AVP::from_u32(MIKROTIK_WIRELESS_VLANI_DTYPE_TYPE, value));
}
/// Lookup a `mikrotik_wireless_vlani_dtype` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_vlani_dtype`, it returns `None`.
pub fn lookup_mikrotik_wireless_vlani_dtype(
    packet: &Packet,
) -> Option<Result<MikrotikWirelessVLANIDtype, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_VLANI_DTYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as MikrotikWirelessVLANIDtype))
}
/// Lookup all of the `mikrotik_wireless_vlani_dtype` value-defined integer value from a packet.
pub fn lookup_all_mikrotik_wireless_vlani_dtype(
    packet: &Packet,
) -> Result<Vec<MikrotikWirelessVLANIDtype>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_VLANI_DTYPE_TYPE) {
        vec.push(avp.encode_u32()? as MikrotikWirelessVLANIDtype)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_MINSIGNAL_TYPE: AVPType = 28;
/// Delete all of `mikrotik_wireless_minsignal` values from a packet.
pub fn delete_mikrotik_wireless_minsignal(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_MINSIGNAL_TYPE);
}
/// Add `mikrotik_wireless_minsignal` string value to a packet.
pub fn add_mikrotik_wireless_minsignal(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_WIRELESS_MINSIGNAL_TYPE, value));
}
/// Lookup a `mikrotik_wireless_minsignal` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_minsignal`, it returns `None`.
pub fn lookup_mikrotik_wireless_minsignal(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_MINSIGNAL_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_wireless_minsignal` string value from a packet.
pub fn lookup_all_mikrotik_wireless_minsignal(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_MINSIGNAL_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_WIRELESS_MAXSIGNAL_TYPE: AVPType = 29;
/// Delete all of `mikrotik_wireless_maxsignal` values from a packet.
pub fn delete_mikrotik_wireless_maxsignal(packet: &mut Packet) {
    packet.delete(MIKROTIK_WIRELESS_MAXSIGNAL_TYPE);
}
/// Add `mikrotik_wireless_maxsignal` string value to a packet.
pub fn add_mikrotik_wireless_maxsignal(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_WIRELESS_MAXSIGNAL_TYPE, value));
}
/// Lookup a `mikrotik_wireless_maxsignal` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_wireless_maxsignal`, it returns `None`.
pub fn lookup_mikrotik_wireless_maxsignal(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_WIRELESS_MAXSIGNAL_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_wireless_maxsignal` string value from a packet.
pub fn lookup_all_mikrotik_wireless_maxsignal(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_WIRELESS_MAXSIGNAL_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const MIKROTIK_SWITCHING_FILTER_TYPE: AVPType = 30;
/// Delete all of `mikrotik_switching_filter` values from a packet.
pub fn delete_mikrotik_switching_filter(packet: &mut Packet) {
    packet.delete(MIKROTIK_SWITCHING_FILTER_TYPE);
}
/// Add `mikrotik_switching_filter` string value to a packet.
pub fn add_mikrotik_switching_filter(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(MIKROTIK_SWITCHING_FILTER_TYPE, value));
}
/// Lookup a `mikrotik_switching_filter` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `mikrotik_switching_filter`, it returns `None`.
pub fn lookup_mikrotik_switching_filter(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(MIKROTIK_SWITCHING_FILTER_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `mikrotik_switching_filter` string value from a packet.
pub fn lookup_all_mikrotik_switching_filter(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(MIKROTIK_SWITCHING_FILTER_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub type MikrotikWirelessEncAlgo = u32;
pub const MIKROTIK_WIRELESS_ENC_ALGO_NO_ENCRYPTION: MikrotikWirelessEncAlgo = 0;
pub const MIKROTIK_WIRELESS_ENC_ALGO_40_BIT_WEP: MikrotikWirelessEncAlgo = 1;
pub const MIKROTIK_WIRELESS_ENC_ALGO_104_BIT_WEP: MikrotikWirelessEncAlgo = 2;
pub const MIKROTIK_WIRELESS_ENC_ALGO_AES_CCM: MikrotikWirelessEncAlgo = 3;
pub const MIKROTIK_WIRELESS_ENC_ALGO_TKIP: MikrotikWirelessEncAlgo = 4;

pub type MikrotikWirelessVLANIDtype = u32;
pub const MIKROTIK_WIRELESS_VLANI_DTYPE_802_1Q: MikrotikWirelessVLANIDtype = 0;
pub const MIKROTIK_WIRELESS_VLANI_DTYPE_802_1AD: MikrotikWirelessVLANIDtype = 1;
