// Code generated by machine generator; DO NOT EDIT.

//! Utility for rfc3580 packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2020 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! # Version $Id$
//! #
//! #    Attributes and values defined in RFC 3580.
//! #    http://www.ietf.org/rfc/rfc3580.txt
//! #
//! #    $Id$
//! #
//! VALUE    Acct-Terminate-Cause        Supplicant-Restart    19
//! VALUE    Acct-Terminate-Cause        Reauthentication-Failure    20
//! VALUE    Acct-Terminate-Cause        Port-Reinit        21
//! VALUE    Acct-Terminate-Cause        Port-Disabled        22
//!
//! VALUE    NAS-Port-Type            Token-Ring        20
//! VALUE    NAS-Port-Type            FDDI            21
//!
//! VALUE    Tunnel-Type            VLAN            13
//! ```

use std::net::{Ipv4Addr, Ipv6Addr};

use std::time::SystemTime;

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;
use crate::core::tag::Tag;

use crate::core::ascend;
use crate::core::cisco;
use crate::core::juniper;
use crate::core::microsoft;
use crate::core::mikrotik;
use crate::core::rfc2865;
use crate::core::rfc2866;
use crate::core::rfc2867;
use crate::core::rfc2868;
use crate::core::rfc2869;
use crate::core::rfc3162;
use crate::core::rfc3576;
pub const ACCT_TERMINATE_CAUSE_SUPPLICANT_RESTART: rfc2866::AcctTerminateCause = 19;
pub const ACCT_TERMINATE_CAUSE_REAUTHENTICATION_FAILURE: rfc2866::AcctTerminateCause = 20;
pub const ACCT_TERMINATE_CAUSE_PORT_REINIT: rfc2866::AcctTerminateCause = 21;
pub const ACCT_TERMINATE_CAUSE_PORT_DISABLED: rfc2866::AcctTerminateCause = 22;

pub const NAS_PORT_TYPE_TOKEN_RING: rfc2865::NasPortType = 20;
pub const NAS_PORT_TYPE_FDDI: rfc2865::NasPortType = 21;

pub const TUNNEL_TYPE_VLAN: rfc2868::TunnelType = 13;
