// Code generated by machine generator; DO NOT EDIT.

//! Utility for rfc5176 packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2020 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! # Version $Id$
//! #
//! #    Attributes and values defined in RFC 5176.
//! #    http://www.ietf.org/rfc/rfc5176.txt
//! #
//! #    $Id$
//! #
//! VALUE    Error-Cause            Invalid-Attribute-Value    407
//! VALUE    Error-Cause            Multiple-Session-Selection-Unsupported    508
//! ```

use std::net::{Ipv4Addr, Ipv6Addr};

use std::time::SystemTime;

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;
use crate::core::tag::Tag;

use crate::core::ascend;
use crate::core::cisco;
use crate::core::juniper;
use crate::core::microsoft;
use crate::core::mikrotik;
use crate::core::rfc2865;
use crate::core::rfc2866;
use crate::core::rfc2867;
use crate::core::rfc2868;
use crate::core::rfc2869;
use crate::core::rfc3162;
use crate::core::rfc3576;
use crate::core::rfc3580;
use crate::core::rfc4072;
use crate::core::rfc4372;
use crate::core::rfc4603;
use crate::core::rfc4675;
use crate::core::rfc4818;
use crate::core::rfc4849;
use crate::core::rfc5090;
pub const ERROR_CAUSE_INVALID_ATTRIBUTE_VALUE: rfc3576::ErrorCause = 407;
pub const ERROR_CAUSE_MULTIPLE_SESSION_SELECTION_UNSUPPORTED: rfc3576::ErrorCause = 508;
