// Code generated by machine generator; DO NOT EDIT.

//! Utility for ruckus packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2019 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! #
//! #	Ruckus Wireless, Inc. dictionary
//! #
//! #
//!
//! VENDOR		Ruckus				25053
//!
//! BEGIN-VENDOR	Ruckus
//!
//! # Value Format:    group_attr1,group_attr2,...
//! ATTRIBUTE	Ruckus-User-Groups			1	string
//! ATTRIBUTE	Ruckus-Sta-RSSI				2	integer
//! ATTRIBUTE	Ruckus-SSID				3	string
//! ATTRIBUTE	Ruckus-Wlan-Id				4	integer
//! ATTRIBUTE	Ruckus-Location				5	string
//! ATTRIBUTE	Ruckus-Grace-Period			6	integer
//! ATTRIBUTE	Ruckus-SCG-CBlade-IP			7	integer
//! ATTRIBUTE	Ruckus-SCG-DBlade-IP			8	integer
//! ATTRIBUTE	Ruckus-VLAN-ID				9	integer
//! ATTRIBUTE	Ruckus-Sta-Expiration			10	integer # not used by AP anymore. Please check SCG-33602
//! ATTRIBUTE	Ruckus-Sta-UUID				11	string
//! ATTRIBUTE	Ruckus-Accept-Enhancement-Reason	12	integer
//! ATTRIBUTE	Ruckus-Sta-Inner-Id			13	string
//! ATTRIBUTE	Ruckus-BSSID				14	octets
//!
//! ATTRIBUTE	Ruckus-FlexAuth-AVP			20	string
//!
//! ATTRIBUTE	Ruckus-WSG-User				10	string
//!
//! ATTRIBUTE	Ruckus-Triplets				101	octets
//! ATTRIBUTE	Ruckus-IMSI				102	octets
//! ATTRIBUTE	Ruckus-MSISDN				103	octets
//! ATTRIBUTE	Ruckus-APN-NI				104	string
//! ATTRIBUTE	Ruckus-QoS				105	octets
//! ATTRIBUTE	Ruckus-Selection-Mode			106	integer
//! ATTRIBUTE	Ruckus-APN-Resolution-Req		107	integer
//! ATTRIBUTE	Ruckus-Start-Time			108	octets
//! ATTRIBUTE	Ruckus-NAS-Type				109	integer
//! ATTRIBUTE	Ruckus-Status				110	integer
//! ATTRIBUTE	Ruckus-APN-OI				111	string
//! ATTRIBUTE	Ruckus-Auth-Type			112	integer
//! ATTRIBUTE	Ruckus-Gn-User-Name			113	string
//! ATTRIBUTE	Ruckus-Brand-Code			114	string
//! ATTRIBUTE	Ruckus-Policy-Name			115	string
//! ATTRIBUTE	Ruckus-Client-Local-IP			116	ipaddr
//! ATTRIBUTE	Ruckus-SGSN-IP				117	ipaddr
//! ATTRIBUTE	Ruckus-Charging-Charac			118	octets
//! ATTRIBUTE	Ruckus-PDP-Type				119	octets
//! ATTRIBUTE	Ruckus-Dynamic-Address-Flag		120	octets
//! ATTRIBUTE	Ruckus-ChCh-Selection-Mode		121	octets
//! ATTRIBUTE	Ruckus-AAA-IP				122	ipaddr
//! ATTRIBUTE	Ruckus-CDR-TYPE				123	integer
//! ATTRIBUTE	Ruckus-SGSN-Number			124	octets
//! ATTRIBUTE	Ruckus-Session-Type			125	integer
//! ATTRIBUTE	Ruckus-Accounting-Status		126	integer
//! ATTRIBUTE	Ruckus-Zone-Id				127	string
//! ATTRIBUTE	Ruckus-Auth-Server-Id			128	string
//! ATTRIBUTE	Ruckus-Utp-Id				129	string
//! ATTRIBUTE	Ruckus-Area-Code			130	octets
//! ATTRIBUTE	Ruckus-Cell-Identifier			131	octets
//! ATTRIBUTE	Ruckus-Wispr-Redirect-Policy		132	string
//! ATTRIBUTE	Ruckus-Eth-Profile-Id			133	integer
//! ATTRIBUTE	Ruckus-Zone-Name			134	string
//! ATTRIBUTE	Ruckus-Wlan-Name			135	string
//! ATTRIBUTE	Ruckus-AP-Roamed			136	integer
//! ATTRIBUTE	Ruckus-Read-Preference			137	octets
//! ATTRIBUTE	Ruckus-Client-Host-Name			138	string
//! ATTRIBUTE	Ruckus-Client-Os-Type			139	string
//! ATTRIBUTE	Ruckus-Client-Os-Class			140	string
//! ATTRIBUTE	Ruckus-Vlan-Pool			141	string
//!
//! # 0x00 + (PBKDF2(HMAC−SHA1, passphrase, ssid, 4096, 256))
//! # for a length of 33 octets.
//! ATTRIBUTE	Ruckus-DPSK				142	octets
//! ATTRIBUTE	Ruckus-CP-Token				143	string
//! ATTRIBUTE	Ruckus-Max-DL-UL-Quota			144	integer
//! ATTRIBUTE	Ruckus-Traffic-Class-Attribute-Ids	145	string
//! ATTRIBUTE	Ruckus-TC-Attr-Ids-With-Quota		146	tlv
//! ATTRIBUTE	Ruckus-TC-Name-Quota			146.1	string
//! ATTRIBUTE	Ruckus-TC-Quota				146.2	octets
//!
//! ATTRIBUTE	Ruckus-Nat-Pool-Name			147	string
//! ATTRIBUTE	Ruckus-Sta-SVlan-Id			148	integer
//! ATTRIBUTE	Ruckus-TC-Acct-Ctrs			149	tlv
//! ATTRIBUTE	Ruckus-Acct-Ctrs_TC-Name		149.1	string
//! ATTRIBUTE	Ruckus-Acct-Ctrs_Input-Octets		149.2	integer
//! ATTRIBUTE	Ruckus-Acct-Ctrs_Output-Octets		149.3	integer
//! ATTRIBUTE	Ruckus-Acct-Ctrs_Input-Packets		149.4	integer
//! ATTRIBUTE	Ruckus-Acct-Ctrs_Output-Packets		149.5	integer
//!
//! ATTRIBUTE	Ruckus-AAA-Id				152	string
//! ATTRIBUTE	Ruckus-DPSK-Params			153	tlv
//! ATTRIBUTE	Ruckus-DPSK-AKM-Suite			153.1	octets
//! ATTRIBUTE	Ruckus-DPSK-Cipher			153.2	byte
//! ATTRIBUTE	Ruckus-DPSK-Anonce			153.3	octets
//! ATTRIBUTE	Ruckus-DPSK-EAPOL-Key-Frame		153.4	octets
//! ATTRIBUTE	Ruckus-Cluster-Name			154	string
//! ATTRIBUTE	Ruckus-Domain-Name			155	string
//! ATTRIBUTE	Ruckus-Client-Device-Type		156	string
//! ATTRIBUTE	Ruckus-Vlan-Name			157	string
//!
//! # Ruckus SmartCell Insight Attributes
//! ATTRIBUTE Ruckus-SCI-Role		200 string
//! ATTRIBUTE Ruckus-SCI-Resource-Group		201 string
//!
//! #
//! #  Integer Translations
//! #
//!
//! #  Ruckus-Selection-Mode Values
//!
//! VALUE	Ruckus-Selection-Mode		Subscribed		0
//! VALUE	Ruckus-Selection-Mode		SentByMS		1
//! VALUE	Ruckus-Selection-Mode		ChosenBySGSN		2
//!
//! #  Ruckus-APN-Resolution-Req Values
//!
//! VALUE	Ruckus-APN-Resolution-Req	NotRequired		0
//! VALUE	Ruckus-APN-Resolution-Req	Required		1
//!
//! #  Ruckus-Status Values
//!
//! VALUE	Ruckus-Status			Success			0
//! VALUE	Ruckus-Status			Failure			1
//!
//! #  Ruckus-Auth-Type Values
//!
//! VALUE	Ruckus-Auth-Type		PPP-SIM			1
//! VALUE	Ruckus-Auth-Type		DummyIMSI		2
//! VALUE	Ruckus-Auth-Type		SoftSIM			3
//! VALUE	Ruckus-Auth-Type		RadiusSIM		4
//! VALUE	Ruckus-Auth-Type		Postpaid		5
//! VALUE	Ruckus-Auth-Type		Prepaid			6
//! VALUE	Ruckus-Auth-Type		LocalRadius		7
//! VALUE	Ruckus-Auth-Type		ProxyRadius		8
//! VALUE	Ruckus-Auth-Type		Voucher			9
//! VALUE	Ruckus-Auth-Type		EAP-SIM			10
//!
//! # Ruckus-Session-Type Values
//! # Updated as per SCG2.1
//! #Value (1) No more valid for SCG2.1
//! VALUE	Ruckus-Session-Type		TTG			2
//! VALUE	Ruckus-Session-Type		Local-Breakout		3
//! VALUE	Ruckus-Session-Type		Local-Breakout-AP	4
//! VALUE	Ruckus-Session-Type		L3GRE			5
//! VALUE	Ruckus-Session-Type		L2GRE			6
//! VALUE	Ruckus-Session-Type		QinQL3			7
//! VALUE	Ruckus-Session-Type		PMIP			8
//!
//! #RUCKUS-NAS_Type
//!
//! VALUE	Ruckus-NAS-Type			SCG			1
//! VALUE	Ruckus-NAS-Type			Others			2
//!
//! #Ruckus-Accounting-Status
//! VALUE	Ruckus-Accounting-Status	Accounting-On		1
//! VALUE	Ruckus-Accounting-Status	Accounting-Off		0
//!
//! END-VENDOR Ruckus
//! ```

use std::net::{Ipv4Addr, Ipv6Addr};

use std::time::SystemTime;

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;
use crate::core::tag::Tag;

use crate::core::ascend;
use crate::core::cisco;
use crate::core::juniper;
use crate::core::microsoft;
use crate::core::mikrotik;
use crate::core::rfc2865;
use crate::core::rfc2866;
use crate::core::rfc2867;
use crate::core::rfc2868;
use crate::core::rfc2869;
use crate::core::rfc3162;
use crate::core::rfc3576;
use crate::core::rfc3580;
use crate::core::rfc4072;
use crate::core::rfc4372;
use crate::core::rfc4603;
use crate::core::rfc4675;
use crate::core::rfc4818;
use crate::core::rfc4849;
use crate::core::rfc5090;
use crate::core::rfc5176;
use crate::core::rfc5607;
use crate::core::rfc5904;
use crate::core::rfc6519;
use crate::core::rfc6572;
use crate::core::rfc6677;
use crate::core::rfc6911;
use crate::core::rfc7055;
use crate::core::rfc7155;

pub const RUCKUS_USER_GROUPS_TYPE: AVPType = 1;
/// Delete all of `ruckus_user_groups` values from a packet.
pub fn delete_ruckus_user_groups(packet: &mut Packet) {
    packet.delete(RUCKUS_USER_GROUPS_TYPE);
}
/// Add `ruckus_user_groups` string value to a packet.
pub fn add_ruckus_user_groups(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_USER_GROUPS_TYPE, value));
}
/// Lookup a `ruckus_user_groups` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_user_groups`, it returns `None`.
pub fn lookup_ruckus_user_groups(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_USER_GROUPS_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_user_groups` string value from a packet.
pub fn lookup_all_ruckus_user_groups(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_USER_GROUPS_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_STA_RSSI_TYPE: AVPType = 2;
/// Delete all of `ruckus_sta_rssi` values from a packet.
pub fn delete_ruckus_sta_rssi(packet: &mut Packet) {
    packet.delete(RUCKUS_STA_RSSI_TYPE);
}
/// Add `ruckus_sta_rssi` integer value to a packet.
pub fn add_ruckus_sta_rssi(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_STA_RSSI_TYPE, value));
}
/// Lookup a `ruckus_sta_rssi` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sta_rssi`, it returns `None`.
pub fn lookup_ruckus_sta_rssi(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet.lookup(RUCKUS_STA_RSSI_TYPE).map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_sta_rssi` integer value from a packet.
pub fn lookup_all_ruckus_sta_rssi(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_STA_RSSI_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_SSID_TYPE: AVPType = 3;
/// Delete all of `ruckus_ssid` values from a packet.
pub fn delete_ruckus_ssid(packet: &mut Packet) {
    packet.delete(RUCKUS_SSID_TYPE);
}
/// Add `ruckus_ssid` string value to a packet.
pub fn add_ruckus_ssid(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_SSID_TYPE, value));
}
/// Lookup a `ruckus_ssid` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_ssid`, it returns `None`.
pub fn lookup_ruckus_ssid(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(RUCKUS_SSID_TYPE).map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_ssid` string value from a packet.
pub fn lookup_all_ruckus_ssid(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SSID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_WLAN_ID_TYPE: AVPType = 4;
/// Delete all of `ruckus_wlan_id` values from a packet.
pub fn delete_ruckus_wlan_id(packet: &mut Packet) {
    packet.delete(RUCKUS_WLAN_ID_TYPE);
}
/// Add `ruckus_wlan_id` integer value to a packet.
pub fn add_ruckus_wlan_id(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_WLAN_ID_TYPE, value));
}
/// Lookup a `ruckus_wlan_id` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_wlan_id`, it returns `None`.
pub fn lookup_ruckus_wlan_id(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet.lookup(RUCKUS_WLAN_ID_TYPE).map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_wlan_id` integer value from a packet.
pub fn lookup_all_ruckus_wlan_id(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_WLAN_ID_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_LOCATION_TYPE: AVPType = 5;
/// Delete all of `ruckus_location` values from a packet.
pub fn delete_ruckus_location(packet: &mut Packet) {
    packet.delete(RUCKUS_LOCATION_TYPE);
}
/// Add `ruckus_location` string value to a packet.
pub fn add_ruckus_location(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_LOCATION_TYPE, value));
}
/// Lookup a `ruckus_location` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_location`, it returns `None`.
pub fn lookup_ruckus_location(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_LOCATION_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_location` string value from a packet.
pub fn lookup_all_ruckus_location(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_LOCATION_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_GRACE_PERIOD_TYPE: AVPType = 6;
/// Delete all of `ruckus_grace_period` values from a packet.
pub fn delete_ruckus_grace_period(packet: &mut Packet) {
    packet.delete(RUCKUS_GRACE_PERIOD_TYPE);
}
/// Add `ruckus_grace_period` integer value to a packet.
pub fn add_ruckus_grace_period(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_GRACE_PERIOD_TYPE, value));
}
/// Lookup a `ruckus_grace_period` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_grace_period`, it returns `None`.
pub fn lookup_ruckus_grace_period(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_GRACE_PERIOD_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_grace_period` integer value from a packet.
pub fn lookup_all_ruckus_grace_period(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_GRACE_PERIOD_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_SCG_C_BLADE_IP_TYPE: AVPType = 7;
/// Delete all of `ruckus_scg_c_blade_ip` values from a packet.
pub fn delete_ruckus_scg_c_blade_ip(packet: &mut Packet) {
    packet.delete(RUCKUS_SCG_C_BLADE_IP_TYPE);
}
/// Add `ruckus_scg_c_blade_ip` integer value to a packet.
pub fn add_ruckus_scg_c_blade_ip(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_SCG_C_BLADE_IP_TYPE, value));
}
/// Lookup a `ruckus_scg_c_blade_ip` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_scg_c_blade_ip`, it returns `None`.
pub fn lookup_ruckus_scg_c_blade_ip(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_SCG_C_BLADE_IP_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_scg_c_blade_ip` integer value from a packet.
pub fn lookup_all_ruckus_scg_c_blade_ip(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SCG_C_BLADE_IP_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_SCG_D_BLADE_IP_TYPE: AVPType = 8;
/// Delete all of `ruckus_scg_d_blade_ip` values from a packet.
pub fn delete_ruckus_scg_d_blade_ip(packet: &mut Packet) {
    packet.delete(RUCKUS_SCG_D_BLADE_IP_TYPE);
}
/// Add `ruckus_scg_d_blade_ip` integer value to a packet.
pub fn add_ruckus_scg_d_blade_ip(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_SCG_D_BLADE_IP_TYPE, value));
}
/// Lookup a `ruckus_scg_d_blade_ip` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_scg_d_blade_ip`, it returns `None`.
pub fn lookup_ruckus_scg_d_blade_ip(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_SCG_D_BLADE_IP_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_scg_d_blade_ip` integer value from a packet.
pub fn lookup_all_ruckus_scg_d_blade_ip(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SCG_D_BLADE_IP_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_VLAN_ID_TYPE: AVPType = 9;
/// Delete all of `ruckus_vlan_id` values from a packet.
pub fn delete_ruckus_vlan_id(packet: &mut Packet) {
    packet.delete(RUCKUS_VLAN_ID_TYPE);
}
/// Add `ruckus_vlan_id` integer value to a packet.
pub fn add_ruckus_vlan_id(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_VLAN_ID_TYPE, value));
}
/// Lookup a `ruckus_vlan_id` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_vlan_id`, it returns `None`.
pub fn lookup_ruckus_vlan_id(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet.lookup(RUCKUS_VLAN_ID_TYPE).map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_vlan_id` integer value from a packet.
pub fn lookup_all_ruckus_vlan_id(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_VLAN_ID_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_STA_EXPIRATION_TYPE: AVPType = 10;
/// Delete all of `ruckus_sta_expiration` values from a packet.
pub fn delete_ruckus_sta_expiration(packet: &mut Packet) {
    packet.delete(RUCKUS_STA_EXPIRATION_TYPE);
}
/// Add `ruckus_sta_expiration` integer value to a packet.
pub fn add_ruckus_sta_expiration(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_STA_EXPIRATION_TYPE, value));
}
/// Lookup a `ruckus_sta_expiration` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sta_expiration`, it returns `None`.
pub fn lookup_ruckus_sta_expiration(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_STA_EXPIRATION_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_sta_expiration` integer value from a packet.
pub fn lookup_all_ruckus_sta_expiration(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_STA_EXPIRATION_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_STA_UUID_TYPE: AVPType = 11;
/// Delete all of `ruckus_sta_uuid` values from a packet.
pub fn delete_ruckus_sta_uuid(packet: &mut Packet) {
    packet.delete(RUCKUS_STA_UUID_TYPE);
}
/// Add `ruckus_sta_uuid` string value to a packet.
pub fn add_ruckus_sta_uuid(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_STA_UUID_TYPE, value));
}
/// Lookup a `ruckus_sta_uuid` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sta_uuid`, it returns `None`.
pub fn lookup_ruckus_sta_uuid(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_STA_UUID_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_sta_uuid` string value from a packet.
pub fn lookup_all_ruckus_sta_uuid(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_STA_UUID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_ACCEPT_ENHANCEMENT_REASON_TYPE: AVPType = 12;
/// Delete all of `ruckus_accept_enhancement_reason` values from a packet.
pub fn delete_ruckus_accept_enhancement_reason(packet: &mut Packet) {
    packet.delete(RUCKUS_ACCEPT_ENHANCEMENT_REASON_TYPE);
}
/// Add `ruckus_accept_enhancement_reason` integer value to a packet.
pub fn add_ruckus_accept_enhancement_reason(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_ACCEPT_ENHANCEMENT_REASON_TYPE, value));
}
/// Lookup a `ruckus_accept_enhancement_reason` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_accept_enhancement_reason`, it returns `None`.
pub fn lookup_ruckus_accept_enhancement_reason(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_ACCEPT_ENHANCEMENT_REASON_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_accept_enhancement_reason` integer value from a packet.
pub fn lookup_all_ruckus_accept_enhancement_reason(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_ACCEPT_ENHANCEMENT_REASON_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_STA_INNER_ID_TYPE: AVPType = 13;
/// Delete all of `ruckus_sta_inner_id` values from a packet.
pub fn delete_ruckus_sta_inner_id(packet: &mut Packet) {
    packet.delete(RUCKUS_STA_INNER_ID_TYPE);
}
/// Add `ruckus_sta_inner_id` string value to a packet.
pub fn add_ruckus_sta_inner_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_STA_INNER_ID_TYPE, value));
}
/// Lookup a `ruckus_sta_inner_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sta_inner_id`, it returns `None`.
pub fn lookup_ruckus_sta_inner_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_STA_INNER_ID_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_sta_inner_id` string value from a packet.
pub fn lookup_all_ruckus_sta_inner_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_STA_INNER_ID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_BSSID_TYPE: AVPType = 14;
/// Delete all of `ruckus_bssid` values from a packet.
pub fn delete_ruckus_bssid(packet: &mut Packet) {
    packet.delete(RUCKUS_BSSID_TYPE);
}
/// Add `ruckus_bssid` octets value to a packet.
pub fn add_ruckus_bssid(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_BSSID_TYPE, value));
}
/// Lookup a `ruckus_bssid` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_bssid`, it returns `None`.
pub fn lookup_ruckus_bssid(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(RUCKUS_BSSID_TYPE).map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_bssid` octets value from a packet.
pub fn lookup_all_ruckus_bssid(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_BSSID_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_FLEX_AUTH_AVP_TYPE: AVPType = 20;
/// Delete all of `ruckus_flex_auth_avp` values from a packet.
pub fn delete_ruckus_flex_auth_avp(packet: &mut Packet) {
    packet.delete(RUCKUS_FLEX_AUTH_AVP_TYPE);
}
/// Add `ruckus_flex_auth_avp` string value to a packet.
pub fn add_ruckus_flex_auth_avp(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_FLEX_AUTH_AVP_TYPE, value));
}
/// Lookup a `ruckus_flex_auth_avp` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_flex_auth_avp`, it returns `None`.
pub fn lookup_ruckus_flex_auth_avp(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_FLEX_AUTH_AVP_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_flex_auth_avp` string value from a packet.
pub fn lookup_all_ruckus_flex_auth_avp(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_FLEX_AUTH_AVP_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_TRIPLETS_TYPE: AVPType = 101;
/// Delete all of `ruckus_triplets` values from a packet.
pub fn delete_ruckus_triplets(packet: &mut Packet) {
    packet.delete(RUCKUS_TRIPLETS_TYPE);
}
/// Add `ruckus_triplets` octets value to a packet.
pub fn add_ruckus_triplets(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_TRIPLETS_TYPE, value));
}
/// Lookup a `ruckus_triplets` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_triplets`, it returns `None`.
pub fn lookup_ruckus_triplets(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_TRIPLETS_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_triplets` octets value from a packet.
pub fn lookup_all_ruckus_triplets(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_TRIPLETS_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_IMSI_TYPE: AVPType = 102;
/// Delete all of `ruckus_imsi` values from a packet.
pub fn delete_ruckus_imsi(packet: &mut Packet) {
    packet.delete(RUCKUS_IMSI_TYPE);
}
/// Add `ruckus_imsi` octets value to a packet.
pub fn add_ruckus_imsi(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_IMSI_TYPE, value));
}
/// Lookup a `ruckus_imsi` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_imsi`, it returns `None`.
pub fn lookup_ruckus_imsi(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(RUCKUS_IMSI_TYPE).map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_imsi` octets value from a packet.
pub fn lookup_all_ruckus_imsi(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_IMSI_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_MSISDN_TYPE: AVPType = 103;
/// Delete all of `ruckus_msisdn` values from a packet.
pub fn delete_ruckus_msisdn(packet: &mut Packet) {
    packet.delete(RUCKUS_MSISDN_TYPE);
}
/// Add `ruckus_msisdn` octets value to a packet.
pub fn add_ruckus_msisdn(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_MSISDN_TYPE, value));
}
/// Lookup a `ruckus_msisdn` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_msisdn`, it returns `None`.
pub fn lookup_ruckus_msisdn(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(RUCKUS_MSISDN_TYPE).map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_msisdn` octets value from a packet.
pub fn lookup_all_ruckus_msisdn(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_MSISDN_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_APN_NI_TYPE: AVPType = 104;
/// Delete all of `ruckus_apn_ni` values from a packet.
pub fn delete_ruckus_apn_ni(packet: &mut Packet) {
    packet.delete(RUCKUS_APN_NI_TYPE);
}
/// Add `ruckus_apn_ni` string value to a packet.
pub fn add_ruckus_apn_ni(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_APN_NI_TYPE, value));
}
/// Lookup a `ruckus_apn_ni` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_apn_ni`, it returns `None`.
pub fn lookup_ruckus_apn_ni(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(RUCKUS_APN_NI_TYPE).map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_apn_ni` string value from a packet.
pub fn lookup_all_ruckus_apn_ni(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_APN_NI_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_QO_S_TYPE: AVPType = 105;
/// Delete all of `ruckus_qo_s` values from a packet.
pub fn delete_ruckus_qo_s(packet: &mut Packet) {
    packet.delete(RUCKUS_QO_S_TYPE);
}
/// Add `ruckus_qo_s` octets value to a packet.
pub fn add_ruckus_qo_s(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_QO_S_TYPE, value));
}
/// Lookup a `ruckus_qo_s` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_qo_s`, it returns `None`.
pub fn lookup_ruckus_qo_s(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(RUCKUS_QO_S_TYPE).map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_qo_s` octets value from a packet.
pub fn lookup_all_ruckus_qo_s(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_QO_S_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_SELECTION_MODE_TYPE: AVPType = 106;
/// Delete all of `ruckus_selection_mode` values from a packet.
pub fn delete_ruckus_selection_mode(packet: &mut Packet) {
    packet.delete(RUCKUS_SELECTION_MODE_TYPE);
}
/// Add `ruckus_selection_mode` value-defined integer value to a packet.
pub fn add_ruckus_selection_mode(packet: &mut Packet, value: RuckusSelectionMode) {
    packet.add(AVP::from_u32(RUCKUS_SELECTION_MODE_TYPE, value));
}
/// Lookup a `ruckus_selection_mode` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_selection_mode`, it returns `None`.
pub fn lookup_ruckus_selection_mode(
    packet: &Packet,
) -> Option<Result<RuckusSelectionMode, AVPError>> {
    packet
        .lookup(RUCKUS_SELECTION_MODE_TYPE)
        .map(|v| Ok(v.encode_u32()? as RuckusSelectionMode))
}
/// Lookup all of the `ruckus_selection_mode` value-defined integer value from a packet.
pub fn lookup_all_ruckus_selection_mode(
    packet: &Packet,
) -> Result<Vec<RuckusSelectionMode>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SELECTION_MODE_TYPE) {
        vec.push(avp.encode_u32()? as RuckusSelectionMode)
    }
    Ok(vec)
}

pub const RUCKUS_APN_RESOLUTION_REQ_TYPE: AVPType = 107;
/// Delete all of `ruckus_apn_resolution_req` values from a packet.
pub fn delete_ruckus_apn_resolution_req(packet: &mut Packet) {
    packet.delete(RUCKUS_APN_RESOLUTION_REQ_TYPE);
}
/// Add `ruckus_apn_resolution_req` value-defined integer value to a packet.
pub fn add_ruckus_apn_resolution_req(packet: &mut Packet, value: RuckusAPNResolutionReq) {
    packet.add(AVP::from_u32(RUCKUS_APN_RESOLUTION_REQ_TYPE, value));
}
/// Lookup a `ruckus_apn_resolution_req` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_apn_resolution_req`, it returns `None`.
pub fn lookup_ruckus_apn_resolution_req(
    packet: &Packet,
) -> Option<Result<RuckusAPNResolutionReq, AVPError>> {
    packet
        .lookup(RUCKUS_APN_RESOLUTION_REQ_TYPE)
        .map(|v| Ok(v.encode_u32()? as RuckusAPNResolutionReq))
}
/// Lookup all of the `ruckus_apn_resolution_req` value-defined integer value from a packet.
pub fn lookup_all_ruckus_apn_resolution_req(
    packet: &Packet,
) -> Result<Vec<RuckusAPNResolutionReq>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_APN_RESOLUTION_REQ_TYPE) {
        vec.push(avp.encode_u32()? as RuckusAPNResolutionReq)
    }
    Ok(vec)
}

pub const RUCKUS_START_TIME_TYPE: AVPType = 108;
/// Delete all of `ruckus_start_time` values from a packet.
pub fn delete_ruckus_start_time(packet: &mut Packet) {
    packet.delete(RUCKUS_START_TIME_TYPE);
}
/// Add `ruckus_start_time` octets value to a packet.
pub fn add_ruckus_start_time(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_START_TIME_TYPE, value));
}
/// Lookup a `ruckus_start_time` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_start_time`, it returns `None`.
pub fn lookup_ruckus_start_time(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_START_TIME_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_start_time` octets value from a packet.
pub fn lookup_all_ruckus_start_time(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_START_TIME_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_NAS_TYPE_TYPE: AVPType = 109;
/// Delete all of `ruckus_nas_type` values from a packet.
pub fn delete_ruckus_nas_type(packet: &mut Packet) {
    packet.delete(RUCKUS_NAS_TYPE_TYPE);
}
/// Add `ruckus_nas_type` value-defined integer value to a packet.
pub fn add_ruckus_nas_type(packet: &mut Packet, value: RuckusNASType) {
    packet.add(AVP::from_u32(RUCKUS_NAS_TYPE_TYPE, value));
}
/// Lookup a `ruckus_nas_type` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_nas_type`, it returns `None`.
pub fn lookup_ruckus_nas_type(packet: &Packet) -> Option<Result<RuckusNASType, AVPError>> {
    packet
        .lookup(RUCKUS_NAS_TYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as RuckusNASType))
}
/// Lookup all of the `ruckus_nas_type` value-defined integer value from a packet.
pub fn lookup_all_ruckus_nas_type(packet: &Packet) -> Result<Vec<RuckusNASType>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_NAS_TYPE_TYPE) {
        vec.push(avp.encode_u32()? as RuckusNASType)
    }
    Ok(vec)
}

pub const RUCKUS_STATUS_TYPE: AVPType = 110;
/// Delete all of `ruckus_status` values from a packet.
pub fn delete_ruckus_status(packet: &mut Packet) {
    packet.delete(RUCKUS_STATUS_TYPE);
}
/// Add `ruckus_status` value-defined integer value to a packet.
pub fn add_ruckus_status(packet: &mut Packet, value: RuckusStatus) {
    packet.add(AVP::from_u32(RUCKUS_STATUS_TYPE, value));
}
/// Lookup a `ruckus_status` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_status`, it returns `None`.
pub fn lookup_ruckus_status(packet: &Packet) -> Option<Result<RuckusStatus, AVPError>> {
    packet
        .lookup(RUCKUS_STATUS_TYPE)
        .map(|v| Ok(v.encode_u32()? as RuckusStatus))
}
/// Lookup all of the `ruckus_status` value-defined integer value from a packet.
pub fn lookup_all_ruckus_status(packet: &Packet) -> Result<Vec<RuckusStatus>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_STATUS_TYPE) {
        vec.push(avp.encode_u32()? as RuckusStatus)
    }
    Ok(vec)
}

pub const RUCKUS_APN_OI_TYPE: AVPType = 111;
/// Delete all of `ruckus_apn_oi` values from a packet.
pub fn delete_ruckus_apn_oi(packet: &mut Packet) {
    packet.delete(RUCKUS_APN_OI_TYPE);
}
/// Add `ruckus_apn_oi` string value to a packet.
pub fn add_ruckus_apn_oi(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_APN_OI_TYPE, value));
}
/// Lookup a `ruckus_apn_oi` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_apn_oi`, it returns `None`.
pub fn lookup_ruckus_apn_oi(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(RUCKUS_APN_OI_TYPE).map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_apn_oi` string value from a packet.
pub fn lookup_all_ruckus_apn_oi(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_APN_OI_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_AUTH_TYPE_TYPE: AVPType = 112;
/// Delete all of `ruckus_auth_type` values from a packet.
pub fn delete_ruckus_auth_type(packet: &mut Packet) {
    packet.delete(RUCKUS_AUTH_TYPE_TYPE);
}
/// Add `ruckus_auth_type` value-defined integer value to a packet.
pub fn add_ruckus_auth_type(packet: &mut Packet, value: RuckusAuthType) {
    packet.add(AVP::from_u32(RUCKUS_AUTH_TYPE_TYPE, value));
}
/// Lookup a `ruckus_auth_type` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_auth_type`, it returns `None`.
pub fn lookup_ruckus_auth_type(packet: &Packet) -> Option<Result<RuckusAuthType, AVPError>> {
    packet
        .lookup(RUCKUS_AUTH_TYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as RuckusAuthType))
}
/// Lookup all of the `ruckus_auth_type` value-defined integer value from a packet.
pub fn lookup_all_ruckus_auth_type(packet: &Packet) -> Result<Vec<RuckusAuthType>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_AUTH_TYPE_TYPE) {
        vec.push(avp.encode_u32()? as RuckusAuthType)
    }
    Ok(vec)
}

pub const RUCKUS_GN_USER_NAME_TYPE: AVPType = 113;
/// Delete all of `ruckus_gn_user_name` values from a packet.
pub fn delete_ruckus_gn_user_name(packet: &mut Packet) {
    packet.delete(RUCKUS_GN_USER_NAME_TYPE);
}
/// Add `ruckus_gn_user_name` string value to a packet.
pub fn add_ruckus_gn_user_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_GN_USER_NAME_TYPE, value));
}
/// Lookup a `ruckus_gn_user_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_gn_user_name`, it returns `None`.
pub fn lookup_ruckus_gn_user_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_GN_USER_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_gn_user_name` string value from a packet.
pub fn lookup_all_ruckus_gn_user_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_GN_USER_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_BRAND_CODE_TYPE: AVPType = 114;
/// Delete all of `ruckus_brand_code` values from a packet.
pub fn delete_ruckus_brand_code(packet: &mut Packet) {
    packet.delete(RUCKUS_BRAND_CODE_TYPE);
}
/// Add `ruckus_brand_code` string value to a packet.
pub fn add_ruckus_brand_code(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_BRAND_CODE_TYPE, value));
}
/// Lookup a `ruckus_brand_code` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_brand_code`, it returns `None`.
pub fn lookup_ruckus_brand_code(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_BRAND_CODE_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_brand_code` string value from a packet.
pub fn lookup_all_ruckus_brand_code(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_BRAND_CODE_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_POLICY_NAME_TYPE: AVPType = 115;
/// Delete all of `ruckus_policy_name` values from a packet.
pub fn delete_ruckus_policy_name(packet: &mut Packet) {
    packet.delete(RUCKUS_POLICY_NAME_TYPE);
}
/// Add `ruckus_policy_name` string value to a packet.
pub fn add_ruckus_policy_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_POLICY_NAME_TYPE, value));
}
/// Lookup a `ruckus_policy_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_policy_name`, it returns `None`.
pub fn lookup_ruckus_policy_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_POLICY_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_policy_name` string value from a packet.
pub fn lookup_all_ruckus_policy_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_POLICY_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_CLIENT_LOCAL_IP_TYPE: AVPType = 116;
/// Delete all of `ruckus_client_local_ip` values from a packet.
pub fn delete_ruckus_client_local_ip(packet: &mut Packet) {
    packet.delete(RUCKUS_CLIENT_LOCAL_IP_TYPE);
}
/// Add `ruckus_client_local_ip` ipaddr value to a packet.
pub fn add_ruckus_client_local_ip(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(RUCKUS_CLIENT_LOCAL_IP_TYPE, value));
}
/// Lookup a `ruckus_client_local_ip` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_client_local_ip`, it returns `None`.
pub fn lookup_ruckus_client_local_ip(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet
        .lookup(RUCKUS_CLIENT_LOCAL_IP_TYPE)
        .map(|v| v.encode_ipv4())
}
/// Lookup all of the `ruckus_client_local_ip` ipaddr value from a packet.
pub fn lookup_all_ruckus_client_local_ip(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CLIENT_LOCAL_IP_TYPE) {
        vec.push(avp.encode_ipv4()?)
    }
    Ok(vec)
}

pub const RUCKUS_SGSN_IP_TYPE: AVPType = 117;
/// Delete all of `ruckus_sgsn_ip` values from a packet.
pub fn delete_ruckus_sgsn_ip(packet: &mut Packet) {
    packet.delete(RUCKUS_SGSN_IP_TYPE);
}
/// Add `ruckus_sgsn_ip` ipaddr value to a packet.
pub fn add_ruckus_sgsn_ip(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(RUCKUS_SGSN_IP_TYPE, value));
}
/// Lookup a `ruckus_sgsn_ip` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sgsn_ip`, it returns `None`.
pub fn lookup_ruckus_sgsn_ip(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet.lookup(RUCKUS_SGSN_IP_TYPE).map(|v| v.encode_ipv4())
}
/// Lookup all of the `ruckus_sgsn_ip` ipaddr value from a packet.
pub fn lookup_all_ruckus_sgsn_ip(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SGSN_IP_TYPE) {
        vec.push(avp.encode_ipv4()?)
    }
    Ok(vec)
}

pub const RUCKUS_CHARGING_CHARAC_TYPE: AVPType = 118;
/// Delete all of `ruckus_charging_charac` values from a packet.
pub fn delete_ruckus_charging_charac(packet: &mut Packet) {
    packet.delete(RUCKUS_CHARGING_CHARAC_TYPE);
}
/// Add `ruckus_charging_charac` octets value to a packet.
pub fn add_ruckus_charging_charac(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_CHARGING_CHARAC_TYPE, value));
}
/// Lookup a `ruckus_charging_charac` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_charging_charac`, it returns `None`.
pub fn lookup_ruckus_charging_charac(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_CHARGING_CHARAC_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_charging_charac` octets value from a packet.
pub fn lookup_all_ruckus_charging_charac(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CHARGING_CHARAC_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_PDP_TYPE_TYPE: AVPType = 119;
/// Delete all of `ruckus_pdp_type` values from a packet.
pub fn delete_ruckus_pdp_type(packet: &mut Packet) {
    packet.delete(RUCKUS_PDP_TYPE_TYPE);
}
/// Add `ruckus_pdp_type` octets value to a packet.
pub fn add_ruckus_pdp_type(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_PDP_TYPE_TYPE, value));
}
/// Lookup a `ruckus_pdp_type` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_pdp_type`, it returns `None`.
pub fn lookup_ruckus_pdp_type(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_PDP_TYPE_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_pdp_type` octets value from a packet.
pub fn lookup_all_ruckus_pdp_type(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_PDP_TYPE_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_DYNAMIC_ADDRESS_FLAG_TYPE: AVPType = 120;
/// Delete all of `ruckus_dynamic_address_flag` values from a packet.
pub fn delete_ruckus_dynamic_address_flag(packet: &mut Packet) {
    packet.delete(RUCKUS_DYNAMIC_ADDRESS_FLAG_TYPE);
}
/// Add `ruckus_dynamic_address_flag` octets value to a packet.
pub fn add_ruckus_dynamic_address_flag(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_DYNAMIC_ADDRESS_FLAG_TYPE, value));
}
/// Lookup a `ruckus_dynamic_address_flag` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_dynamic_address_flag`, it returns `None`.
pub fn lookup_ruckus_dynamic_address_flag(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_DYNAMIC_ADDRESS_FLAG_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_dynamic_address_flag` octets value from a packet.
pub fn lookup_all_ruckus_dynamic_address_flag(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_DYNAMIC_ADDRESS_FLAG_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_CH_CH_SELECTION_MODE_TYPE: AVPType = 121;
/// Delete all of `ruckus_ch_ch_selection_mode` values from a packet.
pub fn delete_ruckus_ch_ch_selection_mode(packet: &mut Packet) {
    packet.delete(RUCKUS_CH_CH_SELECTION_MODE_TYPE);
}
/// Add `ruckus_ch_ch_selection_mode` octets value to a packet.
pub fn add_ruckus_ch_ch_selection_mode(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_CH_CH_SELECTION_MODE_TYPE, value));
}
/// Lookup a `ruckus_ch_ch_selection_mode` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_ch_ch_selection_mode`, it returns `None`.
pub fn lookup_ruckus_ch_ch_selection_mode(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_CH_CH_SELECTION_MODE_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_ch_ch_selection_mode` octets value from a packet.
pub fn lookup_all_ruckus_ch_ch_selection_mode(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CH_CH_SELECTION_MODE_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_AAA_IP_TYPE: AVPType = 122;
/// Delete all of `ruckus_aaa_ip` values from a packet.
pub fn delete_ruckus_aaa_ip(packet: &mut Packet) {
    packet.delete(RUCKUS_AAA_IP_TYPE);
}
/// Add `ruckus_aaa_ip` ipaddr value to a packet.
pub fn add_ruckus_aaa_ip(packet: &mut Packet, value: &Ipv4Addr) {
    packet.add(AVP::from_ipv4(RUCKUS_AAA_IP_TYPE, value));
}
/// Lookup a `ruckus_aaa_ip` ipaddr value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_aaa_ip`, it returns `None`.
pub fn lookup_ruckus_aaa_ip(packet: &Packet) -> Option<Result<Ipv4Addr, AVPError>> {
    packet.lookup(RUCKUS_AAA_IP_TYPE).map(|v| v.encode_ipv4())
}
/// Lookup all of the `ruckus_aaa_ip` ipaddr value from a packet.
pub fn lookup_all_ruckus_aaa_ip(packet: &Packet) -> Result<Vec<Ipv4Addr>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_AAA_IP_TYPE) {
        vec.push(avp.encode_ipv4()?)
    }
    Ok(vec)
}

pub const RUCKUS_CDR_TYPE_TYPE: AVPType = 123;
/// Delete all of `ruckus_cdr_type` values from a packet.
pub fn delete_ruckus_cdr_type(packet: &mut Packet) {
    packet.delete(RUCKUS_CDR_TYPE_TYPE);
}
/// Add `ruckus_cdr_type` integer value to a packet.
pub fn add_ruckus_cdr_type(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_CDR_TYPE_TYPE, value));
}
/// Lookup a `ruckus_cdr_type` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_cdr_type`, it returns `None`.
pub fn lookup_ruckus_cdr_type(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet.lookup(RUCKUS_CDR_TYPE_TYPE).map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_cdr_type` integer value from a packet.
pub fn lookup_all_ruckus_cdr_type(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CDR_TYPE_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_SGSN_NUMBER_TYPE: AVPType = 124;
/// Delete all of `ruckus_sgsn_number` values from a packet.
pub fn delete_ruckus_sgsn_number(packet: &mut Packet) {
    packet.delete(RUCKUS_SGSN_NUMBER_TYPE);
}
/// Add `ruckus_sgsn_number` octets value to a packet.
pub fn add_ruckus_sgsn_number(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_SGSN_NUMBER_TYPE, value));
}
/// Lookup a `ruckus_sgsn_number` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sgsn_number`, it returns `None`.
pub fn lookup_ruckus_sgsn_number(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_SGSN_NUMBER_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_sgsn_number` octets value from a packet.
pub fn lookup_all_ruckus_sgsn_number(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SGSN_NUMBER_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_SESSION_TYPE_TYPE: AVPType = 125;
/// Delete all of `ruckus_session_type` values from a packet.
pub fn delete_ruckus_session_type(packet: &mut Packet) {
    packet.delete(RUCKUS_SESSION_TYPE_TYPE);
}
/// Add `ruckus_session_type` value-defined integer value to a packet.
pub fn add_ruckus_session_type(packet: &mut Packet, value: RuckusSessionType) {
    packet.add(AVP::from_u32(RUCKUS_SESSION_TYPE_TYPE, value));
}
/// Lookup a `ruckus_session_type` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_session_type`, it returns `None`.
pub fn lookup_ruckus_session_type(packet: &Packet) -> Option<Result<RuckusSessionType, AVPError>> {
    packet
        .lookup(RUCKUS_SESSION_TYPE_TYPE)
        .map(|v| Ok(v.encode_u32()? as RuckusSessionType))
}
/// Lookup all of the `ruckus_session_type` value-defined integer value from a packet.
pub fn lookup_all_ruckus_session_type(packet: &Packet) -> Result<Vec<RuckusSessionType>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SESSION_TYPE_TYPE) {
        vec.push(avp.encode_u32()? as RuckusSessionType)
    }
    Ok(vec)
}

pub const RUCKUS_ACCOUNTING_STATUS_TYPE: AVPType = 126;
/// Delete all of `ruckus_accounting_status` values from a packet.
pub fn delete_ruckus_accounting_status(packet: &mut Packet) {
    packet.delete(RUCKUS_ACCOUNTING_STATUS_TYPE);
}
/// Add `ruckus_accounting_status` value-defined integer value to a packet.
pub fn add_ruckus_accounting_status(packet: &mut Packet, value: RuckusAccountingStatus) {
    packet.add(AVP::from_u32(RUCKUS_ACCOUNTING_STATUS_TYPE, value));
}
/// Lookup a `ruckus_accounting_status` value-defined integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_accounting_status`, it returns `None`.
pub fn lookup_ruckus_accounting_status(
    packet: &Packet,
) -> Option<Result<RuckusAccountingStatus, AVPError>> {
    packet
        .lookup(RUCKUS_ACCOUNTING_STATUS_TYPE)
        .map(|v| Ok(v.encode_u32()? as RuckusAccountingStatus))
}
/// Lookup all of the `ruckus_accounting_status` value-defined integer value from a packet.
pub fn lookup_all_ruckus_accounting_status(
    packet: &Packet,
) -> Result<Vec<RuckusAccountingStatus>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_ACCOUNTING_STATUS_TYPE) {
        vec.push(avp.encode_u32()? as RuckusAccountingStatus)
    }
    Ok(vec)
}

pub const RUCKUS_ZONE_ID_TYPE: AVPType = 127;
/// Delete all of `ruckus_zone_id` values from a packet.
pub fn delete_ruckus_zone_id(packet: &mut Packet) {
    packet.delete(RUCKUS_ZONE_ID_TYPE);
}
/// Add `ruckus_zone_id` string value to a packet.
pub fn add_ruckus_zone_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_ZONE_ID_TYPE, value));
}
/// Lookup a `ruckus_zone_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_zone_id`, it returns `None`.
pub fn lookup_ruckus_zone_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_ZONE_ID_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_zone_id` string value from a packet.
pub fn lookup_all_ruckus_zone_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_ZONE_ID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_AUTH_SERVER_ID_TYPE: AVPType = 128;
/// Delete all of `ruckus_auth_server_id` values from a packet.
pub fn delete_ruckus_auth_server_id(packet: &mut Packet) {
    packet.delete(RUCKUS_AUTH_SERVER_ID_TYPE);
}
/// Add `ruckus_auth_server_id` string value to a packet.
pub fn add_ruckus_auth_server_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_AUTH_SERVER_ID_TYPE, value));
}
/// Lookup a `ruckus_auth_server_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_auth_server_id`, it returns `None`.
pub fn lookup_ruckus_auth_server_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_AUTH_SERVER_ID_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_auth_server_id` string value from a packet.
pub fn lookup_all_ruckus_auth_server_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_AUTH_SERVER_ID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_UTP_ID_TYPE: AVPType = 129;
/// Delete all of `ruckus_utp_id` values from a packet.
pub fn delete_ruckus_utp_id(packet: &mut Packet) {
    packet.delete(RUCKUS_UTP_ID_TYPE);
}
/// Add `ruckus_utp_id` string value to a packet.
pub fn add_ruckus_utp_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_UTP_ID_TYPE, value));
}
/// Lookup a `ruckus_utp_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_utp_id`, it returns `None`.
pub fn lookup_ruckus_utp_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(RUCKUS_UTP_ID_TYPE).map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_utp_id` string value from a packet.
pub fn lookup_all_ruckus_utp_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_UTP_ID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_AREA_CODE_TYPE: AVPType = 130;
/// Delete all of `ruckus_area_code` values from a packet.
pub fn delete_ruckus_area_code(packet: &mut Packet) {
    packet.delete(RUCKUS_AREA_CODE_TYPE);
}
/// Add `ruckus_area_code` octets value to a packet.
pub fn add_ruckus_area_code(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_AREA_CODE_TYPE, value));
}
/// Lookup a `ruckus_area_code` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_area_code`, it returns `None`.
pub fn lookup_ruckus_area_code(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_AREA_CODE_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_area_code` octets value from a packet.
pub fn lookup_all_ruckus_area_code(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_AREA_CODE_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_CELL_IDENTIFIER_TYPE: AVPType = 131;
/// Delete all of `ruckus_cell_identifier` values from a packet.
pub fn delete_ruckus_cell_identifier(packet: &mut Packet) {
    packet.delete(RUCKUS_CELL_IDENTIFIER_TYPE);
}
/// Add `ruckus_cell_identifier` octets value to a packet.
pub fn add_ruckus_cell_identifier(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_CELL_IDENTIFIER_TYPE, value));
}
/// Lookup a `ruckus_cell_identifier` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_cell_identifier`, it returns `None`.
pub fn lookup_ruckus_cell_identifier(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_CELL_IDENTIFIER_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_cell_identifier` octets value from a packet.
pub fn lookup_all_ruckus_cell_identifier(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CELL_IDENTIFIER_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_WISPR_REDIRECT_POLICY_TYPE: AVPType = 132;
/// Delete all of `ruckus_wispr_redirect_policy` values from a packet.
pub fn delete_ruckus_wispr_redirect_policy(packet: &mut Packet) {
    packet.delete(RUCKUS_WISPR_REDIRECT_POLICY_TYPE);
}
/// Add `ruckus_wispr_redirect_policy` string value to a packet.
pub fn add_ruckus_wispr_redirect_policy(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_WISPR_REDIRECT_POLICY_TYPE, value));
}
/// Lookup a `ruckus_wispr_redirect_policy` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_wispr_redirect_policy`, it returns `None`.
pub fn lookup_ruckus_wispr_redirect_policy(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_WISPR_REDIRECT_POLICY_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_wispr_redirect_policy` string value from a packet.
pub fn lookup_all_ruckus_wispr_redirect_policy(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_WISPR_REDIRECT_POLICY_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_ETH_PROFILE_ID_TYPE: AVPType = 133;
/// Delete all of `ruckus_eth_profile_id` values from a packet.
pub fn delete_ruckus_eth_profile_id(packet: &mut Packet) {
    packet.delete(RUCKUS_ETH_PROFILE_ID_TYPE);
}
/// Add `ruckus_eth_profile_id` integer value to a packet.
pub fn add_ruckus_eth_profile_id(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_ETH_PROFILE_ID_TYPE, value));
}
/// Lookup a `ruckus_eth_profile_id` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_eth_profile_id`, it returns `None`.
pub fn lookup_ruckus_eth_profile_id(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_ETH_PROFILE_ID_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_eth_profile_id` integer value from a packet.
pub fn lookup_all_ruckus_eth_profile_id(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_ETH_PROFILE_ID_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_ZONE_NAME_TYPE: AVPType = 134;
/// Delete all of `ruckus_zone_name` values from a packet.
pub fn delete_ruckus_zone_name(packet: &mut Packet) {
    packet.delete(RUCKUS_ZONE_NAME_TYPE);
}
/// Add `ruckus_zone_name` string value to a packet.
pub fn add_ruckus_zone_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_ZONE_NAME_TYPE, value));
}
/// Lookup a `ruckus_zone_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_zone_name`, it returns `None`.
pub fn lookup_ruckus_zone_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_ZONE_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_zone_name` string value from a packet.
pub fn lookup_all_ruckus_zone_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_ZONE_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_WLAN_NAME_TYPE: AVPType = 135;
/// Delete all of `ruckus_wlan_name` values from a packet.
pub fn delete_ruckus_wlan_name(packet: &mut Packet) {
    packet.delete(RUCKUS_WLAN_NAME_TYPE);
}
/// Add `ruckus_wlan_name` string value to a packet.
pub fn add_ruckus_wlan_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_WLAN_NAME_TYPE, value));
}
/// Lookup a `ruckus_wlan_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_wlan_name`, it returns `None`.
pub fn lookup_ruckus_wlan_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_WLAN_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_wlan_name` string value from a packet.
pub fn lookup_all_ruckus_wlan_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_WLAN_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_AP_ROAMED_TYPE: AVPType = 136;
/// Delete all of `ruckus_ap_roamed` values from a packet.
pub fn delete_ruckus_ap_roamed(packet: &mut Packet) {
    packet.delete(RUCKUS_AP_ROAMED_TYPE);
}
/// Add `ruckus_ap_roamed` integer value to a packet.
pub fn add_ruckus_ap_roamed(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_AP_ROAMED_TYPE, value));
}
/// Lookup a `ruckus_ap_roamed` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_ap_roamed`, it returns `None`.
pub fn lookup_ruckus_ap_roamed(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet.lookup(RUCKUS_AP_ROAMED_TYPE).map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_ap_roamed` integer value from a packet.
pub fn lookup_all_ruckus_ap_roamed(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_AP_ROAMED_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_READ_PREFERENCE_TYPE: AVPType = 137;
/// Delete all of `ruckus_read_preference` values from a packet.
pub fn delete_ruckus_read_preference(packet: &mut Packet) {
    packet.delete(RUCKUS_READ_PREFERENCE_TYPE);
}
/// Add `ruckus_read_preference` octets value to a packet.
pub fn add_ruckus_read_preference(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_READ_PREFERENCE_TYPE, value));
}
/// Lookup a `ruckus_read_preference` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_read_preference`, it returns `None`.
pub fn lookup_ruckus_read_preference(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_READ_PREFERENCE_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_read_preference` octets value from a packet.
pub fn lookup_all_ruckus_read_preference(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_READ_PREFERENCE_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_CLIENT_HOST_NAME_TYPE: AVPType = 138;
/// Delete all of `ruckus_client_host_name` values from a packet.
pub fn delete_ruckus_client_host_name(packet: &mut Packet) {
    packet.delete(RUCKUS_CLIENT_HOST_NAME_TYPE);
}
/// Add `ruckus_client_host_name` string value to a packet.
pub fn add_ruckus_client_host_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_CLIENT_HOST_NAME_TYPE, value));
}
/// Lookup a `ruckus_client_host_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_client_host_name`, it returns `None`.
pub fn lookup_ruckus_client_host_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_CLIENT_HOST_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_client_host_name` string value from a packet.
pub fn lookup_all_ruckus_client_host_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CLIENT_HOST_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_CLIENT_OS_TYPE_TYPE: AVPType = 139;
/// Delete all of `ruckus_client_os_type` values from a packet.
pub fn delete_ruckus_client_os_type(packet: &mut Packet) {
    packet.delete(RUCKUS_CLIENT_OS_TYPE_TYPE);
}
/// Add `ruckus_client_os_type` string value to a packet.
pub fn add_ruckus_client_os_type(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_CLIENT_OS_TYPE_TYPE, value));
}
/// Lookup a `ruckus_client_os_type` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_client_os_type`, it returns `None`.
pub fn lookup_ruckus_client_os_type(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_CLIENT_OS_TYPE_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_client_os_type` string value from a packet.
pub fn lookup_all_ruckus_client_os_type(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CLIENT_OS_TYPE_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_CLIENT_OS_CLASS_TYPE: AVPType = 140;
/// Delete all of `ruckus_client_os_class` values from a packet.
pub fn delete_ruckus_client_os_class(packet: &mut Packet) {
    packet.delete(RUCKUS_CLIENT_OS_CLASS_TYPE);
}
/// Add `ruckus_client_os_class` string value to a packet.
pub fn add_ruckus_client_os_class(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_CLIENT_OS_CLASS_TYPE, value));
}
/// Lookup a `ruckus_client_os_class` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_client_os_class`, it returns `None`.
pub fn lookup_ruckus_client_os_class(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_CLIENT_OS_CLASS_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_client_os_class` string value from a packet.
pub fn lookup_all_ruckus_client_os_class(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CLIENT_OS_CLASS_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_VLAN_POOL_TYPE: AVPType = 141;
/// Delete all of `ruckus_vlan_pool` values from a packet.
pub fn delete_ruckus_vlan_pool(packet: &mut Packet) {
    packet.delete(RUCKUS_VLAN_POOL_TYPE);
}
/// Add `ruckus_vlan_pool` string value to a packet.
pub fn add_ruckus_vlan_pool(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_VLAN_POOL_TYPE, value));
}
/// Lookup a `ruckus_vlan_pool` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_vlan_pool`, it returns `None`.
pub fn lookup_ruckus_vlan_pool(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_VLAN_POOL_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_vlan_pool` string value from a packet.
pub fn lookup_all_ruckus_vlan_pool(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_VLAN_POOL_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_DPSK_TYPE: AVPType = 142;
/// Delete all of `ruckus_dpsk` values from a packet.
pub fn delete_ruckus_dpsk(packet: &mut Packet) {
    packet.delete(RUCKUS_DPSK_TYPE);
}
/// Add `ruckus_dpsk` octets value to a packet.
pub fn add_ruckus_dpsk(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_DPSK_TYPE, value));
}
/// Lookup a `ruckus_dpsk` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_dpsk`, it returns `None`.
pub fn lookup_ruckus_dpsk(packet: &Packet) -> Option<Vec<u8>> {
    packet.lookup(RUCKUS_DPSK_TYPE).map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_dpsk` octets value from a packet.
pub fn lookup_all_ruckus_dpsk(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_DPSK_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_CP_TOKEN_TYPE: AVPType = 143;
/// Delete all of `ruckus_cp_token` values from a packet.
pub fn delete_ruckus_cp_token(packet: &mut Packet) {
    packet.delete(RUCKUS_CP_TOKEN_TYPE);
}
/// Add `ruckus_cp_token` string value to a packet.
pub fn add_ruckus_cp_token(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_CP_TOKEN_TYPE, value));
}
/// Lookup a `ruckus_cp_token` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_cp_token`, it returns `None`.
pub fn lookup_ruckus_cp_token(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_CP_TOKEN_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_cp_token` string value from a packet.
pub fn lookup_all_ruckus_cp_token(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CP_TOKEN_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_MAX_DL_UL_QUOTA_TYPE: AVPType = 144;
/// Delete all of `ruckus_max_dl_ul_quota` values from a packet.
pub fn delete_ruckus_max_dl_ul_quota(packet: &mut Packet) {
    packet.delete(RUCKUS_MAX_DL_UL_QUOTA_TYPE);
}
/// Add `ruckus_max_dl_ul_quota` integer value to a packet.
pub fn add_ruckus_max_dl_ul_quota(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_MAX_DL_UL_QUOTA_TYPE, value));
}
/// Lookup a `ruckus_max_dl_ul_quota` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_max_dl_ul_quota`, it returns `None`.
pub fn lookup_ruckus_max_dl_ul_quota(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_MAX_DL_UL_QUOTA_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_max_dl_ul_quota` integer value from a packet.
pub fn lookup_all_ruckus_max_dl_ul_quota(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_MAX_DL_UL_QUOTA_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_TRAFFIC_CLASS_ATTRIBUTE_IDS_TYPE: AVPType = 145;
/// Delete all of `ruckus_traffic_class_attribute_ids` values from a packet.
pub fn delete_ruckus_traffic_class_attribute_ids(packet: &mut Packet) {
    packet.delete(RUCKUS_TRAFFIC_CLASS_ATTRIBUTE_IDS_TYPE);
}
/// Add `ruckus_traffic_class_attribute_ids` string value to a packet.
pub fn add_ruckus_traffic_class_attribute_ids(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(
        RUCKUS_TRAFFIC_CLASS_ATTRIBUTE_IDS_TYPE,
        value,
    ));
}
/// Lookup a `ruckus_traffic_class_attribute_ids` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_traffic_class_attribute_ids`, it returns `None`.
pub fn lookup_ruckus_traffic_class_attribute_ids(
    packet: &Packet,
) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_TRAFFIC_CLASS_ATTRIBUTE_IDS_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_traffic_class_attribute_ids` string value from a packet.
pub fn lookup_all_ruckus_traffic_class_attribute_ids(
    packet: &Packet,
) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_TRAFFIC_CLASS_ATTRIBUTE_IDS_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_TC_ATTR_IDS_WITH_QUOTA_TYPE: AVPType = 146;
/// Delete all of `ruckus_tc_attr_ids_with_quota` values from a packet.
pub fn delete_ruckus_tc_attr_ids_with_quota(packet: &mut Packet) {
    packet.delete(RUCKUS_TC_ATTR_IDS_WITH_QUOTA_TYPE);
}
/// Add `ruckus_tc_attr_ids_with_quota` octets value to a packet.
pub fn add_ruckus_tc_attr_ids_with_quota(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_TC_ATTR_IDS_WITH_QUOTA_TYPE, value));
}
/// Lookup a `ruckus_tc_attr_ids_with_quota` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_tc_attr_ids_with_quota`, it returns `None`.
pub fn lookup_ruckus_tc_attr_ids_with_quota(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_TC_ATTR_IDS_WITH_QUOTA_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_tc_attr_ids_with_quota` octets value from a packet.
pub fn lookup_all_ruckus_tc_attr_ids_with_quota(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_TC_ATTR_IDS_WITH_QUOTA_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_NAT_POOL_NAME_TYPE: AVPType = 147;
/// Delete all of `ruckus_nat_pool_name` values from a packet.
pub fn delete_ruckus_nat_pool_name(packet: &mut Packet) {
    packet.delete(RUCKUS_NAT_POOL_NAME_TYPE);
}
/// Add `ruckus_nat_pool_name` string value to a packet.
pub fn add_ruckus_nat_pool_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_NAT_POOL_NAME_TYPE, value));
}
/// Lookup a `ruckus_nat_pool_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_nat_pool_name`, it returns `None`.
pub fn lookup_ruckus_nat_pool_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_NAT_POOL_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_nat_pool_name` string value from a packet.
pub fn lookup_all_ruckus_nat_pool_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_NAT_POOL_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_STA_S_VLAN_ID_TYPE: AVPType = 148;
/// Delete all of `ruckus_sta_s_vlan_id` values from a packet.
pub fn delete_ruckus_sta_s_vlan_id(packet: &mut Packet) {
    packet.delete(RUCKUS_STA_S_VLAN_ID_TYPE);
}
/// Add `ruckus_sta_s_vlan_id` integer value to a packet.
pub fn add_ruckus_sta_s_vlan_id(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(RUCKUS_STA_S_VLAN_ID_TYPE, value));
}
/// Lookup a `ruckus_sta_s_vlan_id` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sta_s_vlan_id`, it returns `None`.
pub fn lookup_ruckus_sta_s_vlan_id(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(RUCKUS_STA_S_VLAN_ID_TYPE)
        .map(|v| v.encode_u32())
}
/// Lookup all of the `ruckus_sta_s_vlan_id` integer value from a packet.
pub fn lookup_all_ruckus_sta_s_vlan_id(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_STA_S_VLAN_ID_TYPE) {
        vec.push(avp.encode_u32()?)
    }
    Ok(vec)
}

pub const RUCKUS_TC_ACCT_CTRS_TYPE: AVPType = 149;
/// Delete all of `ruckus_tc_acct_ctrs` values from a packet.
pub fn delete_ruckus_tc_acct_ctrs(packet: &mut Packet) {
    packet.delete(RUCKUS_TC_ACCT_CTRS_TYPE);
}
/// Add `ruckus_tc_acct_ctrs` octets value to a packet.
pub fn add_ruckus_tc_acct_ctrs(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_TC_ACCT_CTRS_TYPE, value));
}
/// Lookup a `ruckus_tc_acct_ctrs` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_tc_acct_ctrs`, it returns `None`.
pub fn lookup_ruckus_tc_acct_ctrs(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_TC_ACCT_CTRS_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_tc_acct_ctrs` octets value from a packet.
pub fn lookup_all_ruckus_tc_acct_ctrs(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_TC_ACCT_CTRS_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_AAA_ID_TYPE: AVPType = 152;
/// Delete all of `ruckus_aaa_id` values from a packet.
pub fn delete_ruckus_aaa_id(packet: &mut Packet) {
    packet.delete(RUCKUS_AAA_ID_TYPE);
}
/// Add `ruckus_aaa_id` string value to a packet.
pub fn add_ruckus_aaa_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_AAA_ID_TYPE, value));
}
/// Lookup a `ruckus_aaa_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_aaa_id`, it returns `None`.
pub fn lookup_ruckus_aaa_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(RUCKUS_AAA_ID_TYPE).map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_aaa_id` string value from a packet.
pub fn lookup_all_ruckus_aaa_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_AAA_ID_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_DPSK_PARAMS_TYPE: AVPType = 153;
/// Delete all of `ruckus_dpsk_params` values from a packet.
pub fn delete_ruckus_dpsk_params(packet: &mut Packet) {
    packet.delete(RUCKUS_DPSK_PARAMS_TYPE);
}
/// Add `ruckus_dpsk_params` octets value to a packet.
pub fn add_ruckus_dpsk_params(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(RUCKUS_DPSK_PARAMS_TYPE, value));
}
/// Lookup a `ruckus_dpsk_params` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_dpsk_params`, it returns `None`.
pub fn lookup_ruckus_dpsk_params(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(RUCKUS_DPSK_PARAMS_TYPE)
        .map(|v| v.encode_bytes())
}
/// Lookup all of the `ruckus_dpsk_params` octets value from a packet.
pub fn lookup_all_ruckus_dpsk_params(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_DPSK_PARAMS_TYPE) {
        vec.push(avp.encode_bytes())
    }
    vec
}

pub const RUCKUS_CLUSTER_NAME_TYPE: AVPType = 154;
/// Delete all of `ruckus_cluster_name` values from a packet.
pub fn delete_ruckus_cluster_name(packet: &mut Packet) {
    packet.delete(RUCKUS_CLUSTER_NAME_TYPE);
}
/// Add `ruckus_cluster_name` string value to a packet.
pub fn add_ruckus_cluster_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_CLUSTER_NAME_TYPE, value));
}
/// Lookup a `ruckus_cluster_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_cluster_name`, it returns `None`.
pub fn lookup_ruckus_cluster_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_CLUSTER_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_cluster_name` string value from a packet.
pub fn lookup_all_ruckus_cluster_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CLUSTER_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_DOMAIN_NAME_TYPE: AVPType = 155;
/// Delete all of `ruckus_domain_name` values from a packet.
pub fn delete_ruckus_domain_name(packet: &mut Packet) {
    packet.delete(RUCKUS_DOMAIN_NAME_TYPE);
}
/// Add `ruckus_domain_name` string value to a packet.
pub fn add_ruckus_domain_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_DOMAIN_NAME_TYPE, value));
}
/// Lookup a `ruckus_domain_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_domain_name`, it returns `None`.
pub fn lookup_ruckus_domain_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_DOMAIN_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_domain_name` string value from a packet.
pub fn lookup_all_ruckus_domain_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_DOMAIN_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_CLIENT_DEVICE_TYPE_TYPE: AVPType = 156;
/// Delete all of `ruckus_client_device_type` values from a packet.
pub fn delete_ruckus_client_device_type(packet: &mut Packet) {
    packet.delete(RUCKUS_CLIENT_DEVICE_TYPE_TYPE);
}
/// Add `ruckus_client_device_type` string value to a packet.
pub fn add_ruckus_client_device_type(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_CLIENT_DEVICE_TYPE_TYPE, value));
}
/// Lookup a `ruckus_client_device_type` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_client_device_type`, it returns `None`.
pub fn lookup_ruckus_client_device_type(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_CLIENT_DEVICE_TYPE_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_client_device_type` string value from a packet.
pub fn lookup_all_ruckus_client_device_type(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_CLIENT_DEVICE_TYPE_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_VLAN_NAME_TYPE: AVPType = 157;
/// Delete all of `ruckus_vlan_name` values from a packet.
pub fn delete_ruckus_vlan_name(packet: &mut Packet) {
    packet.delete(RUCKUS_VLAN_NAME_TYPE);
}
/// Add `ruckus_vlan_name` string value to a packet.
pub fn add_ruckus_vlan_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_VLAN_NAME_TYPE, value));
}
/// Lookup a `ruckus_vlan_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_vlan_name`, it returns `None`.
pub fn lookup_ruckus_vlan_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_VLAN_NAME_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_vlan_name` string value from a packet.
pub fn lookup_all_ruckus_vlan_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_VLAN_NAME_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_SCI_ROLE_TYPE: AVPType = 200;
/// Delete all of `ruckus_sci_role` values from a packet.
pub fn delete_ruckus_sci_role(packet: &mut Packet) {
    packet.delete(RUCKUS_SCI_ROLE_TYPE);
}
/// Add `ruckus_sci_role` string value to a packet.
pub fn add_ruckus_sci_role(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_SCI_ROLE_TYPE, value));
}
/// Lookup a `ruckus_sci_role` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sci_role`, it returns `None`.
pub fn lookup_ruckus_sci_role(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_SCI_ROLE_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_sci_role` string value from a packet.
pub fn lookup_all_ruckus_sci_role(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SCI_ROLE_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub const RUCKUS_SCI_RESOURCE_GROUP_TYPE: AVPType = 201;
/// Delete all of `ruckus_sci_resource_group` values from a packet.
pub fn delete_ruckus_sci_resource_group(packet: &mut Packet) {
    packet.delete(RUCKUS_SCI_RESOURCE_GROUP_TYPE);
}
/// Add `ruckus_sci_resource_group` string value to a packet.
pub fn add_ruckus_sci_resource_group(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(RUCKUS_SCI_RESOURCE_GROUP_TYPE, value));
}
/// Lookup a `ruckus_sci_resource_group` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `ruckus_sci_resource_group`, it returns `None`.
pub fn lookup_ruckus_sci_resource_group(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(RUCKUS_SCI_RESOURCE_GROUP_TYPE)
        .map(|v| v.encode_string())
}
/// Lookup all of the `ruckus_sci_resource_group` string value from a packet.
pub fn lookup_all_ruckus_sci_resource_group(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(RUCKUS_SCI_RESOURCE_GROUP_TYPE) {
        vec.push(avp.encode_string()?)
    }
    Ok(vec)
}

pub type RuckusAPNResolutionReq = u32;
pub const RUCKUS_APN_RESOLUTION_REQ_NOT_REQUIRED: RuckusAPNResolutionReq = 0;
pub const RUCKUS_APN_RESOLUTION_REQ_REQUIRED: RuckusAPNResolutionReq = 1;

pub type RuckusAccountingStatus = u32;
pub const RUCKUS_ACCOUNTING_STATUS_ACCOUNTING_ON: RuckusAccountingStatus = 1;
pub const RUCKUS_ACCOUNTING_STATUS_ACCOUNTING_OFF: RuckusAccountingStatus = 0;

pub type RuckusAuthType = u32;
pub const RUCKUS_AUTH_TYPE_PPP_SIM: RuckusAuthType = 1;
pub const RUCKUS_AUTH_TYPE_DUMMY_IMSI: RuckusAuthType = 2;
pub const RUCKUS_AUTH_TYPE_SOFT_SIM: RuckusAuthType = 3;
pub const RUCKUS_AUTH_TYPE_RADIUS_SIM: RuckusAuthType = 4;
pub const RUCKUS_AUTH_TYPE_POSTPAID: RuckusAuthType = 5;
pub const RUCKUS_AUTH_TYPE_PREPAID: RuckusAuthType = 6;
pub const RUCKUS_AUTH_TYPE_LOCAL_RADIUS: RuckusAuthType = 7;
pub const RUCKUS_AUTH_TYPE_PROXY_RADIUS: RuckusAuthType = 8;
pub const RUCKUS_AUTH_TYPE_VOUCHER: RuckusAuthType = 9;
pub const RUCKUS_AUTH_TYPE_EAP_SIM: RuckusAuthType = 10;

pub type RuckusNASType = u32;
pub const RUCKUS_NAS_TYPE_SCG: RuckusNASType = 1;
pub const RUCKUS_NAS_TYPE_OTHERS: RuckusNASType = 2;

pub type RuckusSelectionMode = u32;
pub const RUCKUS_SELECTION_MODE_SUBSCRIBED: RuckusSelectionMode = 0;
pub const RUCKUS_SELECTION_MODE_SENT_BY_MS: RuckusSelectionMode = 1;
pub const RUCKUS_SELECTION_MODE_CHOSEN_BY_SGSN: RuckusSelectionMode = 2;

pub type RuckusSessionType = u32;
pub const RUCKUS_SESSION_TYPE_TTG: RuckusSessionType = 2;
pub const RUCKUS_SESSION_TYPE_LOCAL_BREAKOUT: RuckusSessionType = 3;
pub const RUCKUS_SESSION_TYPE_LOCAL_BREAKOUT_AP: RuckusSessionType = 4;
pub const RUCKUS_SESSION_TYPE_L3GRE: RuckusSessionType = 5;
pub const RUCKUS_SESSION_TYPE_L2GRE: RuckusSessionType = 6;
pub const RUCKUS_SESSION_TYPE_QIN_QL3: RuckusSessionType = 7;
pub const RUCKUS_SESSION_TYPE_PMIP: RuckusSessionType = 8;

pub type RuckusStatus = u32;
pub const RUCKUS_STATUS_SUCCESS: RuckusStatus = 0;
pub const RUCKUS_STATUS_FAILURE: RuckusStatus = 1;
