// Code generated by machine generator; DO NOT EDIT.
// Clippy: `#[must_use]` on functions returning `Option`/`Result` is intentional even though
// those types are already `#[must_use]`; the attribute surfaces better IDE messages.
#![allow(clippy::double_must_use)]

//! Utility for wispr packet.
//!
//! This module handles the packet according to the following definition:
//! ```text
//! //! # -*- text -*-
//! # Copyright (C) 2019 The FreeRADIUS Server project and contributors
//! # This work is licensed under CC-BY version 4.0 https://creativecommons.org/licenses/by/4.0
//! #
//! # dictionary.wispr
//! #
//! #  Attributes from the Wireless Broadband Alliance (used to be Wispr)
//! #
//! #  Updated attributes are at
//! #
//! #    https://github.com/wireless-broadband-alliance/RADIUS-VSA
//! #
//! # Version:    $Id$
//! #
//!
//! VENDOR        WISPr                14122
//!
//! #
//! #    Standard attribute
//! #
//! BEGIN-VENDOR    WISPr
//!
//! ATTRIBUTE    WISPr-Location-ID            1    string
//! ATTRIBUTE    WISPr-Location-Name            2    string
//! ATTRIBUTE    WISPr-Logoff-URL            3    string
//! ATTRIBUTE    WISPr-Redirection-URL            4    string
//! ATTRIBUTE    WISPr-Bandwidth-Min-Up            5    integer
//! ATTRIBUTE    WISPr-Bandwidth-Min-Down        6    integer
//! ATTRIBUTE    WISPr-Bandwidth-Max-Up            7    integer
//! ATTRIBUTE    WISPr-Bandwidth-Max-Down        8    integer
//! ATTRIBUTE    WISPr-Session-Terminate-Time        9    string
//! ATTRIBUTE    WISPr-Session-Terminate-End-Of-Day    10    string
//! ATTRIBUTE    WISPr-Billing-Class-Of-Service        11    string
//!
//! ATTRIBUTE    WBA-Offered-Service            12    string
//! ATTRIBUTE    WBA-Financial-Clearing-Provider        13    string
//! ATTRIBUTE    WBA-Data-Clearing-Provider        14    string
//! ATTRIBUTE    WBA-Linear-Volume-Rate            15    octets
//! ATTRIBUTE    WBA-Identity-Provider            16    string
//! ATTRIBUTE    WBA-Custom-SLA            17    string
//!
//! END-VENDOR    WISPr
//! ```

use crate::core::avp::{AVPError, AVPType, AVP};
use crate::core::packet::Packet;

pub const WIS_PR_LOCATION_ID_TYPE: AVPType = 1;
/// Delete all of `wis_pr_location_id` values from a packet.
pub fn delete_wis_pr_location_id(packet: &mut Packet) {
    packet.delete(WIS_PR_LOCATION_ID_TYPE);
}
/// Add `wis_pr_location_id` string value to a packet.
pub fn add_wis_pr_location_id(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WIS_PR_LOCATION_ID_TYPE, value));
}
/// Lookup a `wis_pr_location_id` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_location_id`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_location_id(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WIS_PR_LOCATION_ID_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wis_pr_location_id` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_location_id(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_LOCATION_ID_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WIS_PR_LOCATION_NAME_TYPE: AVPType = 2;
/// Delete all of `wis_pr_location_name` values from a packet.
pub fn delete_wis_pr_location_name(packet: &mut Packet) {
    packet.delete(WIS_PR_LOCATION_NAME_TYPE);
}
/// Add `wis_pr_location_name` string value to a packet.
pub fn add_wis_pr_location_name(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WIS_PR_LOCATION_NAME_TYPE, value));
}
/// Lookup a `wis_pr_location_name` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_location_name`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_location_name(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WIS_PR_LOCATION_NAME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wis_pr_location_name` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_location_name(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_LOCATION_NAME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WIS_PR_LOGOFF_URL_TYPE: AVPType = 3;
/// Delete all of `wis_pr_logoff_url` values from a packet.
pub fn delete_wis_pr_logoff_url(packet: &mut Packet) {
    packet.delete(WIS_PR_LOGOFF_URL_TYPE);
}
/// Add `wis_pr_logoff_url` string value to a packet.
pub fn add_wis_pr_logoff_url(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WIS_PR_LOGOFF_URL_TYPE, value));
}
/// Lookup a `wis_pr_logoff_url` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_logoff_url`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_logoff_url(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WIS_PR_LOGOFF_URL_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wis_pr_logoff_url` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_logoff_url(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_LOGOFF_URL_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WIS_PR_REDIRECTION_URL_TYPE: AVPType = 4;
/// Delete all of `wis_pr_redirection_url` values from a packet.
pub fn delete_wis_pr_redirection_url(packet: &mut Packet) {
    packet.delete(WIS_PR_REDIRECTION_URL_TYPE);
}
/// Add `wis_pr_redirection_url` string value to a packet.
pub fn add_wis_pr_redirection_url(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WIS_PR_REDIRECTION_URL_TYPE, value));
}
/// Lookup a `wis_pr_redirection_url` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_redirection_url`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_redirection_url(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WIS_PR_REDIRECTION_URL_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wis_pr_redirection_url` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_redirection_url(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_REDIRECTION_URL_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WIS_PR_BANDWIDTH_MIN_UP_TYPE: AVPType = 5;
/// Delete all of `wis_pr_bandwidth_min_up` values from a packet.
pub fn delete_wis_pr_bandwidth_min_up(packet: &mut Packet) {
    packet.delete(WIS_PR_BANDWIDTH_MIN_UP_TYPE);
}
/// Add `wis_pr_bandwidth_min_up` integer value to a packet.
pub fn add_wis_pr_bandwidth_min_up(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(WIS_PR_BANDWIDTH_MIN_UP_TYPE, value));
}
/// Lookup a `wis_pr_bandwidth_min_up` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_bandwidth_min_up`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_bandwidth_min_up(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(WIS_PR_BANDWIDTH_MIN_UP_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `wis_pr_bandwidth_min_up` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_bandwidth_min_up(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_BANDWIDTH_MIN_UP_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const WIS_PR_BANDWIDTH_MIN_DOWN_TYPE: AVPType = 6;
/// Delete all of `wis_pr_bandwidth_min_down` values from a packet.
pub fn delete_wis_pr_bandwidth_min_down(packet: &mut Packet) {
    packet.delete(WIS_PR_BANDWIDTH_MIN_DOWN_TYPE);
}
/// Add `wis_pr_bandwidth_min_down` integer value to a packet.
pub fn add_wis_pr_bandwidth_min_down(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(WIS_PR_BANDWIDTH_MIN_DOWN_TYPE, value));
}
/// Lookup a `wis_pr_bandwidth_min_down` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_bandwidth_min_down`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_bandwidth_min_down(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(WIS_PR_BANDWIDTH_MIN_DOWN_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `wis_pr_bandwidth_min_down` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_bandwidth_min_down(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_BANDWIDTH_MIN_DOWN_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const WIS_PR_BANDWIDTH_MAX_UP_TYPE: AVPType = 7;
/// Delete all of `wis_pr_bandwidth_max_up` values from a packet.
pub fn delete_wis_pr_bandwidth_max_up(packet: &mut Packet) {
    packet.delete(WIS_PR_BANDWIDTH_MAX_UP_TYPE);
}
/// Add `wis_pr_bandwidth_max_up` integer value to a packet.
pub fn add_wis_pr_bandwidth_max_up(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(WIS_PR_BANDWIDTH_MAX_UP_TYPE, value));
}
/// Lookup a `wis_pr_bandwidth_max_up` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_bandwidth_max_up`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_bandwidth_max_up(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(WIS_PR_BANDWIDTH_MAX_UP_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `wis_pr_bandwidth_max_up` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_bandwidth_max_up(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_BANDWIDTH_MAX_UP_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const WIS_PR_BANDWIDTH_MAX_DOWN_TYPE: AVPType = 8;
/// Delete all of `wis_pr_bandwidth_max_down` values from a packet.
pub fn delete_wis_pr_bandwidth_max_down(packet: &mut Packet) {
    packet.delete(WIS_PR_BANDWIDTH_MAX_DOWN_TYPE);
}
/// Add `wis_pr_bandwidth_max_down` integer value to a packet.
pub fn add_wis_pr_bandwidth_max_down(packet: &mut Packet, value: u32) {
    packet.add(AVP::from_u32(WIS_PR_BANDWIDTH_MAX_DOWN_TYPE, value));
}
/// Lookup a `wis_pr_bandwidth_max_down` integer value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_bandwidth_max_down`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_bandwidth_max_down(packet: &Packet) -> Option<Result<u32, AVPError>> {
    packet
        .lookup(WIS_PR_BANDWIDTH_MAX_DOWN_TYPE)
        .map(AVP::encode_u32)
}
/// Lookup all of the `wis_pr_bandwidth_max_down` integer value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_bandwidth_max_down(packet: &Packet) -> Result<Vec<u32>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_BANDWIDTH_MAX_DOWN_TYPE) {
        vec.push(avp.encode_u32()?);
    }
    Ok(vec)
}

pub const WIS_PR_SESSION_TERMINATE_TIME_TYPE: AVPType = 9;
/// Delete all of `wis_pr_session_terminate_time` values from a packet.
pub fn delete_wis_pr_session_terminate_time(packet: &mut Packet) {
    packet.delete(WIS_PR_SESSION_TERMINATE_TIME_TYPE);
}
/// Add `wis_pr_session_terminate_time` string value to a packet.
pub fn add_wis_pr_session_terminate_time(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WIS_PR_SESSION_TERMINATE_TIME_TYPE, value));
}
/// Lookup a `wis_pr_session_terminate_time` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_session_terminate_time`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_session_terminate_time(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WIS_PR_SESSION_TERMINATE_TIME_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wis_pr_session_terminate_time` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_session_terminate_time(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_SESSION_TERMINATE_TIME_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WIS_PR_SESSION_TERMINATE_END_OF_DAY_TYPE: AVPType = 10;
/// Delete all of `wis_pr_session_terminate_end_of_day` values from a packet.
pub fn delete_wis_pr_session_terminate_end_of_day(packet: &mut Packet) {
    packet.delete(WIS_PR_SESSION_TERMINATE_END_OF_DAY_TYPE);
}
/// Add `wis_pr_session_terminate_end_of_day` string value to a packet.
pub fn add_wis_pr_session_terminate_end_of_day(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(
        WIS_PR_SESSION_TERMINATE_END_OF_DAY_TYPE,
        value,
    ));
}
/// Lookup a `wis_pr_session_terminate_end_of_day` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_session_terminate_end_of_day`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_session_terminate_end_of_day(
    packet: &Packet,
) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WIS_PR_SESSION_TERMINATE_END_OF_DAY_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wis_pr_session_terminate_end_of_day` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_session_terminate_end_of_day(
    packet: &Packet,
) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_SESSION_TERMINATE_END_OF_DAY_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WIS_PR_BILLING_CLASS_OF_SERVICE_TYPE: AVPType = 11;
/// Delete all of `wis_pr_billing_class_of_service` values from a packet.
pub fn delete_wis_pr_billing_class_of_service(packet: &mut Packet) {
    packet.delete(WIS_PR_BILLING_CLASS_OF_SERVICE_TYPE);
}
/// Add `wis_pr_billing_class_of_service` string value to a packet.
pub fn add_wis_pr_billing_class_of_service(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(
        WIS_PR_BILLING_CLASS_OF_SERVICE_TYPE,
        value,
    ));
}
/// Lookup a `wis_pr_billing_class_of_service` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wis_pr_billing_class_of_service`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wis_pr_billing_class_of_service(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WIS_PR_BILLING_CLASS_OF_SERVICE_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wis_pr_billing_class_of_service` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wis_pr_billing_class_of_service(
    packet: &Packet,
) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WIS_PR_BILLING_CLASS_OF_SERVICE_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WBA_OFFERED_SERVICE_TYPE: AVPType = 12;
/// Delete all of `wba_offered_service` values from a packet.
pub fn delete_wba_offered_service(packet: &mut Packet) {
    packet.delete(WBA_OFFERED_SERVICE_TYPE);
}
/// Add `wba_offered_service` string value to a packet.
pub fn add_wba_offered_service(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WBA_OFFERED_SERVICE_TYPE, value));
}
/// Lookup a `wba_offered_service` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wba_offered_service`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wba_offered_service(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WBA_OFFERED_SERVICE_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wba_offered_service` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wba_offered_service(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WBA_OFFERED_SERVICE_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WBA_FINANCIAL_CLEARING_PROVIDER_TYPE: AVPType = 13;
/// Delete all of `wba_financial_clearing_provider` values from a packet.
pub fn delete_wba_financial_clearing_provider(packet: &mut Packet) {
    packet.delete(WBA_FINANCIAL_CLEARING_PROVIDER_TYPE);
}
/// Add `wba_financial_clearing_provider` string value to a packet.
pub fn add_wba_financial_clearing_provider(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(
        WBA_FINANCIAL_CLEARING_PROVIDER_TYPE,
        value,
    ));
}
/// Lookup a `wba_financial_clearing_provider` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wba_financial_clearing_provider`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wba_financial_clearing_provider(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WBA_FINANCIAL_CLEARING_PROVIDER_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wba_financial_clearing_provider` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wba_financial_clearing_provider(
    packet: &Packet,
) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WBA_FINANCIAL_CLEARING_PROVIDER_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WBA_DATA_CLEARING_PROVIDER_TYPE: AVPType = 14;
/// Delete all of `wba_data_clearing_provider` values from a packet.
pub fn delete_wba_data_clearing_provider(packet: &mut Packet) {
    packet.delete(WBA_DATA_CLEARING_PROVIDER_TYPE);
}
/// Add `wba_data_clearing_provider` string value to a packet.
pub fn add_wba_data_clearing_provider(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WBA_DATA_CLEARING_PROVIDER_TYPE, value));
}
/// Lookup a `wba_data_clearing_provider` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wba_data_clearing_provider`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wba_data_clearing_provider(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WBA_DATA_CLEARING_PROVIDER_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wba_data_clearing_provider` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wba_data_clearing_provider(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WBA_DATA_CLEARING_PROVIDER_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WBA_LINEAR_VOLUME_RATE_TYPE: AVPType = 15;
/// Delete all of `wba_linear_volume_rate` values from a packet.
pub fn delete_wba_linear_volume_rate(packet: &mut Packet) {
    packet.delete(WBA_LINEAR_VOLUME_RATE_TYPE);
}
/// Add `wba_linear_volume_rate` octets value to a packet.
pub fn add_wba_linear_volume_rate(packet: &mut Packet, value: &[u8]) {
    packet.add(AVP::from_bytes(WBA_LINEAR_VOLUME_RATE_TYPE, value));
}
/// Lookup a `wba_linear_volume_rate` octets value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wba_linear_volume_rate`, it returns `None`.
#[must_use]
pub fn lookup_wba_linear_volume_rate(packet: &Packet) -> Option<Vec<u8>> {
    packet
        .lookup(WBA_LINEAR_VOLUME_RATE_TYPE)
        .map(AVP::encode_bytes)
}
/// Lookup all of the `wba_linear_volume_rate` octets value from a packet.
#[must_use]
pub fn lookup_all_wba_linear_volume_rate(packet: &Packet) -> Vec<Vec<u8>> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WBA_LINEAR_VOLUME_RATE_TYPE) {
        vec.push(avp.encode_bytes());
    }
    vec
}

pub const WBA_IDENTITY_PROVIDER_TYPE: AVPType = 16;
/// Delete all of `wba_identity_provider` values from a packet.
pub fn delete_wba_identity_provider(packet: &mut Packet) {
    packet.delete(WBA_IDENTITY_PROVIDER_TYPE);
}
/// Add `wba_identity_provider` string value to a packet.
pub fn add_wba_identity_provider(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WBA_IDENTITY_PROVIDER_TYPE, value));
}
/// Lookup a `wba_identity_provider` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wba_identity_provider`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wba_identity_provider(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet
        .lookup(WBA_IDENTITY_PROVIDER_TYPE)
        .map(AVP::encode_string)
}
/// Lookup all of the `wba_identity_provider` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wba_identity_provider(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WBA_IDENTITY_PROVIDER_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}

pub const WBA_CUSTOM_SLA_TYPE: AVPType = 17;
/// Delete all of `wba_custom_sla` values from a packet.
pub fn delete_wba_custom_sla(packet: &mut Packet) {
    packet.delete(WBA_CUSTOM_SLA_TYPE);
}
/// Add `wba_custom_sla` string value to a packet.
pub fn add_wba_custom_sla(packet: &mut Packet, value: &str) {
    packet.add(AVP::from_string(WBA_CUSTOM_SLA_TYPE, value));
}
/// Lookup a `wba_custom_sla` string value from a packet.
///
/// It returns the first looked up value. If there is no associated value with `wba_custom_sla`, it returns `None`.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_wba_custom_sla(packet: &Packet) -> Option<Result<String, AVPError>> {
    packet.lookup(WBA_CUSTOM_SLA_TYPE).map(AVP::encode_string)
}
/// Lookup all of the `wba_custom_sla` string value from a packet.
///
/// # Errors
///
/// Returns an `AVPError` if decoding fails.
#[must_use]
pub fn lookup_all_wba_custom_sla(packet: &Packet) -> Result<Vec<String>, AVPError> {
    let mut vec = Vec::new();
    for avp in packet.lookup_all(WBA_CUSTOM_SLA_TYPE) {
        vec.push(avp.encode_string()?);
    }
    Ok(vec)
}
